### ISSUE TITLE
Game immediately crashes after I join/create a world

### ISSUE THREAD

**Issue by aSpeedy** [cabaletta/baritone#1039]
## Some information
Operating system:Windows 10 
Java version: Version 8 (build 1.8.0_211-b11)
Minecraft version:1.14.4
Baritone version: 1.14.4
Forge mods (if used): None 

## Exception, error or logs
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12.10.2019 13:43
Description: Unexpected error

java.lang.NoClassDefFoundError: dke
	at dkc.a(SourceFile:346)
	at ls.a(SourceFile:76)
	at ls.a(SourceFile:13)
	at ke.a(SourceFile:21)
	at ke$$Lambda$2817/165043682.run(Unknown Source)
	at agq.h(SourceFile:144)
	at agu.h(SourceFile:23)
	at agq.q(SourceFile:118)
	at agq.bh(SourceFile:103)
	at cyc.e(SourceFile:915)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dke
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinPlayerController] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 23 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ısHittingBlock:Z in dke for mixins.baritone.json:MixinPlayerController->@Accessor[FIELD_SETTER]::setIsHittingBlock(Z)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 23 more

## How to reproduce

**Comment by enderman2s** [comment]
Have you tested it without baritone?

**Comment by aSpeedy** [comment]
> Have you tested it without baritone?

When I got the error first time, I tested and it didnt have  any problems
Now that I tested again, it gives the same error with default & optifine version, I'll try  re-downloading  the game

**Comment by ZeroMemes** [comment]
What environment are you running baritone in?

**Comment by TheK0tYaRa** [comment]
Try running latest forge
