### ISSUE TITLE
My build command doesn't work

### ISSUE THREAD

**Issue by PokePercy** [cabaletta/baritone#1085]
Operating system: win 10 home
Java version:
Minecraft version:1.14.4
Baritone version:v1.4.3
Forge mods (if used): 
 
The text An unhandled error has occurred. This error is your games log, please report this at  https://github.com/cabaletta/baritone/issues

**Comment by TheK0tYaRa** [comment]
You need to add the error logs for this to be usefull.

**Comment by hde-ghel** [comment]
Here is a log for that issue (same config, same error), But i think it's just doesn't work on 1.14. Could you confirm that plz ?

`[17:00:35] [main/INFO]: [CHAT] [Baritone] > build Wolf-3D
[17:00:35] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:00:35] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3897/15784778.accept(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:14)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:25)
[17:00:35] [main/INFO]: [STDERR]: 	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:00:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.2B.0(2B.java:41)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.1M$$Lambda$2173/663126311.0(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.03U.0(03U.java:28)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.1A.0(1A.java:22)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.1A$$Lambda$2188/1473885540.invoke(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[17:00:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[17:00:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1721/882678778.accept(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[17:00:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[17:00:35] [main/INFO]: [STDERR]: 	at net.impactclient.5Q.post(5Q.java:3)
[17:00:35] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1226)
[17:00:35] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[17:00:35] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[17:00:35] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[17:00:35] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[17:00:35] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[17:00:35] [main/INFO]: [STDERR]: 	at cya$$Lambda$3726/1883769182.run(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[17:00:35] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[17:00:35] [main/INFO]: [STDERR]: 	at cya$$Lambda$1497/985823021.invoke(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:00:35] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:00:35] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17:00:35] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[17:00:35] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[17:00:35] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[17:00:35] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[17:00:35] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[17:00:35] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[17:00:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:00:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:00:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:00:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:00:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:00:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:00:35] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[17:00:35] [main/INFO]: [STDERR]: 	... 48 more`

**Comment by StijnSimons** [comment]
1.13+ not supported.

**Comment by TheK0tYaRa** [comment]
#1102
