### ISSUE TITLE
The schematic doesn't work

### ISSUE THREAD

**Issue by ckle2101** [cabaletta/baritone#1093]
The log says:

[20:54:17] [main/INFO]: [CHAT] [Baritone] > build heart
[20:54:17] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[20:54:17] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3688/965614152.accept(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:14)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:25)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:54:17] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.2B.0(2B.java:41)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.1M$$Lambda$2157/584527001.0(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.03U.0(03U.java:28)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.1A.0(1A.java:22)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.1A$$Lambda$2181/458593254.invoke(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[20:54:17] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[20:54:17] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1667/2123448049.accept(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:54:17] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[20:54:17] [main/INFO]: [STDERR]: 	at net.impactclient.5Q.post(5Q.java:3)
[20:54:17] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1226)
[20:54:17] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[20:54:17] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[20:54:17] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[20:54:17] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[20:54:17] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[20:54:17] [main/INFO]: [STDERR]: 	at cya$$Lambda$3648/422288949.run(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[20:54:17] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[20:54:17] [main/INFO]: [STDERR]: 	at cya$$Lambda$1462/1838736903.invoke(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[20:54:17] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[20:54:17] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[20:54:17] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:291)
[20:54:17] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1027)
[20:54:17] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[20:54:17] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[20:54:17] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:54:17] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:54:17] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:54:17] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:54:17] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:54:17] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[20:54:17] [main/INFO]: [STDERR]: 	... 48 more

**Comment by TheK0tYaRa** [comment]
Baritone had a problem with numerical IDs in the schematic for 1.13

**Comment by ckle2101** [comment]
so what does that mean

**Comment by TheK0tYaRa** [comment]
It basically means "use schematic for your minecraft version"

**Comment by ckle2101** [comment]
How do I do that?

On Oct 23, 2019, at 9:31 PM, TheK0tYaRa <notifications@github.com> wrote:

﻿

It basically means "use schematic for your minecraft version"

**Comment by TheK0tYaRa** [comment]
Just don't use build. Use fill, shell, walls in the context of #sel and multiple selections. I do so a lot and am very happy with it.

**Comment by ckle2101** [comment]
Ok thanks

Cole Kleinhans

On Oct 25, 2019, at 3:02 AM, TheK0tYaRa <notifications@github.com> wrote:

﻿

Just don't use build. Use fill, shell, walls in the context of #sel and multiple selections. I do so a lot and am very happy with it.
