### ISSUE TITLE
Command .b build

### ISSUE THREAD

**Issue by Morddy** [cabaletta/baritone#1102]
14:16:35] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3486/554507077.accept(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:14)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:25)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:16:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.2B.0(2B.java:41)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.1M$$Lambda$2138/741557488.0(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.03U.0(03U.java:28)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.1A.0(1A.java:22)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.1A$$Lambda$2153/1938502831.invoke(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[14:16:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[14:16:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1685/2112179175.accept(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[14:16:35] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[14:16:35] [main/INFO]: [STDERR]: 	at net.impactclient.5Q.post(5Q.java:3)
[14:16:35] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1226)
[14:16:35] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[14:16:35] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[14:16:35] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[14:16:35] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[14:16:35] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[14:16:35] [main/INFO]: [STDERR]: 	at cya$$Lambda$3479/951141924.run(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[14:16:35] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[14:16:35] [main/INFO]: [STDERR]: 	at cya$$Lambda$1460/1837241461.invoke(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[14:16:35] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[14:16:35] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[14:16:35] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[14:16:35] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[14:16:35] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[14:16:35] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[14:16:35] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[14:16:35] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:16:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:16:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:16:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:16:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:16:35] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[14:16:35] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
Those are logs around time i used command .b build

**Comment by TheK0tYaRa** [comment]
This is a generic issue of everybody who uses build with old schematics
