### ISSUE TITLE
cant build schematics

### ISSUE THREAD

**Issue by aiden-bod** [cabaletta/baritone#1107]
[16:36:39] [main/INFO]: [CHAT] [Baritone] > build jesusobbynorth
[16:36:39] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:36:39] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$2982/238673731.accept(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[16:36:39] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[16:36:39] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:36:39] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:36:39] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:36:39] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:36:39] [main/INFO]: [STDERR]: 	at cya$$Lambda$2952/995691809.run(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:36:39] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:36:39] [main/INFO]: [STDERR]: 	at cya$$Lambda$1506/1371955400.invoke(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:36:39] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:36:39] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:36:39] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[16:36:39] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[16:36:39] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[16:36:39] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:36:39] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:36:39] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:36:39] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:36:39] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:36:39] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:36:39] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:36:39] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:36:39] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:36:39] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:36:39] [main/INFO]: [STDERR]: 	... 32 more

trying to build a redeemer statue with obsidian, no idea why it wont work

**Comment by aiden-bod** [comment]
oops 1.14 cant build, also whyn't

**Comment by TheK0tYaRa** [comment]
#1102
