### ISSUE TITLE
Using Wurst+ Baritone = error

### ISSUE THREAD

**Issue by RajehTXD** [cabaletta/baritone#1119]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WCoreMod (ForgeWurst-0.11-MC1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 11/2/19 12:07 PM
Description: Initializing game

java.lang.NoSuchMethodError: baritone.api.IBaritoneProvider.getPrimaryBaritone()Lbaritone/api/IBaritone;
	at net.impactclient.2X.0(Unknown Source)
	at net.impactclient.4G.0(Unknown Source)
	at net.minecraft.client.Minecraft.handler$init$zbl000(Minecraft.java:3854)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:570)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.impactclient.2X.0(Unknown Source)
	at net.impactclient.4G.0(Unknown Source)
	at net.minecraft.client.Minecraft.handler$init$zbl000(Minecraft.java:3854)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:570)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1368552832 bytes (1305 MB) / 1879048192 bytes (1792 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                        | Signature                                |
	|:------ |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forgewurst | 0.11         | ForgeWurst-0.11-MC1.12.2.jar  | None                                     |

	Loaded coremods (and transformers): 
WCoreMod (ForgeWurst-0.11-MC1.12.2.jar)
  net.wurstclient.forge.asm.WClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6480G'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6480G GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD A4-3300M APU with Radeon(tm) HD Graphics

**Comment by RajehTXD** [comment]
btw used forge to add both

**Comment by RajehTXD** [comment]
even without wurst. same error

**Comment by RajehTXD** [comment]
@cabaletta @leijurv

**Comment by StijnSimons** [comment]
No need to tag anyone, forge __is and will not be supported in case of compatibility issues__.

**Comment by StijnSimons** [comment]
And you got stuff setup wrong
```
java.lang.NoSuchMethodError: baritone.api.IBaritoneProvider.getPrimaryBaritone()Lbaritone/api/IBaritone;
```

**Comment by RajehTXD** [comment]
1.12.2 forge is supported

**Comment by RajehTXD** [comment]
AND BTW I DOWNLOADED THE LAST 1.12.2 MOD  forge standalone.

**Comment by Mhowser** [comment]
Just wait for the Fabric fork of Wurst to finish and run it with Fabritone.

**Comment by StijnSimons** [comment]
Forge is __not__ supported after 1.12.2, again.

**Comment by Mhowser** [comment]
![nick-young-confused-face-300x256-nqlyaa](https://user-images.githubusercontent.com/24195572/68091960-162bb700-fe3b-11e9-8ec8-2682c8c9fd14.jpg)
This is the baritone repo, tho
