### ISSUE TITLE
Baritone can't load ANY schematics (IMPACT)

### ISSUE THREAD

**Issue by VernamChinobi** [cabaletta/baritone#1132]
## Some information
Operating system: Win10 64bit
Java version: 8.0.2110.12
Minecraft version: 1.14.4
Baritone version: v1.4.3
Forge mods (if used): none

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).
[16:37:02] [main/INFO]: [CHAT] [Baritone] > build pene
[16:37:02] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:37:02] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3581/310604146.accept(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:14)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.2A.0(2A.java:25)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:37:02] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.2B.0(2B.java:41)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.1M$$Lambda$2311/1529238393.0(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.03U.0(03U.java:28)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.1A.0(1A.java:22)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.1A$$Lambda$2326/1456310531.invoke(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[16:37:02] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[16:37:02] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1850/105275210.accept(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:37:02] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[16:37:02] [main/INFO]: [STDERR]: 	at net.impactclient.5Q.post(5Q.java:3)
[16:37:02] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1226)
[16:37:02] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[16:37:02] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:37:02] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:37:02] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:37:02] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:37:02] [main/INFO]: [STDERR]: 	at cya$$Lambda$3571/1334679764.run(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:37:02] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:37:02] [main/INFO]: [STDERR]: 	at cya$$Lambda$1538/906413349.invoke(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:37:02] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:37:02] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:37:02] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[16:37:02] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[16:37:02] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[16:37:02] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:37:02] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:37:02] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:37:02] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:37:02] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:37:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:37:02] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:37:02] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:37:02] [main/INFO]: [STDERR]: 	... 49 more
[16:37:05] [Server thread/INFO]: Saving and pausing game...
[16:37:05] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:overworld
[16:37:05] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_end
[16:37:05] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_nether

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
baritone can't load ANY schematics, neither created by myself nor downloaded from other resources.

## Final checklist
- [yeah ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [yeah  ] I have included logs, exceptions and / or steps to reproduce the issue.
- [yeah 
![11111](https://user-images.githubusercontent.com/57532298/68481205-a016be00-0247-11ea-96a4-786df0092be4.png)
 ] I have not used any OwO's or UwU's in this issue. sure lol

**Comment by ThebesAndSound** [comment]
build is not available yet on 1.13+

**Comment by MinecraftDude800** [comment]
This is a known issue. It won't work past 1.12

**Comment by MateoGavela** [comment]
Men i have the same problem

**Comment by S-B99** [comment]
How are people still commenting on this. You need to include `.schematic` after the file name.
