### ISSUE TITLE
build error 1.14.4

### ISSUE THREAD

**Issue by Ehrenf** [cabaletta/baritone#1147]
here is my log
[16:48:02] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[16:48:02] [main/INFO]: Using primary tweak class name baritone.launch.BaritoneTweaker
[16:48:02] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[16:48:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Ehren/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[16:48:02] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[16:48:03] [main/INFO]: Compatibility level set to JAVA_8
[16:48:03] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[16:48:03] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:48:03] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockStateContainer, name: baritone.launch.mixins.MixinBlockStateContainer
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChatScreen, name: baritone.launch.mixins.MixinChatScreen
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkArray, name: baritone.launch.mixins.MixinChunkArray
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientChunkProvider, name: baritone.launch.mixins.MixinClientChunkProvider
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayerEntity, name: baritone.launch.mixins.MixinClientPlayerEntity
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinClientPlayNetHandler, name: baritone.launch.mixins.MixinClientPlayNetHandler
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntity, name: baritone.launch.mixins.MixinEntity
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderManager, name: baritone.launch.mixins.MixinEntityRenderManager
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinGameRenderer, name: baritone.launch.mixins.MixinGameRenderer
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLivingEntity, name: baritone.launch.mixins.MixinLivingEntity
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinLootContext, name: baritone.launch.mixins.MixinLootContext
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerController, name: baritone.launch.mixins.MixinPlayerController
[16:48:03] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinScreen, name: baritone.launch.mixins.MixinScreen
[16:48:03] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:48:04] [main/INFO]: Setting user: EhrensEpicGaming
[16:48:08] [main/WARN]: Skipping bad option: lastServer:
[16:48:08] [main/INFO]: LWJGL Version: 3.2.2 build 10
[16:48:12] [main/INFO]: Narrator library for x64 successfully loaded
[16:48:18] [main/INFO]: OpenAL initialized.
[16:48:18] [main/INFO]: Sound engine started
[16:48:18] [main/INFO]: Created: 2048x2048 textures-atlas
[16:48:19] [main/INFO]: Created: 256x256 textures/particle-atlas
[16:48:19] [main/INFO]: Created: 256x256 textures/painting-atlas
[16:48:19] [main/INFO]: Created: 256x128 textures/mob_effect-atlas
[16:48:41] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:48:41] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:48:41] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:48:41] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:48:41] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:48:41] [Server thread/INFO]: Starting integrated minecraft server version 1.14.4
[16:48:41] [Server thread/INFO]: Generating keypair
[16:48:41] [Server thread/INFO]: Reloading ResourceManager: Default
[16:48:42] [Server thread/INFO]: Loaded 6 recipes
[16:48:42] [Server thread/INFO]: Loaded 811 advancements
[16:48:42] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:48:43] [main/INFO]: Preparing spawn area: 0%
[16:48:43] [main/INFO]: Preparing spawn area: 0%
[16:48:43] [main/INFO]: Preparing spawn area: 0%
[16:48:45] [main/INFO]: Preparing spawn area: 83%
[16:48:45] [main/INFO]: Preparing spawn area: 83%
[16:48:45] [main/INFO]: Preparing spawn area: 83%
[16:48:45] [main/INFO]: Preparing spawn area: 83%
[16:48:46] [main/INFO]: Preparing spawn area: 99%
[16:48:46] [main/INFO]: Time elapsed: 3672 ms
[16:48:47] [Server thread/INFO]: EhrensEpicGaming[local:E:6b5176f1] logged in with entity id 218 at (-217.74921676604816, 63.0, 66.16337872563659)
[16:48:48] [Server thread/INFO]: EhrensEpicGaming joined the game
[16:48:48] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0
[16:48:48] [main/INFO]: [STDOUT]: Cached world directory: C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\cache
[16:48:48] [main/INFO]: [STDOUT]: Would save waypoints to C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\waypoints
[16:48:48] [Server thread/INFO]: Saving and pausing game...
[16:48:48] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:overworld
[16:48:48] [pool-5-thread-1/INFO]: [STDOUT]: Loading region -1,0 from disk C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\cache
[16:48:48] [main/INFO]: Loaded 67 advancements
[16:48:49] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 761ms
[16:48:50] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_nether
[16:48:50] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_end
[16:48:50] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2174ms or 43 ticks behind
[16:48:50] [pool-5-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\cache
[16:48:50] [pool-5-thread-1/INFO]: [STDOUT]: Loaded region successfully in 85ms
[16:49:18] [pool-5-thread-2/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\cache
[16:49:18] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\Ehren\AppData\Roaming\.minecraft\saves\Baritone\baritone\DIM0\cache
[16:49:18] [pool-5-thread-2/INFO]: [STDOUT]: Saved region successfully
[16:49:18] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[16:49:18] [pool-5-thread-2/INFO]: [STDOUT]: World save took 290ms
[16:49:18] [main/INFO]: [CHAT] [Baritone] > build House_1
[16:49:18] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:49:18] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3108/56423897.accept(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[16:49:18] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[16:49:18] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:49:18] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:49:18] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:49:18] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:49:18] [main/INFO]: [STDERR]: 	at cya$$Lambda$3052/809642601.run(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:49:18] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:49:18] [main/INFO]: [STDERR]: 	at cya$$Lambda$1509/1367317411.invoke(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:49:18] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:49:18] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[16:49:18] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:291)
[16:49:18] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1027)
[16:49:18] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:49:18] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:49:18] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:49:18] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:18] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:18] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:18] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:49:18] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:49:18] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:49:18] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:49:18] [main/INFO]: [STDERR]: 	... 31 more
[16:49:29] [main/INFO]: [CHAT] [Baritone] > build H
[16:49:29] [main/INFO]: [STDERR]: java.io.FileNotFoundException: C:\Users\Ehren\AppData\Roaming\.minecraft\schematics\H.schematic (The system cannot find the file specified)
[16:49:29] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[16:49:29] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[16:49:29] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3108/56423897.accept(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:49:29] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[16:49:29] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[16:49:29] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:49:29] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:49:29] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:49:29] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:49:29] [main/INFO]: [STDERR]: 	at cya$$Lambda$3052/809642601.run(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:49:29] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:49:29] [main/INFO]: [STDERR]: 	at cya$$Lambda$1509/1367317411.invoke(Unknown Source)
[16:49:29] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:49:29] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:49:29] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:49:29] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[16:49:29] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[16:49:29] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[16:49:29] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:49:29] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:49:29] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:49:29] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:29] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:29] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:29] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:49:29] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:49:29] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:49:29] [main/INFO]: [CHAT] [Baritone] Couldn't load the schematic
[16:49:31] [main/INFO]: [CHAT] [Baritone] > build
[16:49:31] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandNotEnoughArgumentsException: Not enough arguments (expected at least 1)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.af.requireMin(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.af.get(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.af.getString(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.api.command.datatypes.RelativeFile.apply(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.api.command.datatypes.RelativeFile.apply(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.af.getDatatypePost(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3108/56423897.accept(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:49:31] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[16:49:31] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[16:49:31] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:49:31] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:49:31] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:49:31] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:49:31] [main/INFO]: [STDERR]: 	at cya$$Lambda$3052/809642601.run(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:49:31] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:49:31] [main/INFO]: [STDERR]: 	at cya$$Lambda$1509/1367317411.invoke(Unknown Source)
[16:49:31] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:49:31] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:49:31] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[16:49:31] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:291)
[16:49:31] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1027)
[16:49:31] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:49:31] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:49:31] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:49:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:31] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:31] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:49:31] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:49:31] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:49:31] [main/INFO]: [CHAT] [Baritone] Error at argument #<unknown>: Expected RelativeFile
[16:49:35] [Server thread/INFO]: Saving and pausing game...
[16:49:35] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:overworld
[16:49:35] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_nether
[16:49:35] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_end
[16:49:50] [main/INFO]: [CHAT] [Baritone] > build House_1
[16:49:50] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:49:50] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3108/56423897.accept(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[16:49:50] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[16:49:50] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[16:49:50] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[16:49:50] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[16:49:50] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[16:49:50] [main/INFO]: [STDERR]: 	at cya$$Lambda$3052/809642601.run(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[16:49:50] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[16:49:50] [main/INFO]: [STDERR]: 	at cya$$Lambda$1509/1367317411.invoke(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:49:50] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:49:50] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:49:50] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[16:49:50] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[16:49:50] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[16:49:50] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[16:49:50] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[16:49:50] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[16:49:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:50] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:50] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:49:50] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:49:50] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:49:50] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[16:49:50] [main/INFO]: [STDERR]: 	... 32 more
[16:50:23] [Server thread/INFO]: Saving and pausing game...
[16:50:23] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:overworld
[16:50:24] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_nether
[16:50:24] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_end
[16:50:27] [Server thread/INFO]: EhrensEpicGaming lost connection: Disconnected
[16:50:27] [Server thread/INFO]: EhrensEpicGaming left the game
[16:50:27] [Server thread/INFO]: Stopping singleplayer server as player logged out
[16:50:27] [Server thread/INFO]: Stopping server
[16:50:27] [Server thread/INFO]: Saving players
[16:50:27] [Server thread/INFO]: Saving worlds
[16:50:27] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:overworld
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (Baritone): All chunks are saved
[16:50:27] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_nether
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:50:27] [Server thread/INFO]: Saving chunks for level 'Baritone'/minecraft:the_end
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (Baritone): All chunks are saved
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:50:27] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:50:29] [main/INFO]: Stopping!

**Comment by Ehrenf** [comment]
nvm
