### ISSUE TITLE
Wont follow player but gives an error instead

### ISSUE THREAD

**Issue by Jorgen10** [cabaletta/baritone#1184]
## Some information
Operating system: Windows 10
Java version: 1.8.0
Minecraft version: 1.14.4
Baritone version: 1.4.3
Forge mods (if used): No mods used

## [18:07:26] [main/INFO]: [CHAT] [Baritone] > follow player filtys00
[18:07:26] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[18:07:26] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:07:26] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3005/254087276.accept(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[18:07:26] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[18:07:26] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[18:07:26] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[18:07:26] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[18:07:26] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[18:07:26] [main/INFO]: [STDERR]: 	at cya$$Lambda$2994/1387022456.run(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[18:07:26] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[18:07:26] [main/INFO]: [STDERR]: 	at cya$$Lambda$1479/1795330205.invoke(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[18:07:26] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[18:07:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[18:07:26] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[18:07:26] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[18:07:26] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[18:07:26] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[18:07:26] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[18:07:26] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[18:07:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:07:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:07:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:07:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:07:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:07:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:07:26] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.av$$Lambda$3277/422342907.apply(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:07:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[18:07:26] [main/INFO]: [STDERR]: 	at baritone.av.execute(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: 	... 32 more).

## How to reproduce
Just type #follow player (player name which in my case was filtys00)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by QueueHuo** [comment]
It seems that I also encountered this problem. 

Minecraft version 1.15.2;
Java version: 1.8
Baritone version: 1.5.3

**Comment by ZacSharp** [comment]
Reproduced with
Minecraft version: 1.12.2
Java version: 1.8
Baritone version: 1.2.14
It only happened when I tried to follow a player that was either not online or out of render distance

**Comment by dominikaaaa** [comment]
>  It only happened when I tried to follow a player that was either not online or out of render distance

That's not a bug tho

**Comment by ZacSharp** [comment]
I guess it should not tell you to report the error here if it's not a bug

**Comment by ZacSharp** [comment]
Should I open a new issue for that?

**Comment by dominikaaaa** [comment]
Probably
