### ISSUE TITLE
baritone is crashing

### ISSUE THREAD

**Issue by John200410** [cabaletta/baritone#1185]
## Some information
Operating system: Windows 10 build 1803
Java version: Default Minecraft Java
Minecraft version: 1.12.2
Baritone version: 1.2.10
Forge mods (if used): Future, rusherhack, riga's highway builder, ReAuth, Schematica & required libs. (I tried without any mods and it still doesn't work)

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.ei
	at baritone.ei.a(Unknown Source)
	at baritone.ei.a(Unknown Source)
	at baritone.hc.a(Unknown Source)
	at baritone.hc$$Lambda$192/639061779.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.hc.a(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zcj000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1754)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Join a world and crash, singleplayer and multiplayer.

## Final checklist
- [X ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X ] I have included logs, exceptions and / or steps to reproduce the issue.
- [X ] I have not used any OwO's or UwU's in this issue.

**Comment by THEREALWWEFAN231** [comment]
Agreed, I get this crap too, many people have gotten java.lang.IllegalAccessError errors from baritone all which seem to be different.

**Comment by 0-x-2-2** [comment]
Are you using the standalone or api version?

**Comment by John200410** [comment]
> Are you using the standalone or api version?

standalone

**Comment by 0-x-2-2** [comment]
> > Are you using the standalone or api version?
> 
> standalone

Can you send a full crash report and logs on the latest forge 1.12.2 with the latest baritone standalone for 1.12.2 with zero mods?

**Comment by John200410** [comment]
> > > Are you using the standalone or api version?
> > 
> > 
> > standalone
> 
> I am unable to reproduce. Can you send a full crash report and logs on the latest forge 1.12.2 with the latest baritone standalone for 1.12.2 with zero mods?

[latest.log](https://github.com/cabaletta/baritone/files/3937141/latest.log)

**Comment by John200410** [comment]
bumping this

**Comment by ZeroMemes** [comment]
Try using the API release instead of Standalone and see if the issue persists. I think I might have an idea as to what is causing this.

**Comment by John200410** [comment]
> Try using the API release instead of Standalone and see if the issue persists. I think I might have an idea as to what is causing this.

Just downloaded the latest API release for forge and the issue still persists.

[21:07:02] [main/INFO] [FML]: Applying holder lookups
[21:07:02] [main/INFO] [FML]: Holder lookups applied
[21:07:03] [pool-5-thread-4/INFO] [STDOUT]: [baritone.u:b:-1]: Started saving saved containers in a new thread
[21:07:03] [pool-5-thread-3/INFO] [STDOUT]: [baritone.u:c:-1]: Started saving the world in a new thread
[21:07:03] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
	at baritone.j.a(Unknown Source) ~[j.class:1.2.11]
	at baritone.j.onTick(Unknown Source) ~[j.class:1.2.11]
	at baritone.ce.a(Unknown Source) ~[ce.class:1.2.11]
	at baritone.ce$$Lambda$198/1455227219.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_51]
	at baritone.ce.onTick(Unknown Source) ~[ce.class:1.2.11]
	at net.minecraft.client.Minecraft.handler$runTick$zck000(Minecraft.java) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1754) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by famous1622** [comment]
Still persists, adding a AT in another mod making the fields accessible causes a fail with:

```
java.lang.IncompatibleClassChangeError: Expected non-static field baritone.dj.field_177990_b
    at baritone.hn.b(Unknown Source)
    at baritone.el.a(Unknown Source)
    at baritone.el.a(Unknown Source)
    at baritone.hf.a(Unknown Source)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
    at baritone.hf.a(Unknown Source)

```

**Comment by 0-x-2-2** [comment]
> Expected non-static field baritone.dj.field_177990_b

something is deformed here...

**Comment by famous1622** [comment]
Get this.

It's having -noverify on.

IDEFK

**Comment by Tigermouthbear** [comment]
Im getting this error too

**Comment by Tigermouthbear** [comment]
Figured it out, it crashes when you have noverify on. Idk why I had it on

**Comment by dominikaaaa** [comment]
did you try reading one comment up

**Comment by cookiedragon234** [comment]
Yeah lol noverify is weird sometimes it causes the jvm to do *more* access checks

**Comment by John200410** [comment]
Can confirm that removing noverify that it runs properly

**Comment by dominikaaaa** [comment]
thank you babbaj for labelling this correctly. I was getting this issue for like 2 weeks in a non-dev env and I couldn't figure it out for the life of me. I'm so fucking stupid

**Comment by harshpatel0** [comment]
How do I disable noverify?

**Comment by JustOchz** [comment]
Hey, I never enabled noverify, but it's still crashing for me.

**Comment by scorbett123** [comment]
> Hey, I never enabled noverify, but it's still crashing for me.

This may be a different issue then, please look at your log and see whether the error looks similar to this one, and if not open a new issue with the log.

**Comment by RandomHuman22** [comment]
im having the same problem xd

**Comment by scorbett123** [comment]
> 

Follow the solution in the above issue and remove noverify then
