### ISSUE TITLE
Baritone Schematic #build error

### ISSUE THREAD

**Issue by Miky88** [cabaletta/baritone#1199]
## Some information
Operating system: Win 10
Java version: 8
Minecraft version: 1.14.4
Baritone version: latest 1.14.4
Forge mods (if used): None, using Vanilla w/Optifine&Baritone

## Exception, error or logs
[14:30:52] [main/INFO]: [CHAT] [Baritone] > build house
[14:30:52] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[14:30:52] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[14:30:52] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[14:30:52] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[14:30:52] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[14:30:52] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
...

## How to reproduce
Just do a schematic in 1.14.4, paste it in schematics folder and do "build <schematic file>"
## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue. // WHAT!?!?

**Comment by FTC55** [comment]
Schematics don't work in 1.13+
