### ISSUE TITLE
can't build 

### ISSUE THREAD

**Issue by jackferno** [cabaletta/baritone#1223]
[19:04:32] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:04:32] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$2967/2015333670.accept(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zzb000(SourceFile)
[19:04:32] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[19:04:32] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[19:04:32] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[19:04:32] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[19:04:32] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[19:04:32] [main/INFO]: [STDERR]: 	at cya.lambda$onKeyEvent$4(KeyboardListener.java:442)
[19:04:32] [main/INFO]: [STDERR]: 	at cya$$Lambda$1765/889863667.run(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[19:04:32] [main/INFO]: [STDERR]: 	at cya.a(KeyboardListener.java:409)
[19:04:32] [main/INFO]: [STDERR]: 	at cya$$Lambda$1466/955381449.invoke(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[19:04:32] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[19:04:32] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[19:04:32] [main/INFO]: [STDERR]: 	at cuo.k(MainWindow.java:503)
[19:04:32] [main/INFO]: [STDERR]: 	at cuo.c(MainWindow.java:342)
[19:04:32] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[19:04:32] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[19:04:32] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[19:04:32] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[19:04:32] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:04:32] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:04:32] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:04:32] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:04:32] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[19:04:32] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[19:04:32] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[19:04:32] [main/INFO]: [STDERR]: 	... 33 more

**Comment by Fnagger** [comment]
I've got the first one, while trying to build from a Schematic file
