### ISSUE TITLE
Baritone build command dosn't work

### ISSUE THREAD

**Issue by msogamer** [cabaletta/baritone#1241]
## Some information
Operating system:win10
Java versiondon't know
Minecraft version:1.14.4
Baritone version:1.2.10

## Exception, error or logs
[21:01:57] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[21:01:57] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[21:01:57] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[21:01:57] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[21:01:57] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[21:01:57] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[21:01:57] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[21:01:57] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[21:01:57] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[21:01:57] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[21:01:57] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[21:01:57] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[21:01:57] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[21:01:57] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[21:01:57] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[21:01:57] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[21:01:57] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:291)
[21:01:57] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1027)
[21:01:57] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[21:01:57] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[21:01:57] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:01:57] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:01:57] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[21:01:57] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)

## How to reproduce
going in to a world typing .b build [scematic name]
## Final checklist
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
build does not work 1.13+

**Comment by leijurv** [comment]
@0-x-2-2 except it does https://github.com/cabaletta/baritone/commit/adff391e459d27baa047dad1ad74fe47b0c0a029

**Comment by 0-x-2-2** [comment]
>master
