### ISSUE TITLE
Baritone crashes when using #sel set 'block' for all versions. (This does not hapen with impact Baritone)

### ISSUE THREAD

**Issue by crispylemons** [cabaletta/baritone#1242]
## Some information
Operating system: Windows 10
Java version: v8, 1.80_231-b11 with 64bit version installed to.
Minecraft version: 1.14.4
Baritone version: I used you download cilent using 1.4 and modified to use baratone with 1.4.4 (and updated org.ow2.asm:asm-all:5.2)
Forge mods (if used): N/A

## Exception, error or logs
///Log for standard 1.14.4 baritone launcher///
---- Minecraft Crash Report ----
// My bad.

Time: 13/01/20 5:44 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.h.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$1700/1651074976.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at cyc.handler$runTick$zzi000(SourceFile)
	at cyc.m(SourceFile:1401)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.h.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$1700/1651074976.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at cyc.handler$runTick$zzi000(SourceFile)

-- Affected level --
Details:
	All players: 1 total; [dmp['Nick_Strike'/14680, l='MpServer', x=2529.65, y=74.00, z=4123.41]]
	Chunk stats: Client Chunk Cache: 18225, 81
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (2508,74,4107), Chunk: (at 12,4,11 in 156,256; contains blocks 2496,0,4096 to 2511,255,4111), Region: (4,8; contains chunks 128,256 to 159,287, blocks 2048,0,4096 to 2559,255,4607)
	Level time: 38272513 game time, 30000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Travertine (git:Travertine-Bootstrap:1.15-SNAPSHOT:61be17f:115) <- Scylla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 672967896 bytes (641 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

///Custom 1.14.4 baritone launcher///
---- Minecraft Crash Report ----
// My bad.

Time: 13/01/20 5:36 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.dy.b(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.h.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$1700/268447802.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at cyc.handler$runTick$zzi000(SourceFile)
	at cyc.m(SourceFile:1401)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.dy.b(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.h.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$1700/268447802.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at cyc.handler$runTick$zzi000(SourceFile)

-- Affected level --
Details:
	All players: 1 total; [dmp['Nick_Strike'/7834, l='MpServer', x=2534.48, y=75.00, z=4122.32]]
	Chunk stats: Client Chunk Cache: 18225, 81
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (2508,74,4107), Chunk: (at 12,4,11 in 156,256; contains blocks 2496,0,4096 to 2511,255,4111), Region: (4,8; contains chunks 128,256 to 159,287, blocks 2048,0,4096 to 2559,255,4607)
	Level time: 38263174 game time, 30000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Travertine (git:Travertine-Bootstrap:1.15-SNAPSHOT:61be17f:115) <- Scylla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 545322128 bytes (520 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

## How to reproduce
Use #sel too tp select a 4*4 area
#sel 1
#sel 2
#sel set (anyblock)
When it runs out of blocks or jumps the game will crash.

## Final checklist
- [ Yes] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ Yes] I have included logs, exceptions and / or steps to reproduce the issue.
- [Yes ] I have not used any OwO's or UwU's in this issue.

## My Jason file for the custom updated launcher
{
  "id": "1.14.4-Baritone",
  "type": "release",
  "inheritsFrom": "1.14.4",
  "jar": "1.14.4",
  "time": "2019-07-23T20:50:21Z",
  "releaseTime": "2019-07-23T20:50:21Z",
  "downloads": {},
  "minimumLauncherVersion": 0,
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
     "--tweakClass",
     "baritone.launch.BaritoneTweaker"
    ]
  },
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12",
      "downloads": {
        "artifact": {
          "path": "net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar",
          "sha1": "111e7bea9c968cdb3d06ef4632bf7ff0824d0f36",
          "size": 32999,
          "url": "https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar"
        }
      }
    },
    {
      "name": "cabaletta:baritone-api:1.4.4",
      "downloads": {
        "artifact": {
          "path": "cabaletta/baritone-api/1.4.4/baritone-api-1.4.4.jar",
          "sha1": "d7a88e1ab25875c4936b3aa1708c9d8f4576b120",
          "size": 435911,
          "url": "https://github.com/cabaletta/baritone/releases/download/v1.4.4/baritone-api-1.4.4.jar"
        }
      }
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "downloads": {
        "artifact": {
          "path": "com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar",
          "sha1": "d1d3856e7d9ba0c43f6d6a1d488cdd35e5098127",
          "size": 9938,
          "url": "https://impactdevelopment.github.io/maven/com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar"
        }
      }
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "downloads": {
        "artifact": {
          "path": "org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar",
          "sha1": "7a670207bdb97db418118ad1e9bb42424ff3776d",
          "size": 1017668,
          "url": "https://impactdevelopment.github.io/maven/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar"
        }
      }
    },
    {
      "name": "org.ow2.asm:asm-all:5.2",
      "downloads": {
        "artifact": {
          "path": "org/ow2/asm/asm-all/5.2/asm-all-5.2.jar",
          "sha1": "2ea49e08b876bbd33e0a7ce75c8f371d29e1f10a",
          "size": 247787,
          "url": "http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar"
        }
      }
    }
  ]
}

**Comment by crispylemons** [comment]
The issue was with Minecraft missing files. This can be fixed by downloading the Minecraft launcher and clicking repair button. 👍
