### ISSUE TITLE
Weather2 Mod causes crash

### ISSUE THREAD

**Issue by madamunkey** [cabaletta/baritone#1251]
## Some information
Operating system: Windows 10
Java version: 1.8.0_51
Minecraft version: 1.12.2
Baritone version: 1.2.11

Forge mods (if used): 
Impact (Forge mod) 4.8.3
[1.12]bspkrsCore-universal-7.6.0.1.jar
ForgeEndertech-1.12.2-4.4.26.0-build.0431.jar
AdPother-1.12.2-1.0.29.0-build.0431.jar
jei_1.12.2-4.15.0.291.jar
Baubles-1.12-1.5.2.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
railcraft-12.0.0.jar
CTM-MC1.12.2-1.0.1.30.jar
Chisel-MC1.12.2-1.0.1.44.jar
Mantle-1.12-1.3.3.55.jar
TConstruct-1.12.2-2.12.0.157.jar
ImmersiveEngineering-0.12-92.jar
alternatingflux-0.12.2-2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
ancientwarfare-1.12.2-2.7.0.772.jar
AppleSkin-mc1.12-1.0.9.jar
iChunUtil-1.12.2-7.2.2.jar
BackTools-1.12.2-7.0.1.jar
bettercaves-1.12.2-1.6.0.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
Bloodmoon-MC1.12.2-1.5.3.jar
coroutil-1.12.1-1.2.32.jar
culinaryconstruct-1.3.3.1.jar
CustomNPCs_1.12.2-(01Oct19).jar
disenchanter-[1.12]1.6.jar
embers-0.230.jar
firstaid-1.6.12.jar
HardcoreDarkness-MC1.12.2-2.0.jar
Hwyla-1.8.21-B36_1.12.jar
jeivillagers-1.12-1.0.2.jar
journeymap-1.12.2-5.5.5.jar
Pam's+HarvestCraft+1.12.2zf.jar
just-enough-harvestcraft-1.12.2-1.6.6.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
nonetherPortals_v1.0.0formc1.12.2.jar
Placebo-1.12.2-1.6.0.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SpartanShields-1.12.2-1.5.4.jar
SpartanWeaponry-1.12.2-beta-1.3.8.jar
TinkersComplement-1.12.2-0.4.2.jar
tinkersjei-1.2.jar
Toast+Control-1.12.2-1.8.1.jar
ToughAsNails-1.12.2-3.1.0.139-universal.jar
TreeCapitator-Mod-1.12.2.jar
WaitingTime-1.0.1.jar
Wawla-1.12.2-2.5.273.jar
Waystones_1.12.2-4.0.72.jar
WearableBackpacks-1.12.2-3.1.4.jar
weather2-1.12.1-2.6.12.jar
zombieawareness-1.12.1-1.11.16.jar

## Exception, error or logs
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WTPlugin (WaitingTime-1.0.1.jar)
  LoadingPlugin (AdPother-1.12.2-1.0.29.0-build.0431.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.26.0-build.0431.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/15/20 11:59 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at weather2.block.BlockSandLayer.func_176205_b(BlockSandLayer.java:67)
	at baritone.ck.b(Unknown Source)
	at baritone.ck.a(Unknown Source)
	at baritone.ck.a(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.ce.a(Unknown Source)
	at baritone.ce$$Lambda$2537/1121356941.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.ce.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zej000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at weather2.block.BlockSandLayer.func_176205_b(BlockSandLayer.java:67)
	at baritone.ck.b(Unknown Source)
	at baritone.ck.a(Unknown Source)
	at baritone.ck.a(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.ce.a(Unknown Source)
	at baritone.ce$$Lambda$2537/1121356941.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.ce.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zej000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Madamunkey'/393315, l='MpServer', x=43.22, y=70.13, z=-3986.21], EntityOtherPlayerMP['FluffyRBTank'/175175, l='MpServer', x=26.81, y=72.00, z=-3983.91]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (180,67,263), Chunk: (at 4,4,7 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7675479 game time, 8670659 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityCartChest['Chest Cart'/171968, l='MpServer', x=3.50, y=15.06, z=-3951.50], EntityRabbit['Rabbit'/172033, l='MpServer', x=96.21, y=79.00, z=-3935.08], EntityHusk['Husk'/391430, l='MpServer', x=99.50, y=78.00, z=-3930.50], EntityZombie['Zombie'/391425, l='MpServer', x=103.55, y=72.25, z=-3969.25], EntityPlayerSP['Madamunkey'/393315, l='MpServer', x=43.22, y=70.13, z=-3986.21], EntityOtherPlayerMP['FluffyRBTank'/175175, l='MpServer', x=26.81, y=72.00, z=-3983.91], EntityLatchedRenderer['unknown'/70, l='MpServer', x=8.50, y=65.00, z=8.50], EntityCreeper['Creeper'/391427, l='MpServer', x=98.50, y=76.00, z=-3940.50], EntityItem['item.item.bone'/386188, l='MpServer', x=75.99, y=84.00, z=-3972.28], EntityAncientGolem['Ancient Golem'/171656, l='MpServer', x=72.30, y=44.20, z=-4026.30], EntityOtherPlayerMP['FluffyRBTank'/175175, l='MpServer', x=26.81, y=72.00, z=-3983.91], EntityLatchedRenderer['unknown'/76, l='MpServer', x=26.81, y=72.00, z=-3983.91], EntityItem['item.item.bone'/391572, l='MpServer', x=85.19, y=74.00, z=-3969.61], EntityCartChest['Chest Cart'/171862, l='MpServer', x=1.50, y=15.06, z=-3976.50], EntityCartChest['Chest Cart'/171863, l='MpServer', x=51.50, y=20.06, z=-3969.50], EntityItem['item.item.arrow'/391571, l='MpServer', x=84.13, y=75.00, z=-3969.13], EntityCartChest['Chest Cart'/171864, l='MpServer', x=68.50, y=19.06, z=-3972.50], EntitySkeleton['Skeleton'/392159, l='MpServer', x=114.99, y=72.00, z=-3986.55], EntitySpider['Spider'/392230, l='MpServer', x=120.56, y=72.00, z=-3976.75], EntitySkeleton['Skeleton'/391969, l='MpServer', x=113.50, y=40.00, z=-3914.50], EntityItem['item.item.bone'/392492, l='MpServer', x=90.88, y=70.00, z=-3972.75], EntityItem['item.tile.sand.default'/391080, l='MpServer', x=-7.72, y=69.13, z=-4049.50], EntityItem['item.item.arrow'/391019, l='MpServer', x=75.64, y=69.00, z=-4002.00], EntityItem['item.item.arrow'/392491, l='MpServer', x=89.35, y=69.13, z=-3973.88], EntitySkeleton['Skeleton'/391861, l='MpServer', x=112.70, y=69.38, z=-3907.51], EntityRabbit['Rabbit'/391863, l='MpServer', x=112.07, y=105.00, z=-4034.69], EntityCreeper['Creeper'/391859, l='MpServer', x=118.50, y=67.00, z=-3950.50], EntityCreeper['Creeper'/392828, l='MpServer', x=90.50, y=21.00, z=-3976.50], EntityBat['Bat'/391423, l='MpServer', x=100.69, y=21.10, z=-3977.83], EntityItem['item.item.leggingsCloth'/391800, l='MpServer', x=-4.43, y=68.00, z=-4006.18], EntityCreeper['Creeper'/392827, l='MpServer', x=85.50, y=21.00, z=-3976.50], EntityHusk['Husk'/391866, l='MpServer', x=120.21, y=106.00, z=-4024.63]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/70, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3245498800 bytes (3095 MB) / 5368709120 bytes (5120 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version            | Source                                        | Signature                                |
	|:------ |:------------------------ |:------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2             | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42               | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99          | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge                    | 14.23.5.2847       | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | bspkrscore               | 7.6.0.1            | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
	| LCHIJA | forgeendertech           | 1.12.2-4.4.26.0    | ForgeEndertech-1.12.2-4.4.26.0-build.0431.jar | None                                     |
	| LCHIJA | adpother                 | 1.12.2-1.0.29.0    | AdPother-1.12.2-1.0.29.0-build.0431.jar       | None                                     |
	| LCHIJA | jei                      | 4.15.0.291         | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCHIJA | baubles                  | 1.5.2              | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | thaumcraft               | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | railcraft                | 12.0.0             | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | ctm                      | MC1.12.2-1.0.1.30  | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
	| LCHIJA | chisel                   | MC1.12.2-1.0.1.44  | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55      | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct               | 1.12.2-2.12.0.157  | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
	| LCHIJA | immersiveengineering     | 0.12-92            | ImmersiveEngineering-0.12-92.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | alternatingflux          | 0.12.2-2           | alternatingflux-0.12.2-2.jar                  | None                                     |
	| LCHIJA | codechickenlib           | 3.2.3.358          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772   | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772   | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772   | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772   | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772   | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | appleskin                | 1.0.9              | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| LCHIJA | ichunutil                | 7.2.2              | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools                | 7.0.1              | BackTools-1.12.2-7.0.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | bettercaves              | 1.12.2             | bettercaves-1.12.2-1.6.0.jar                  | None                                     |
	| LCHIJA | bibliocraft              | 2.4.5              | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHIJA | biomesoplenty            | 7.0.1.2441         | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | bloodmoon                | 1.5.3              | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | extendedrenderer         | v1.0               | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | coroutil                 | 1.12.1-1.2.32      | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | configmod                | v1.0               | coroutil-1.12.1-1.2.32.jar                    | None                                     |
	| LCHIJA | culinaryconstruct        | 1.3.3.1            | culinaryconstruct-1.3.3.1.jar                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | customnpcs               | 1.12               | CustomNPCs_1.12.2-(01Oct19).jar               | None                                     |
	| LCHIJA | disenchanter             | 1.6                | disenchanter-[1.12]1.6.jar                    | None                                     |
	| LCHIJA | embers                   | 0.230              | embers-0.230.jar                              | None                                     |
	| LCHIJA | firstaid                 | 1.6.12             | firstaid-1.6.12.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | hardcoredarkness         | 2.0                | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | waila                    | 1.8.21             | Hwyla-1.8.21-B36_1.12.jar                     | None                                     |
	| LCHIJA | jeivillagers             | 1.0                | jeivillagers-1.12-1.0.2.jar                   | None                                     |
	| LCHIJA | journeymap               | 1.12.2-5.5.5       | journeymap-1.12.2-5.5.5.jar                   | None                                     |
	| LCHIJA | harvestcraft             | 1.12.2zb           | Pam's+HarvestCraft+1.12.2zf.jar               | None                                     |
	| LCHIJA | jehc                     | 1.6.6              | just-enough-harvestcraft-1.12.2-1.6.6.jar     | None                                     |
	| LCHIJA | jeresources              | 0.9.2.60           | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHIJA | nonetherportals          | 1.0.0              | nonetherPortals_v1.0.0formc1.12.2.jar         | None                                     |
	| LCHIJA | placebo                  | 1.6.0              | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | sereneseasons            | 1.2.18             | SereneSeasons-1.12.2-1.2.18-universal.jar     | None                                     |
	| LCHIJA | spartanshields           | 1.5.4              | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| LCHIJA | spartanweaponry          | beta 1.3.8         | SpartanWeaponry-1.12.2-beta-1.3.8.jar         | None                                     |
	| LCHIJA | tcomplement              | 1.12.2-0.4.2       | TinkersComplement-1.12.2-0.4.2.jar            | None                                     |
	| LCHIJA | tinkersjei               | 1.2                | tinkersjei-1.2.jar                            | None                                     |
	| LCHIJA | toastcontrol             | 1.8.1              | Toast+Control-1.12.2-1.8.1.jar                | None                                     |
	| LCHIJA | toughasnails             | 3.1.0.139          | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCHIJA | treecapitator            | 1.43.0             | TreeCapitator-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | waitingtime              | 1.0.1              | WaitingTime-1.0.1.jar                         | None                                     |
	| LCHIJA | wawla                    | 2.5.273            | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones                | 4.0.72             | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LCHIJA | wearablebackpacks        | 3.1.4              | WearableBackpacks-1.12.2-3.1.4.jar            | None                                     |
	| LCHIJA | weather2                 | 1.12.1-2.6.12      | weather2-1.12.1-2.6.12.jar                    | None                                     |
	| LCHIJA | zombieawareness          | 1.12.1-1.11.16     | zombieawareness-1.12.1-1.11.16.jar            | None                                     |
	| LCHIJA | rtg                      | 6.1.0.0-snapshot.1 | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |

	Loaded coremods (and transformers): 
WTPlugin (WaitingTime-1.0.1.jar)
  com.blamejared.waitingtime.core.WTClassTransformer
LoadingPlugin (AdPother-1.12.2-1.0.29.0-build.0431.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EngineersDecor$DecorFurnace
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Furnace
  com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$PortableGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$CombustionChamber
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberSolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberLiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Alloyer
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Crusher
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$AnimalFeeding
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.Natura$NetherrackFurnace
  com.endertech.minecraft.mods.adpother.transformers.Pyrotech$TileCombustion
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.transformers.UltimateCarMod$Car
  com.endertech.minecraft.mods.adpother.transformers.ViesCraft$AirShip
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CorePlugin (ForgeEndertech-1.12.2-4.4.26.0-build.0431.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.41' Renderer: 'GeForce GTX 1060 with Max-Q Design/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

## How to reproduce
Load into a Desert biome with Weather2 layered sand and trigger a tornado (tornado possibly not necessary but was happening during first crash)

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Should be fixed by #1087

**Comment by 0-x-2-2** [comment]
https://github.com/cabaletta/baritone/pull/1087/files#diff-f81be37399700d83810860d43db2cb2fR56 

This is pozzed and it is not actually returning the true block state of the block instead it is probably returning air or stone because it is a cached chunk or some other reason and the mod just assumes it must be a valid block state for its block and attempts to read a block state property from it that should always exist as long as that is really the mods block state.

**Comment by madamunkey** [comment]
> 
> 
> Should be fixed by #1087 🤔. Can you send the debug.log file from the logs folder, please?

Addons will be different (namely invtweaks, wurst, and advxray) but the same issue occured when i reinstalled the Impact forge plugin 
[debug.log](https://github.com/cabaletta/baritone/files/4080438/debug.log)
