### ISSUE TITLE
Crash While Loading Map

### ISSUE THREAD

**Issue by OswinL** [cabaletta/baritone#1254]
## Some information
Operating system: w10
Java version: 8
Minecraft version: 1.14.4
Baritone version: 1.14.4
Forge mods (if used):  

## Exception, error or logs
  
Time: 22.01.2020 14:46
Description: Unexpected error

java.lang.NoClassDefFoundError: dke
	at dkc.a(SourceFile:346)
	at ls.a(SourceFile:76)
	at ls.a(SourceFile:13)
	at ke.a(SourceFile:21)
	at ke$$Lambda$2810/363391564.run(Unknown Source)
	at agq.h(SourceFile:144)
	at agu.h(SourceFile:23)
	at agq.q(SourceFile:118)
	at agq.bh(SourceFile:103)
	at cyc.e(SourceFile:915)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dke
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinPlayerController] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 23 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ısHittingBlock:Z in dke for mixins.baritone.json:MixinPlayerController->@Accessor[FIELD_SETTER]::setIsHittingBlock(Z)V
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:338)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1017527024 bytes (970 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 630 GL version 4.6.0 - Build 26.20.100.6999, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

## How to reproduce
I can launch the game and but I can't load a world
I have the original game it is not cracked
I tried impact but it crashes on launch
## Final checklist
- [+ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [+ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [+ ] I have not used any OwO's or UwU's in this issue.

**Comment by 0-x-2-2** [comment]
Try reinstalling the game?

**Comment by S-B99** [comment]
Can't reproduce this.

**Comment by OswinL** [comment]
> Try reinstalling the game?

I already did doesn't work

**Comment by 0-x-2-2** [comment]
Send the entire log file.

**Comment by OswinL** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/4122178/latest.log)

**Comment by OswinL** [comment]
hello?? its been 9 days

**Comment by Aaron2550** [comment]
You said you're on 1.14.4, the logs say smth about 
```
Launch wrapper 1.12
```
Not a Dev, idk of this related but check if u really really reeeeally have the right baritone version. 

> hello?? its been 9 days

Afaik this is a free, hobby project,  chill out fam

**Comment by OswinL** [comment]
[https://www.dropbox.com/s/rkml3hjokd3qv0m/1.14.4-Baritone.zip?dl=1](url)
this is the download link I use
I have 1.14.4 version

**Comment by S-B99** [comment]
Download the official one

**Comment by OswinL** [comment]
I solved it by using wurst and adding baritone to it
