### ISSUE TITLE
.b build <schematic> gives an unexception error

### ISSUE THREAD

**Issue by gus42298** [cabaletta/baritone#1272]
## Some information
Operating system: Windows 10
Minecraft version: Impact 4.8 for 1.14.4
Baritone version: 1.4.3

## Exception, error or logs
[20:38:34] [main/INFO]: [CHAT] [Baritone] > build automated-doors
[20:38:34] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[20:38:34] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3581/807851213.accept(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:38:34] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.1B$$Lambda$2139/1225241735.0(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.0f$$Lambda$2154/1897989813.invoke(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[20:38:34] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[20:38:34] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1686/1553994406.accept(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:38:34] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[20:38:34] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[20:38:34] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[20:38:34] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[20:38:34] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[20:38:34] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[20:38:34] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[20:38:34] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[20:38:34] [main/INFO]: [STDERR]: 	at cya$$Lambda$3576/292334905.run(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[20:38:34] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[20:38:34] [main/INFO]: [STDERR]: 	at cya$$Lambda$1463/347864558.invoke(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[20:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[20:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[20:38:34] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[20:38:34] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[20:38:34] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[20:38:34] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[20:38:34] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[20:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:38:34] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:38:34] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[20:38:34] [main/INFO]: [STDERR]: 	... 49 more

## How to reproduce
.b build automated-doors

## Here are the location of the schematic file
![asdtgfyhgh](https://user-images.githubusercontent.com/47524902/73877270-a3c2dc80-4858-11ea-88d9-537f3eeac128.PNG)

## Here's the error message in-game
![sdsd](https://user-images.githubusercontent.com/47524902/73877314-bf2de780-4858-11ea-932e-c32ef2cfbbd9.PNG)

**Comment by StijnSimons** [comment]
#1285 #1241 #1223 #1204 #1190 #1199 [Full list here if you didn't know](https://github.com/cabaletta/baritone/issues?utf8=%E2%9C%93&q=numeric+ids)

Image if github actually made an option to search for existing issues 😳
