### ISSUE TITLE
#build not working

### ISSUE THREAD

**Issue by sVeXh** [cabaletta/baritone#1285]
[19:10:15] [main/INFO]: [CHAT] [Baritone] > build fetterironfarm.schematic
[19:10:15] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:10:15] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3792/1682623231.accept(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zef000(SourceFile)
[19:10:15] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[19:10:15] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[19:10:15] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[19:10:15] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[19:10:15] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[19:10:15] [main/INFO]: [STDERR]: 	at cya$$Lambda$3760/1195122259.run(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[19:10:15] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[19:10:15] [main/INFO]: [STDERR]: 	at cya$$Lambda$1532/426744693.invoke(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[19:10:15] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[19:10:15] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[19:10:15] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[19:10:15] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[19:10:15] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[19:10:15] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[19:10:15] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[19:10:15] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[19:10:15] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:10:15] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:10:15] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:10:15] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:10:15] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:10:15] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:10:15] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[19:10:15] [main/INFO]: [STDERR]: 	... 32 more

**Comment by BongEatBong** [comment]
> [19:10:15] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo

Are you using Impact 4.8.3? #build is currently only supported on 1.12.2 Impact due to outdated Baritone version, though Impact with updated Baritone is available to donators via nightlies.

**Comment by sVeXh** [comment]
i was using 1.14 at that time now im running impact + baritone on 1.12 with baritone 1.12.10 and the bot is ''overloaded'' and keeps pausing and not building. can it maybe be because there are too many air blocks in the schematic and it doesnt know how to build the schematic?
Anyway, heres the log.
[19:15:32] [main/INFO]: [CHAT] [Baritone] > build IronFarmnew
[19:15:32] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[19:15:32] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=612,y=4,z=156}
[19:15:32] [main/INFO]: [CHAT] [Baritone] Starting layer 0
[19:15:47] [main/INFO]: [CHAT] [Baritone] Starting layer 1
[19:15:52] [pool-5-thread-13/INFO]: [STDOUT]: 5375743 movements considered
[19:15:52] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13162
[19:15:52] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 257514
[19:15:52] [pool-5-thread-13/INFO]: [STDOUT]: 122114 nodes per second
[19:15:54] [pool-5-thread-13/INFO]: [STDOUT]: 5323648 movements considered
[19:15:54] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13088
[19:15:54] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 255072
[19:15:54] [pool-5-thread-13/INFO]: [STDOUT]: 120992 nodes per second
[19:15:56] [pool-5-thread-13/INFO]: [STDOUT]: 5589710 movements considered
[19:15:56] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13421
[19:15:56] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 267501
[19:15:56] [pool-5-thread-13/INFO]: [STDOUT]: 127040 nodes per second
[19:16:04] [pool-5-thread-13/INFO]: [STDOUT]: 5754830 movements considered
[19:16:04] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13585
[19:16:04] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 275174
[19:16:04] [pool-5-thread-13/INFO]: [STDOUT]: 132383 nodes per second
[19:16:06] [pool-5-thread-13/INFO]: [STDOUT]: 5454589 movements considered
[19:16:06] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13246
[19:16:06] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 261182
[19:16:06] [pool-5-thread-13/INFO]: [STDOUT]: 123906 nodes per second
[19:16:09] [pool-5-thread-13/INFO]: [STDOUT]: 5592551 movements considered
[19:16:09] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13413
[19:16:09] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 267621
[19:16:09] [pool-5-thread-13/INFO]: [STDOUT]: 127104 nodes per second
[19:16:11] [pool-5-thread-13/INFO]: [STDOUT]: 5296896 movements considered
[19:16:11] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13049
[19:16:11] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 253817
[19:16:11] [pool-5-thread-13/INFO]: [STDOUT]: 120384 nodes per second
[19:16:13] [pool-5-thread-13/INFO]: [STDOUT]: 5396864 movements considered
[19:16:13] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13174
[19:16:13] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 258486
[19:16:13] [pool-5-thread-13/INFO]: [STDOUT]: 122594 nodes per second
[19:16:15] [pool-5-thread-13/INFO]: [STDOUT]: 5548912 movements considered
[19:16:15] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13368
[19:16:15] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 265592
[19:16:15] [pool-5-thread-13/INFO]: [STDOUT]: 126112 nodes per second
[19:16:17] [pool-5-thread-13/INFO]: [STDOUT]: 5550319 movements considered
[19:16:17] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13371
[19:16:17] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 265659
[19:16:17] [pool-5-thread-13/INFO]: [STDOUT]: 126144 nodes per second
[19:16:19] [pool-5-thread-13/INFO]: [STDOUT]: 5463035 movements considered
[19:16:19] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13259
[19:16:19] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 261579
[19:16:19] [pool-5-thread-13/INFO]: [STDOUT]: 124160 nodes per second
[19:16:21] [pool-5-thread-13/INFO]: [STDOUT]: 5570029 movements considered
[19:16:21] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13402
[19:16:21] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 266586
[19:16:21] [pool-5-thread-13/INFO]: [STDOUT]: 126592 nodes per second
[19:16:23] [pool-5-thread-13/INFO]: [STDOUT]: 5636190 movements considered
[19:16:23] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13480
[19:16:23] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 269672
[19:16:23] [pool-5-thread-13/INFO]: [STDOUT]: 128096 nodes per second
[19:16:25] [pool-5-thread-13/INFO]: [STDOUT]: 5554543 movements considered
[19:16:25] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13381
[19:16:25] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 265861
[19:16:25] [pool-5-thread-13/INFO]: [STDOUT]: 126240 nodes per second
[19:16:28] [pool-5-thread-13/INFO]: [STDOUT]: 5198336 movements considered
[19:16:28] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 12932
[19:16:28] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 249220
[19:16:28] [pool-5-thread-13/INFO]: [STDOUT]: 118144 nodes per second
[19:16:30] [pool-5-thread-13/INFO]: [STDOUT]: 5302528 movements considered
[19:16:30] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13062
[19:16:30] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 254086
[19:16:30] [pool-5-thread-13/INFO]: [STDOUT]: 120512 nodes per second
[19:16:32] [pool-5-thread-13/INFO]: [STDOUT]: 4904064 movements considered
[19:16:32] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 12543
[19:16:32] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 235455
[19:16:32] [pool-5-thread-13/INFO]: [STDOUT]: 111456 nodes per second
[19:16:34] [pool-5-thread-13/INFO]: [STDOUT]: 5492598 movements considered
[19:16:34] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13298
[19:16:34] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 262962
[19:16:34] [pool-5-thread-13/INFO]: [STDOUT]: 124832 nodes per second
[19:16:36] [pool-5-thread-13/INFO]: [STDOUT]: 5096960 movements considered
[19:16:36] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 12798
[19:16:36] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 244478
[19:16:36] [pool-5-thread-13/INFO]: [STDOUT]: 115840 nodes per second
[19:16:38] [pool-5-thread-13/INFO]: [STDOUT]: 5344768 movements considered
[19:16:38] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13116
[19:16:38] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 256060
[19:16:38] [pool-5-thread-13/INFO]: [STDOUT]: 121472 nodes per second
[19:16:40] [pool-5-thread-13/INFO]: [STDOUT]: 5265920 movements considered
[19:16:40] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13019
[19:16:40] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 252379
[19:16:40] [pool-5-thread-13/INFO]: [STDOUT]: 119680 nodes per second
[19:16:42] [pool-5-thread-13/INFO]: [STDOUT]: 5164544 movements considered
[19:16:42] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 12887
[19:16:42] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 247639
[19:16:42] [pool-5-thread-13/INFO]: [STDOUT]: 117376 nodes per second
[19:16:44] [pool-5-thread-13/INFO]: [STDOUT]: 4584448 movements considered
[19:16:44] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 12118
[19:16:44] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 220502
[19:16:44] [pool-5-thread-13/INFO]: [STDOUT]: 104192 nodes per second
[19:16:46] [pool-5-thread-13/INFO]: [STDOUT]: 5432060 movements considered
[19:16:46] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13228
[19:16:46] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 260140
[19:16:46] [pool-5-thread-13/INFO]: [STDOUT]: 123456 nodes per second
[19:16:48] [pool-5-thread-13/INFO]: [STDOUT]: 5512307 movements considered
[19:16:48] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13326
[19:16:48] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 263886
[19:16:48] [pool-5-thread-13/INFO]: [STDOUT]: 125280 nodes per second
[19:16:50] [pool-5-thread-13/INFO]: [STDOUT]: 5502452 movements considered
[19:16:50] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13319
[19:16:50] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 263431
[19:16:50] [pool-5-thread-13/INFO]: [STDOUT]: 125056 nodes per second
[19:16:52] [pool-5-thread-13/INFO]: [STDOUT]: 5378560 movements considered
[19:16:52] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13157
[19:16:52] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 257637
[19:16:52] [pool-5-thread-13/INFO]: [STDOUT]: 122240 nodes per second
[19:16:54] [pool-5-thread-13/INFO]: [STDOUT]: 5739752 movements considered
[19:16:54] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13577
[19:16:54] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 274481
[19:16:54] [pool-5-thread-13/INFO]: [STDOUT]: 132036 nodes per second
[19:16:56] [pool-5-thread-13/INFO]: [STDOUT]: 5299712 movements considered
[19:16:56] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13057
[19:16:56] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 253953
[19:16:56] [pool-5-thread-13/INFO]: [STDOUT]: 120448 nodes per second
[19:16:58] [pool-5-thread-13/INFO]: [STDOUT]: 5327872 movements considered
[19:16:58] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13094
[19:16:58] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 255270
[19:16:58] [pool-5-thread-13/INFO]: [STDOUT]: 121088 nodes per second
[19:17:01] [pool-5-thread-13/INFO]: [STDOUT]: 5561579 movements considered
[19:17:01] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13393
[19:17:01] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 266193
[19:17:01] [pool-5-thread-13/INFO]: [STDOUT]: 126400 nodes per second
[19:17:03] [pool-5-thread-13/INFO]: [STDOUT]: 5344768 movements considered
[19:17:03] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13116
[19:17:03] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 256060
[19:17:03] [pool-5-thread-13/INFO]: [STDOUT]: 121472 nodes per second
[19:17:05] [pool-5-thread-13/INFO]: [STDOUT]: 5650237 movements considered
[19:17:05] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13490
[19:17:05] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 270322
[19:17:05] [pool-5-thread-13/INFO]: [STDOUT]: 128416 nodes per second
[19:17:07] [pool-5-thread-13/INFO]: [STDOUT]: 5739752 movements considered
[19:17:07] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13577
[19:17:07] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 274481
[19:17:07] [pool-5-thread-13/INFO]: [STDOUT]: 134348 nodes per second
[19:17:09] [pool-5-thread-13/INFO]: [STDOUT]: 5555948 movements considered
[19:17:09] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13382
[19:17:09] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 265926
[19:17:09] [pool-5-thread-13/INFO]: [STDOUT]: 126272 nodes per second
[19:17:11] [pool-5-thread-13/INFO]: [STDOUT]: 5588325 movements considered
[19:17:11] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13415
[19:17:11] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 267431
[19:17:11] [pool-5-thread-13/INFO]: [STDOUT]: 127008 nodes per second
[19:17:13] [pool-5-thread-13/INFO]: [STDOUT]: 5515123 movements considered
[19:17:13] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13331
[19:17:13] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 264019
[19:17:13] [pool-5-thread-13/INFO]: [STDOUT]: 125344 nodes per second
[19:17:15] [pool-5-thread-13/INFO]: [STDOUT]: 5477112 movements considered
[19:17:15] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13279
[19:17:15] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 262239
[19:17:15] [pool-5-thread-13/INFO]: [STDOUT]: 124480 nodes per second
[19:17:17] [pool-5-thread-13/INFO]: [STDOUT]: 5340544 movements considered
[19:17:17] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13112
[19:17:17] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 255864
[19:17:17] [pool-5-thread-13/INFO]: [STDOUT]: 121376 nodes per second
[19:17:19] [pool-5-thread-13/INFO]: [STDOUT]: 5394048 movements considered
[19:17:19] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13175
[19:17:19] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 258359
[19:17:19] [pool-5-thread-13/INFO]: [STDOUT]: 122592 nodes per second
[19:17:21] [pool-5-thread-13/INFO]: [STDOUT]: 5675567 movements considered
[19:17:21] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13516
[19:17:21] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 271500
[19:17:21] [pool-5-thread-13/INFO]: [STDOUT]: 128992 nodes per second
[19:17:23] [pool-5-thread-13/INFO]: [STDOUT]: 5598178 movements considered
[19:17:23] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13430
[19:17:23] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 267894
[19:17:23] [pool-5-thread-13/INFO]: [STDOUT]: 127232 nodes per second
[19:18:57] [pool-5-thread-13/INFO]: [STDOUT]: 5272960 movements considered
[19:18:57] [pool-5-thread-13/INFO]: [STDOUT]: Open set size: 13033
[19:18:57] [pool-5-thread-13/INFO]: [STDOUT]: PathNode map size: 252713
[19:18:57] [pool-5-thread-13/INFO]: [STDOUT]: 119840 nodes per second
[19:19:55] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:20:00] [main/INFO]: [CHAT] [Baritone] > resume
[19:20:00] [main/INFO]: [CHAT] [Baritone] Not paused
[19:20:00] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:20:04] [main/INFO]: [CHAT] [Baritone] > pause
[19:20:04] [main/INFO]: [CHAT] [Baritone] Paused
[19:20:05] [main/INFO]: [CHAT] [Baritone] > resume
[19:20:05] [main/INFO]: [CHAT] [Baritone] Resumed
[19:20:05] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:20:09] [main/INFO]: [CHAT] [Baritone] > build IronFarmnew
[19:20:09] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[19:20:09] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=677,y=5,z=180}
[19:20:09] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:20:19] [main/INFO]: [CHAT] [Baritone] > cancel
[19:20:19] [main/INFO]: [CHAT] [Baritone] ok canceled
[19:20:20] [main/INFO]: [CHAT] [Baritone] > build IronFarmnew
[19:20:20] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[19:20:20] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=684,y=4,z=185}
[19:20:20] [main/INFO]: [CHAT] [Baritone] Starting layer 0
[19:20:35] [main/INFO]: [CHAT] [Baritone] Starting layer 1
[19:21:03] [pool-5-thread-2/INFO]: [STDOUT]: World save took 3ms
[19:21:08] [pool-5-thread-4/INFO]: [STDOUT]: World save took 0ms
[19:21:22] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:21:28] [main/INFO]: [CHAT] [Baritone] > resume
[19:21:28] [main/INFO]: [CHAT] [Baritone] Not paused
[19:21:28] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:21:38] [main/INFO]: [CHAT] [Baritone] > resume
[19:21:38] [main/INFO]: [CHAT] [Baritone] Not paused
[19:21:39] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:21:42] [main/INFO]: [CHAT] [Baritone] > resume
[19:21:42] [main/INFO]: [CHAT] [Baritone] Not paused
[19:21:42] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:21:47] [main/INFO]: [CHAT] [Baritone] > resume
[19:21:47] [main/INFO]: [CHAT] [Baritone] Not paused
[19:21:47] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:21:56] [main/INFO]: [CHAT] [Baritone] > resume
[19:21:56] [main/INFO]: [CHAT] [Baritone] Not paused
[19:21:56] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:22:00] [main/INFO]: [CHAT] [Baritone] > resume
[19:22:00] [main/INFO]: [CHAT] [Baritone] Not paused
[19:22:01] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:22:10] [main/INFO]: [CHAT] [Baritone] > resume
[19:22:10] [main/INFO]: [CHAT] [Baritone] Not paused
[19:22:11] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:22:15] [main/INFO]: [CHAT] [Baritone] > resume
[19:22:15] [main/INFO]: [CHAT] [Baritone] Not paused
[19:22:15] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:22:22] [main/INFO]: [CHAT] [Baritone] > resume
[19:22:22] [main/INFO]: [CHAT] [Baritone] Not paused
[19:22:23] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[19:22:37] [main/INFO]: [CHAT] [Baritone] > pause
[19:22:37] [main/INFO]: [CHAT] [Baritone] Paused
[19:22:38] [main/INFO]: [CHAT] [Baritone] > resume
[19:22:38] [main/INFO]: [CHAT] [Baritone] Resumed
[19:22:38] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
