### ISSUE TITLE
cant #build own schematics

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#1300]
## Some information
Operating system:win 10 home
Java version:(Build 1.8.0_131-b11)
Minecraft version:1.12.2
Baritone version:1.12.10
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[18:17:35] [main/INFO]: [CHAT] [Baritone] > build ironfarmneqw
[18:17:35] [main/INFO]: [STDERR]: java.io.FileNotFoundException: C:\Users\LucaF\AppData\Roaming\.minecraft\schematics\ironfarmneqw.schematic (Das System kann die angegebene Datei nicht finden)
[18:17:35] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[18:17:35] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[18:17:35] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.dz.build(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.am.execute(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.ce$$Lambda$672/1857935745.accept(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[18:17:35] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[18:17:35] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zeg000(SourceFile)
[18:17:35] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[18:17:35] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[18:17:35] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[18:17:35] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[18:17:35] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[18:17:35] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[18:17:35] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[18:17:35] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[18:17:35] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[18:17:35] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:17:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:17:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:17:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:17:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:17:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:17:35] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:17:35] [main/INFO]: [CHAT] [Baritone] Couldn't load the schematic
[18:17:37] [main/INFO]: [CHAT] [Baritone] > build ironfarmnew
[18:17:37] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[18:17:37] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=127,y=4,z=1071}
[18:17:37] [main/INFO]: [CHAT] [Baritone] Starting layer 0
[18:17:53] [main/INFO]: [CHAT] [Baritone] Starting layer 1
[18:17:58] [pool-5-thread-2/INFO]: [STDOUT]: World save took 1ms
[18:18:07] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel
[18:18:11] [main/INFO]: [CHAT] [Baritone] > build ironfarmnew
[18:18:11] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[18:18:11] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=194,y=6,z=1094}
[18:18:11] [main/INFO]: [CHAT] [Baritone] Unable to do it. Pausing. resume to resume, cancel to cancel

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Download this schematic: http://www.mediafire.com/file/vklhb8fu5vvnyx0/IronFarmnew.schematic/file
enter singleplayer creative world
#build ironfarmnew

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by StijnSimons** [comment]
`[18:17:35] [main/INFO]: [STDERR]: java.io.FileNotFoundException: C:\Users\LucaF\AppData\Roaming.minecraft\schematics\ironfarmneqw.schematic (Das System kann die angegebene Datei nicht finden)`

**Comment by StijnSimons** [comment]
Maybe spell "new" right first

**Comment by sVeXh** [comment]
[18:17:37] [main/INFO]: [CHAT] [Baritone] > build ironfarmnew

**Comment by sVeXh** [comment]
Maybe read first

**Comment by StijnSimons** [comment]
Maybe put only the erroring part in the github 🤔

**Comment by sVeXh** [comment]
there is nothing more than that

**Comment by sVeXh** [comment]
that all i get

**Comment by S-B99** [comment]
> [ONLY FOR 1.12.2 VERSION] Place the schematic file into .minecraft/schematics then type #build name. Make sure the required blocks are in your hotbar!

Try this and please also try adding the file extension to the path. Eg `#build impact.schematic`. Also make sure you're typing the name correctly, check the file name.

**Comment by sVeXh** [comment]
Ok im gonna try that on the Weekend please dont close this yet im not home before weekend

**Comment by ZacSharp** [comment]
I'd say five years later and after they deleted their account it's safe to assume they won't come back.
