### ISSUE TITLE
Can't build my schematic in 1.14.4 

### ISSUE THREAD

**Issue by HannaCriesPurple** [cabaletta/baritone#1308]
## Some information
Operating system: WIndow 10
Java version: latest
Minecraft version: 1.14.4
Baritone version: latest with impacte
Forge mods (if used): NO

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[13:15:36] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$2668/1645283156.accept(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zef000(SourceFile)
[13:15:36] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[13:15:36] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[13:15:36] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[13:15:36] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[13:15:36] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[13:15:36] [main/INFO]: [STDERR]: 	at cya$$Lambda$2581/1049659915.run(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[13:15:36] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[13:15:36] [main/INFO]: [STDERR]: 	at cya$$Lambda$1491/1942100755.invoke(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[13:15:36] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:15:36] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[13:15:36] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[13:15:36] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[13:15:36] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[13:15:36] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[13:15:36] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[13:15:36] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[13:15:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:15:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:15:36] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:15:36] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[13:15:36] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:15:36] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:15:36] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[13:15:36] [main/INFO]: [STDERR]: 	... 32 more

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
 Why i get this error ? In 1.14.4 whe can't use the schematics printer ? 
Thx for help . 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Your schematic file needs to be 1.12.2, this does not support 1.13 schematics

**Comment by HannaCriesPurple** [comment]
I Have create the schematics file in 1.12 version !

**Comment by S-B99** [comment]
Yes.

**Comment by HannaCriesPurple** [comment]
> Yes.

It's not a question ...
I have create the schematics on my 1.12.2 spigot server
Put the schematics fille in my schematics folder
Start impact client in 1.14.4 

And i get this error .

**Comment by S-B99** [comment]
No you don't, because the attached log is for 1.13 schematics

**Comment by S-B99** [comment]
Wait, I might be wrong. It is something else

**Comment by HannaCriesPurple** [comment]
ok i will retry, thanks you very much for your quick reply .

**Comment by HannaCriesPurple** [comment]
> Wait, I might be wrong. It is something else


oo i don't see your message ok i wait other help

**Comment by ZeroMemes** [comment]
The latest 1.12.2+ versions have support for schematic files in both the MCEdit and Sponge formats.
