### ISSUE TITLE
Tried to build  a schematic.

### ISSUE THREAD

**Issue by HeinzRudi** [cabaletta/baritone#1312]
## Some information
Operating system:win 10
Java version:Build 1.8.0_241-b07
Minecraft version:1.14.4
Baritone version:v1.4.3
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[20:08:44] [main/INFO]: [CHAT] [Baritone] > build abc
[20:08:44] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[20:08:44] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3729/1745258294.accept(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:08:44] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.1B$$Lambda$2282/136916074.0(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.0f$$Lambda$2297/60456959.invoke(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[20:08:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[20:08:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1744/1122090977.accept(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:08:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[20:08:44] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[20:08:44] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[20:08:44] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[20:08:44] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[20:08:44] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[20:08:44] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[20:08:44] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[20:08:44] [main/INFO]: [STDERR]: 	at cya$$Lambda$3726/1831829645.run(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[20:08:44] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[20:08:44] [main/INFO]: [STDERR]: 	at cya$$Lambda$1520/559210048.invoke(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[20:08:44] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[20:08:44] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[20:08:44] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[20:08:44] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[20:08:44] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[20:08:44] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[20:08:44] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[20:08:44] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:08:44] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:08:44] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:08:44] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:08:44] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:08:44] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[20:08:44] [main/INFO]: [STDERR]: 	... 49 more
[20:08:48] [Server thread/INFO]: Saving and pausing game...
[20:08:48] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_end
[20:08:48] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_nether
[20:08:48] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:overworld

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
it happens with all schematics
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
Please add .schematic to the end of the command
