### ISSUE TITLE
Schematic not working

### ISSUE THREAD

**Issue by Gamerpedia15** [cabaletta/baritone#1325]
## Some information
Operating system: Windows 10
Java version: No idea, java is deciding to be weird and not open. I last updated it sometime in the last 6 months I think.
Minecraft version: 1.12.2 Impact
Baritone version: It's 4.8.3 1.12.2 Impact. I don't know what Baritone version it would be.
Forge mods (if used): None

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[debug.log](https://github.com/cabaletta/baritone/files/4242146/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/4242148/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Save an area of land in Worldedit as a schematic then try to load it using baritone.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used). (Sorta)
- [x ] I have included logs, exceptions and/or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment]
![2020-02-23-135354_676x190_scrot](https://user-images.githubusercontent.com/17222512/75117946-f9aec700-5643-11ea-8a99-ed11f5ce34e0.png)
mfw

**Comment by S-B99** [comment]
Uh, that log is 1.15.2.

How are you using 1.12.2 impact if your log is 1.15.2

**Comment by ZeroMemes** [comment]
```
(debug.log)
...
Caused by: java.lang.OutOfMemoryError: Java heap space
```
This would indicate that you would need to allocate more RAM to your game. The other log that you provided was from another game entirely. Please locate the proper log file that is generated when you experience your issue and attach it in a reply.

**Comment by 0-x-2-2** [comment]
> This would indicate that you would need to allocate more RAM to your game. The other log that you provided was from another game entirely. Please locate the proper log file that is generated when you experience your issue and attach it in a reply.

It also looks like the wrong log because there are no mentions of Baritone being loaded at all.

**Comment by S-B99** [comment]
@0-x-2-2 https://github.com/cabaletta/baritone/issues/1325#issuecomment-590103509

**Comment by Gamerpedia15** [comment]
I'm sorry about that. I didn't realize I had the wrong logs. I attached my
debug and latest logs because that's what it said but I guess I should've
gotten different logs. I think I found it though. I promise I'm not that
retarded.

**Comment by S-B99** [comment]
Latest literally means latest log. If you launched the game after it will be latest as well. Please provide the proper logs.

**Comment by Gamerpedia15** [comment]
I realized what happened. I had launched the 1.15.2 fabric loader after the
1.12.2 Impact. I launched the 1.14.4 Impact and I'm 99% sure that the logs
I attached with my message from 3 hours ago were the same logs that I
needed. But I caused the same error and I'll attach the logs. It was
slightly different this time because it was a downloaded schematic but I'm
pretty sure it was copied via w/e.

**Comment by S-B99** [comment]
Instead of stating exactly what I said here, https://github.com/cabaletta/baritone/issues/1325#issuecomment-590103509, could you actually attach the logs please?

**Comment by Gamerpedia15** [comment]
I did.

**Comment by Gamerpedia15** [comment]
If you go three messages above this one (AKA my message where I stated
exactly what you said) I attached the logs.

**Comment by S-B99** [comment]
![](https://cdn.discordapp.com/attachments/308653317834145802/681324833362935818/Screenshot_20200223-212115.png)
no, you did not.

**Comment by Gamerpedia15** [comment]
[image: Proof.png]
It says I attached it. I can redo it I guess. Give me a few minutes.

**Comment by S-B99** [comment]
your image didn't attach either

you need to wait for it to finish uploading before submitting the comment.

**Comment by Gamerpedia15** [comment]
Attached

**Comment by Gamerpedia15** [comment]
Again:

**Comment by S-B99** [comment]
Please wait for the attachment to finish uploading before submitting. 
![](https://cdn.discordapp.com/attachments/308653317834145802/681332429495074961/Screenshot_20200223-215133.png)

**Comment by Gamerpedia15** [comment]
Sorry for being ignorant

>

**Comment by Gamerpedia15** [comment]
It gets shown as completed but one more time:

**Comment by S-B99** [comment]
please check your are connected to the internet

**Comment by S-B99** [comment]
oh your'e using fucking email lol

that won't work

**Comment by Gamerpedia15** [comment]
I uploaded it to mediafire:
http://www.mediafire.com/file/ed39zibu8fynoe1/latest.log/file

>

**Comment by Gamerpedia15** [comment]
There was one error before I did it because I had the extension as .schem
not .schematic. There's also probably one after it which was me trying to
put in a note block song.

>

**Comment by S-B99** [comment]
could you please upload the actual log that happens when you run the command with the proper naming, such as `penis.schematic`, not `penis`

**Comment by S-B99** [comment]
`C:\Users\Bradley\AppData\Roaming\.minecraft\schematics\test.schematic (The system cannot find the file specified)`

Please make sure you actually have a schematic

**Comment by Gamerpedia15** [comment]
Like I said that was the first time I did it. It was titled "test.schem" so
I changed it to "test.schematic".

**Comment by Gamerpedia15** [comment]
I will do your first comment though.

**Comment by S-B99** [comment]
The file doesn't exist.

**Comment by Gamerpedia15** [comment]
So I did it twice. First I did  test.schem then I did the edited version
with test.schematic and the updated logs are:
https://www.mediafire.com/file/y5aloiswr2y4xdl/latest.log/file

**Comment by Gamerpedia15** [comment]
That's weird because
https://www.mediafire.com/view/aotei3zprihp251/image.png/file

>

**Comment by Gamerpedia15** [comment]
You may be looking at my first attempt using the .schem instead of the one
that ends with .schematic

**Comment by 0-x-2-2** [comment]
```
[21:08:36] [main/INFO]: [CHAT] [Baritone] > build test.schematic
[21:08:36] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[21:08:36] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.IllegalStateException: bad schematic 
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.ce$$Lambda$699/1880044907.accept(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.0U.0(0U.java:17)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.0U.0(0U.java:3)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:08:36] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.0R.0(0R.java:49)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.5_$$Lambda$557/90486891.0(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.0xt.0(0xt.java:31)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.2E.0(2E.java:37)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.2E$$Lambda$571/2002865788.invoke(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[21:08:36] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[21:08:36] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$108/1125906288.accept(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[21:08:36] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[21:08:36] [main/INFO]: [STDERR]: 	at net.impactclient.0e.post(0e.java:6)
[21:08:36] [main/INFO]: [STDERR]: 	at bud.redirect$sendChatPacket$zzd000(SourceFile:1170)
[21:08:36] [main/INFO]: [STDERR]: 	at bud.g(SourceFile:293)
[21:08:36] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[21:08:36] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[21:08:36] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[21:08:36] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[21:08:36] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[21:08:36] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[21:08:36] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[21:08:36] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[21:08:36] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:08:36] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:08:36] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:08:36] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:08:36] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:08:36] [main/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: bad schematic 
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.go.<init>(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.dz.build(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	at baritone.am.execute(Unknown Source)
[21:08:36] [main/INFO]: [STDERR]: 	... 41 more
```

**Comment by Gamerpedia15** [comment]
I'm gonna assume that the issue is when w/e saves it they don't provide
enough information/they provide bad information which causes baritone to
not work.

>

**Comment by TomaszOleszko** [comment]
If you're having trouble loading a WorldEdit schematic in Baritone, save the schematic using the following command:

`//schem save filename sponge.2`
This ensures the schematic is saved in a format that Baritone can load correctly.
