### ISSUE TITLE
follow exception 1.12.2

### ISSUE THREAD

**Issue by dankmolot** [cabaletta/baritone#1376]
Error when i trying follow entity

### Error log
`[20:45:00] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > follow entity enderman
[20:45:00] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_191308_b
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cc.execute(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.a(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce$$Lambda$881/1452293471.accept(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zeg000(EntityPlayerSP.java)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:45:00] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchFieldError: field_191308_b
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.ag.getDatatypeFor(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.aw.execute(Unknown Source)
[20:45:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 24 more`

**Comment by S-B99** [comment]
That means there are no enderman in loaded chunks.

**Comment by TheK0tYaRa** [comment]
Replicated the error with enderman behind the wall

**Comment by CDAGaming** [comment]
Yea looking at the log, this seems like an actual error (Maybe the wrong file being loaded since its a mapping issue)

**Comment by dankmolot** [comment]
This bug appears only on the forge version of the game

**Comment by krzys-h** [comment]
Can confirm: `follow entity sheep` with the sheep right next to me caused this error. I am running with forge too.

**Comment by CDAGaming** [comment]
Ill try to reproduce this today possibly...

**Comment by krzys-h** [comment]
The issue is definitely with forge, it seems that one of its patches removes the field in question: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/entity/EntityList.java.patch#L7

I also accidentally found the following in my log file coming from WorldDownloader, it seems like they struggled with the same issue:
```
[20:34:31] [World Downloader update check thread/INFO]: [WDL] NoSuchFieldException due to forge; switching to fallback. This is (sadly) expected: 
java.lang.NoSuchFieldError: field_191308_b
	at wdl.StandardEntityManagers.<clinit>(StandardEntityManagers_1_12.java:383) [StandardEntityManagers.class:?]
	at wdl.EntityUtils.<clinit>(EntityUtils.java:48) [EntityUtils.class:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
	at java.lang.Class.forName(Class.java:264) [?:1.8.0_265]
	at wdl.update.ClassHasher.hash(ClassHasher.java:57) [ClassHasher.class:?]
	at wdl.update.WDLUpdateChecker.run(WDLUpdateChecker.java:316) [WDLUpdateChecker.class:?]
```

See https://github.com/Pokechu22/WorldDownloader/commit/624380b4c65aa2c501d790af6eb7b8d359aacdcd
