### ISSUE TITLE
baritone not building

### ISSUE THREAD

**Issue by jabba24657** [cabaletta/baritone#1422]
Operating system: Windows
Minecraft version: 1.14.4

[17:22:50] [main/INFO]: [CHAT] [Baritone] > build TownHall.schematic
[17:22:50] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:22:50] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$2665/1012472328.accept(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:22:50] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.1B$$Lambda$2148/1064280797.0(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.0f$$Lambda$2163/1225761077.invoke(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[17:22:50] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[17:22:50] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1696/1766973538.accept(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[17:22:50] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[17:22:50] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[17:22:50] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[17:22:50] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[17:22:50] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[17:22:50] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[17:22:50] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[17:22:50] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:410)
[17:22:50] [main/INFO]: [STDERR]: 	at cya$$Lambda$2627/2145209191.run(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[17:22:50] [main/INFO]: [STDERR]: 	at cya.a(SourceFile:408)
[17:22:50] [main/INFO]: [STDERR]: 	at cya$$Lambda$1471/1914765072.invoke(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:22:50] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:22:50] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17:22:50] [main/INFO]: [STDERR]: 	at cuo.k(SourceFile:408)
[17:22:50] [main/INFO]: [STDERR]: 	at cuo.c(SourceFile:279)
[17:22:50] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[17:22:50] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[17:22:50] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[17:22:50] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:22:50] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:22:50] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:22:50] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:22:50] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:22:50] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[17:22:50] [main/INFO]: [STDERR]: 	... 49 more

**Comment by S-B99** [comment]
You need to include the **full** file name in the command.

**Comment by jabba24657** [comment]
I tried writing out the whole file name and it said the same thing

**Comment by S-B99** [comment]
You did not, as shown by the log.

**Comment by jabba24657** [comment]
i just tried it a minute ago

**Comment by S-B99** [comment]
Then send a log of when it doesn't work when you *do* include the full file name, as in the log you sent you did *not* include the full file name.

**Comment by jabba24657** [comment]
its updated

**Comment by VortexCZE09** [comment]
I was reporting this yesterday and i got answer "use full file name". There is proof, that even with .schematic it doesnt work. https://imgur.com/a/SGCawhV

There is error log (Minecraft 1.13.2)

[09:29:58] [main/INFO]: [CHAT] [Baritone] > build muf.schematic
[09:29:58] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[09:29:58] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.ce$$Lambda$2430/488805494.accept(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.9M.0(9M.java:26)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.9M.0(9M.java:14)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:29:58] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.9a.0(9a.java:67)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.8E$$Lambda$1521/498744418.0(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.03.0(03.java:12)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.0P.0(0P.java:18)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.0P$$Lambda$1536/1709362345.invoke(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[09:29:58] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[09:29:58] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1070/1119948605.accept(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[09:29:58] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[09:29:58] [main/INFO]: [STDERR]: 	at net.impactclient.8b.post(8b.java:2)
[09:29:58] [main/INFO]: [STDERR]: 	at ctj.redirect$sendChatPacket$zzd000(SourceFile:1239)
[09:29:58] [main/INFO]: [STDERR]: 	at ctj.f(SourceFile:320)
[09:29:58] [main/INFO]: [STDERR]: 	at ckd.b(SourceFile:301)
[09:29:58] [main/INFO]: [STDERR]: 	at ckd.e(SourceFile:294)
[09:29:58] [main/INFO]: [STDERR]: 	at cjg.keyPressed(SourceFile:131)
[09:29:58] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:389)
[09:29:58] [main/INFO]: [STDERR]: 	at cfq$$Lambda$2428/630347345.run(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at ckd.a(SourceFile:430)
[09:29:58] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:387)
[09:29:58] [main/INFO]: [STDERR]: 	at cfq$$Lambda$877/177711253.invoke(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[09:29:58] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[09:29:58] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3108)
[09:29:58] [main/INFO]: [STDERR]: 	at cgd.a(SourceFile:321)
[09:29:58] [main/INFO]: [STDERR]: 	at cft.c(SourceFile:875)
[09:29:58] [main/INFO]: [STDERR]: 	at cft.a(SourceFile:395)
[09:29:58] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:144)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:29:58] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:29:58] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:29:58] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[09:29:58] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:29:58] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.go.<init>(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.dz.build(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	at baritone.am.execute(Unknown Source)
[09:29:58] [main/INFO]: [STDERR]: 	... 47 more
[09:30:00] [main/INFO]: AutoCasting
[09:30:01] [main/INFO]: [CHAT] Saved screenshot as 2020-03-21_09.30.01.png

**Comment by redbrain1014** [comment]
> [09:29:58] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
maybe the schematic used numeric ids and the game (1.13+) didn't understand it.

**Comment by VortexCZE09** [comment]
I hope they will fix it, i really need schematica for > 1.12.2

**Comment by S-B99** [comment]
Schematica works for above 1.12.2. This error is from your schematic being created in the wrong version.
