### ISSUE TITLE
Baritone crashing as soon as im launching it.

### ISSUE THREAD

**Issue by 0nics** [cabaletta/baritone#1507]
## Some information
Operating system: Windows 10
Java version: Java Version 8 Update 241 (Build 1.8.0_241-b07)
Minecraft version: 1.14.4
Baritone version: 1.4.2
Forge mods (if used): None

## Exception, error or logs
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at io.github.impactdevelopment.simpletweaker.SimpleTweaker.doInitialSetup(SimpleTweaker.java:96)
	at io.github.impactdevelopment.simpletweaker.SimpleTweaker.injectIntoClassLoader(SimpleTweaker.java:57)
	at baritone.launch.BaritoneTweaker.injectIntoClassLoader(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
## How to reproduce
I followed the exact steps in CraftStone's video about how to install Baritone on 1.14.4 without any additional mods. As soon as i try to open it, it instantly crashes and gives me these error logs.

Edit: I tried it on 1.15.2, it worked there.
        My friend tried it on 1.14.4 and he got the same error message and the same type of crash 
        aswell.

**Comment by UltraBlackLinux** [comment]
have you placed the right baritone version in your libraries folder?

**Comment by satyamedh** [comment]
stale issue close it pls :P
