### ISSUE TITLE
Baritone crashing on Multimc

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1533]
## What do you need help with?
I wanna use baritone on MultiMC, so I created this custom Patch:

{
    "+tweakers": [
        "baritone.launch.BaritoneTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "baritone-api:1.5.2",
            "M1.15.2-hint": "local",
            "M1.15.2-filename": "baritone-api-1.5.2.jar"            
        },
        {
            "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
            "url": "https://impactdevelopment.github.io/maven/"
        },
        {
            "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
            "url": "https://repo.spongepowered.org/maven/"
        },
        {
            "name": "org.ow2.asm:asm-all:5.0.3",
            "url": "https://repo1.maven.org/maven2/"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "releaseTime": "2019-07-23T20:50:21+00:00",
    "type": "release",
    "name": "Baritone",
    "uid": "baritone",
    "version": "1.5.2",
    "requires": [
        {
            "equals": "1.15.2",
            "uid": "net.minecraft"
        }
    ]
}

Sadly MC crashes with this error:

[main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: baritone.launch.BaritoneTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

Any suggestions, how i can fix this?

## Final checklist
- [ ] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
You're missing the baritone library, your json is probably incorrect.

**Comment by UltraBlackLinux** [comment]
> You're missing the baritone library, your json is probably incorrect.
what library?

**Comment by dominikaaaa** [comment]
the error is literally you don't have baritone

**Comment by UltraBlackLinux** [comment]
do i have to put baritone in a specific folder inside of libraries?

**Comment by dominikaaaa** [comment]
No, the json does it for you. Your json is incorrect.

**Comment by UltraBlackLinux** [comment]
i want to make it different, cause the impact maven repo is sieriously outdated, so i downloaded the newest api version for my client and put it into the libraries folder.

**Comment by dominikaaaa** [comment]
no clue, sorry

**Comment by UltraBlackLinux** [comment]
oh :(

**Comment by dominikaaaa** [comment]
ye, just did so now

**Comment by UltraBlackLinux** [comment]
ty so much
