### ISSUE TITLE
try to use .b build schematic name.

### ISSUE THREAD

**Issue by wtfbrohaha** [cabaletta/baritone#1605]
[06:28:06] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[06:28:06] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3720/2061102481.accept(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:28:06] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.1B$$Lambda$2252/1877764981.0(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.0f$$Lambda$2267/112701510.invoke(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[06:28:06] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[06:28:06] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1705/354419506.accept(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[06:28:06] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[06:28:06] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[06:28:06] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[06:28:06] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[06:28:06] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[06:28:06] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[06:28:06] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[06:28:06] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[06:28:06] [main/INFO]: [STDERR]: 	at cya.lambda$onKeyEvent$4(KeyboardListener.java:440)
[06:28:06] [main/INFO]: [STDERR]: 	at cya$$Lambda$3718/2075521461.run(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[06:28:06] [main/INFO]: [STDERR]: 	at cya.a(KeyboardListener.java:407)
[06:28:06] [main/INFO]: [STDERR]: 	at cya$$Lambda$1473/1877226071.invoke(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[06:28:06] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[06:28:06] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[06:28:06] [main/INFO]: [STDERR]: 	at cuo.k(MainWindow.java:503)
[06:28:06] [main/INFO]: [STDERR]: 	at cuo.c(MainWindow.java:342)
[06:28:06] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[06:28:06] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[06:28:06] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[06:28:06] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:28:06] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:28:06] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[06:28:06] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[06:28:06] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[06:28:06] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[06:28:06] [main/INFO]: [STDERR]: 	... 50 more

**Comment by wtfbrohaha** [comment]
and
////

06:39:44] [main/INFO]: [CHAT] [Baritone] > build saturn-v
[06:39:44] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[06:39:44] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3720/1438926309.accept(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:6)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.7.0(7.java:16)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:39:44] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.6.0(6.java:55)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.1B$$Lambda$2174/946432134.0(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.4a.0(4a.java:5)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.0f.0(0f.java:38)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.0f$$Lambda$2189/2102026771.invoke(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[06:39:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[06:39:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager$$Lambda$1721/441427423.accept(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[06:39:44] [main/INFO]: [STDERR]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[06:39:44] [main/INFO]: [STDERR]: 	at net.impactclient.01M.post(01M.java:3)
[06:39:44] [main/INFO]: [STDERR]: 	at dmp.redirect$sendChatPacket$zzd000(SourceFile:1200)
[06:39:44] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile:288)
[06:39:44] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[06:39:44] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[06:39:44] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[06:39:44] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[06:39:44] [main/INFO]: [STDERR]: 	at cya.lambda$onKeyEvent$4(KeyboardListener.java:440)
[06:39:44] [main/INFO]: [STDERR]: 	at cya$$Lambda$3387/716066433.run(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[06:39:44] [main/INFO]: [STDERR]: 	at cya.a(KeyboardListener.java:407)
[06:39:44] [main/INFO]: [STDERR]: 	at cya$$Lambda$1494/1877226071.invoke(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[06:39:44] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[06:39:44] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[06:39:44] [main/INFO]: [STDERR]: 	at cuo.k(MainWindow.java:503)
[06:39:44] [main/INFO]: [STDERR]: 	at cuo.c(MainWindow.java:342)
[06:39:44] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[06:39:44] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[06:39:44] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[06:39:44] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:39:44] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:39:44] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[06:39:44] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[06:39:44] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[06:39:44] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[06:39:44] [main/INFO]: [STDERR]: 	... 50 more

**Comment by dominikaaaa** [comment]
include the full file name
