### ISSUE TITLE
Hello. Baritone can't follow players with a weird username. 

### ISSUE THREAD

**Issue by miclol** [cabaletta/baritone#1608]
[15:34:31] [main/INFO]: [CHAT] [Fabritone] > follow player (username that starts and ends with an underscore)
[15:34:31] [main/INFO]: [CHAT] [Fabritone] Following these types of entities:
[15:34:31] [main/INFO]: [CHAT] [Fabritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[15:34:31] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.runCommand(BaritoneChatControl.java:145)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.onSendChatMessage(BaritoneChatControl.java:70)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:70)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler$$Lambda$4003/294237682.accept(Unknown Source)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:70)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zcj000$sendChatMessage(class_746.java:1250)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.sendMessage(class_437.java:326)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.sendMessage(class_437.java:319)
[15:34:31] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.keyPressed(class_408.java:95)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:336)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$3991/1356757853.run(Unknown Source)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:334)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.lambda$null$7(class_309.java:627)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$3968/157211110.run(Unknown Source)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:104)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.lambda$setupCallbacks$8(class_309.java:626)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$1662/890250372.invoke(Unknown Source)
[15:34:31] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[15:34:31] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[15:34:31] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[15:34:31] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:363)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1012)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:619)
[15:34:31] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:204)
[15:34:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:34:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:34:31] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:34:31] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:34:31] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[15:34:31] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[15:34:31] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[15:34:31] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand$$Lambda$4256/120659815.apply(Unknown Source)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:34:31] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand.execute(FollowCommand.java:81)
[15:34:31] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[15:34:31] [main/INFO]: [STDERR]: 	... 38 more
[15:34:36] [pool-5-thread-2/INFO]: [STDOUT]: World save took 2ms

**Comment by dominikaaaa** [comment]
This is the baritone repo, not fabritone repo.

**Comment by miclol** [comment]
I know you won't care about me as you already have a bad impression but...
[12:23:54] [main/INFO]: [CHAT] [Baritone] > follow player (username with start and end with underscore)
[12:23:54] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[12:23:54] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[12:23:54] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.ce$$Lambda$2752/370402731.accept(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at dqb.handler$sendChatMessage$zza000(SourceFile)
[12:23:54] [main/INFO]: [STDERR]: 	at dqb.f(SourceFile)
[12:23:54] [main/INFO]: [STDERR]: 	at dgb.sendMessage(SourceFile:326)
[12:23:54] [main/INFO]: [STDERR]: 	at dgb.sendMessage(SourceFile:319)
[12:23:54] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[12:23:54] [main/INFO]: [STDERR]: 	at dfa.keyPressed(SourceFile:95)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl.lambda$onKeyEvent$4(KeyboardListener.java:439)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl$$Lambda$2728/530913105.run(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at dgb.wrapScreenError(SourceFile:447)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl.a(KeyboardListener.java:406)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl.lambda$null$7(KeyboardListener.java:615)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl$$Lambda$2719/237580721.run(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at ais.execute(ThreadTaskExecutor.java:104)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl.lambda$setupCallbacks$8(KeyboardListener.java:614)
[12:23:54] [main/INFO]: [STDERR]: 	at dbl$$Lambda$1522/1530856786.invoke(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[12:23:54] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[12:23:54] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[12:23:54] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)
[12:23:54] [main/INFO]: [STDERR]: 	at cxx.e(MainWindow.java:363)
[12:23:54] [main/INFO]: [STDERR]: 	at dbn.d(SourceFile:1012)
[12:23:54] [main/INFO]: [STDERR]: 	at dbn.d(SourceFile:619)
[12:23:54] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:204)
[12:23:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:54] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:23:54] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:23:54] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:23:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:23:54] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:23:54] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.ba$$Lambda$2791/1506992655.apply(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[12:23:54] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[12:23:54] [main/INFO]: [STDERR]: 	at baritone.ba.execute(Unknown Source)
[12:23:54] [main/INFO]: [STDERR]: 	... 36 more
Even with Baritone the same error occurs. (I have noticed this error only occurs with Optifine tho) (I  think this is a cross-compatibility problem...?)

**Comment by miclol** [comment]
Json file I used to merge Optifine with Baritone: https://github.com/cabaletta/baritone/issues/1359

**Comment by dominikaaaa** [comment]
I don't care for the attitude and don't have any sort of bias towards anyone, but we do not support Fabritone in this repository, it's an unofficial fork of Baritone. That said, I'll reopen this.

**Comment by UltraBlackLinux** [comment]
Actually if I try it it tells me:
[15:35:41] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.cd.execute(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.cf.a(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zze000(SourceFile)
[15:35:41] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[15:35:41] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[15:35:41] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[15:35:41] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.f(GuiChatOF.java:41)
[15:35:41] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[15:35:41] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[15:35:41] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[15:35:41] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[15:35:41] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[15:35:41] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[15:35:41] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:35:41] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:35:41] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:35:41] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:35:41] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:35:41] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:35:41] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:35:41] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:35:41] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:35:41] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:35:41] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:35:41] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[15:35:41] [main/INFO]: [STDERR]: 	at baritone.bb.execute(Unknown Source)
[15:35:41] [main/INFO]: [STDERR]: 	... 32 more

**Comment by UltraBlackLinux** [comment]
using multimc json patch optifine+baritone
