### ISSUE TITLE
baritone.api.command.exception.CommandUnhandledException

### ISSUE THREAD

**Issue by sourTaste000** [cabaletta/baritone#1687]
## Some information
Operating system: macOS 10.14.6
Java version: 1.8.0_251, using 64-bit architecture.
Minecraft version: 1.13.2
Baritone version: 1.3.5 (Integrated with Impact 4.8.3)
Forge mods (if used): none

## Exception, error or logs
https://paste.ee/p/c6qKc

## How to reproduce

`#build *any .schematica file fails*`

## Modified settings
chatControl is set to false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by sourTaste000** [comment]
oops i didnt change the title

**Comment by dominikaaaa** [comment]
You need to make the schematic in 1.13

**Comment by dominikaaaa** [comment]
Oh actually, in your log you forgot to include the full file name
> build sakura-tree

**Comment by sourTaste000** [comment]
```
17:54:26] [main/INFO]: [CHAT] [Baritone] > build sakura-tree.schematic
[17:54:26] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:54:26] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at ctj.handler$sendChatMessage$zeg000(SourceFile)
[17:54:26] [main/INFO]: [STDERR]: 	at ctj.f(SourceFile)
[17:54:26] [main/INFO]: [STDERR]: 	at ckd.b(SourceFile:301)
[17:54:26] [main/INFO]: [STDERR]: 	at ckd.e(SourceFile:294)
[17:54:26] [main/INFO]: [STDERR]: 	at cjg.keyPressed(SourceFile:131)
[17:54:26] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:389)
[17:54:26] [main/INFO]: [STDERR]: 	at ckd.a(SourceFile:430)
[17:54:26] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:387)
[17:54:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:54:26] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:54:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
[17:54:26] [main/INFO]: [STDERR]: 	at cgd.a(SourceFile:309)
[17:54:26] [main/INFO]: [STDERR]: 	at cft.c(SourceFile:875)
[17:54:26] [main/INFO]: [STDERR]: 	at cft.a(SourceFile:395)
[17:54:26] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:144)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:54:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:54:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:54:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:54:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:54:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:54:26] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:54:26] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:54:26] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:54:26] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:54:26] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.go.<init>(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.dz.build(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	at baritone.am.execute(Unknown Source)
[17:54:26] [main/INFO]: [STDERR]: 	... 35 more
```

**Comment by dominikaaaa** [comment]
And as I thought, it's the other thing. 
> You need to make the schematic in 1.13

**Comment by sourTaste000** [comment]
```
17:58:48] [main/INFO]: [CHAT] [Baritone] > build small_tower.schematic
[17:58:48] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:58:48] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at ctj.handler$sendChatMessage$zeg000(SourceFile)
[17:58:48] [main/INFO]: [STDERR]: 	at ctj.f(SourceFile)
[17:58:48] [main/INFO]: [STDERR]: 	at ckd.b(SourceFile:301)
[17:58:48] [main/INFO]: [STDERR]: 	at ckd.e(SourceFile:294)
[17:58:48] [main/INFO]: [STDERR]: 	at cjg.keyPressed(SourceFile:131)
[17:58:48] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:389)
[17:58:48] [main/INFO]: [STDERR]: 	at ckd.a(SourceFile:430)
[17:58:48] [main/INFO]: [STDERR]: 	at cfq.a(SourceFile:387)
[17:58:48] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:58:48] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:58:48] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
[17:58:48] [main/INFO]: [STDERR]: 	at cgd.a(SourceFile:309)
[17:58:48] [main/INFO]: [STDERR]: 	at cft.c(SourceFile:875)
[17:58:48] [main/INFO]: [STDERR]: 	at cft.a(SourceFile:395)
[17:58:48] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:144)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:58:48] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:58:48] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:58:48] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:58:48] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:58:48] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:58:48] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:58:48] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:58:48] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:58:48] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:58:48] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.go.<init>(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.dz.build(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	at baritone.am.execute(Unknown Source)
[17:58:48] [main/INFO]: [STDERR]: 	... 35 more
```
lul

**Comment by sourTaste000** [comment]
https://www.planetminecraft.com/project/small-medieval-style-tower-1-13-2/

**Comment by sourTaste000** [comment]
im on creative mode if that information helps

**Comment by sourTaste000** [comment]
and I installed impact on multimc

**Comment by dominikaaaa** [comment]
The error suggests otherwise. The schematic was most likely built in 1.12.2 and converted. 

Use sponge format or something. Also, Impact is only supported on the official MC launcher

**Comment by sourTaste000** [comment]
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC

**Comment by sourTaste000** [comment]
ok will try sponge format

**Comment by dominikaaaa** [comment]
My bad :p
I guess there are exceptions.

**Comment by sourTaste000** [comment]
can u reopen this issue?

**Comment by sourTaste000** [comment]
or i need to try sponge format first lol

**Comment by dominikaaaa** [comment]
try that
