### ISSUE TITLE
Follow entity zombie results in an error

### ISSUE THREAD

**Issue by Zeptora** [cabaletta/baritone#1815]
## Some information
Operating system: Windows 10
Java version: 
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): Liteloader

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[04:10:00] [Client thread/INFO]: [CHAT] [Baritone] > follow entity zombie
[04:10:00] [Client thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_191308_b
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.y.a(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.y.onSendChatMessage(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.a(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf$$Lambda$290/993633096.accept(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zbh000(EntityPlayerSP.java)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[04:10:00] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchFieldError: field_191308_b
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.ag.getDatatypeFor(Unknown Source)
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.bb.execute(Unknown Source)
[04:10:00] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 24 more
Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I typed in follow entity zombie
## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
That means there's no zombies to follow

**Comment by Zeptora** [comment]
I put a zombie right next to me, obviously.
