### ISSUE TITLE
An unhandled exception has occured. the error is in your game's log.

### ISSUE THREAD

**Issue by DaMagicFox** [cabaletta/baritone#1835]
## Some information
Operating system: Windows 10
Java version: 8th Version 241st update
Minecraft version: 1.16.1
Baritone version: 1.4.2 
Forge mods (if used): None

## Exception, error or logs
[23:13:19] [main/INFO]: [CHAT] [Fabritone] > mine diamond_ore
[23:13:19] [main/INFO]: [CHAT] [Fabritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]
[23:13:19] [main/INFO]: [CHAT] [Fabritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:13:19] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.runCommand(BaritoneChatControl.java:168)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.onSendChatMessage(BaritoneChatControl.java:90)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:71)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler$$Lambda$3910/119637292.accept(Unknown Source)
[23:13:19] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[23:13:19] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:71)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zcm000$sendChatMessage(class_746.java:1274)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:309)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:302)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:98)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:350)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$3845/2135366219.run(Unknown Source)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:431)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:348)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:438)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$3829/2039550308.run(Unknown Source)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:438)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_309$$Lambda$2594/1448517199.invoke(Unknown Source)
[23:13:19] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[23:13:19] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[23:13:19] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[23:13:19] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:308)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1041)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:654)
[23:13:19] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[23:13:19] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:13:19] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:13:19] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:13:19] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:13:19] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[23:13:19] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[23:13:19] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[23:13:19] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException

...
## How to reproduce
Just wrote @mine diamond_ore in chat.
## Modified settings
--
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Cookietank** [comment]
Hey bro I'm having the exact same issue

**Comment by dominikaaaa** [comment]
this is baritone

**Comment by Cookietank** [comment]
> this is baritone

What do you mean

**Comment by dominikaaaa** [comment]
this is the baritone repository

**Comment by DaMagicFox** [comment]
?

**Comment by dominikaaaa** [comment]
this. is. the. baritone. repository.

**Comment by dominikaaaa** [comment]
https://gitlab.com/CDAGaming/fabritone/

**Comment by dominikaaaa** [comment]
learn how to use google

**Comment by DaMagicFox** [comment]
I didn't know, it literally told me to search here, so it hasn't anything to do with wrong google searches

**Comment by dominikaaaa** [comment]
Yes it does. You're using Fabritone. This is not Fabritone, this is Baritone. It is not Baritone's fault that Fabritone provides the wrong help URL.

**Comment by Cookietank** [comment]
it's not our fault that the devs on here are so unhelpful when we ask for help

**Comment by dominikaaaa** [comment]
You're asking for help with something else

It's like walking into an Android store asking for help with an iPhone. We won't help you here

**Comment by RealIndrit** [comment]
Is this the crash on @ only in chat? @CDAGaming  fix this, i dont have time currently. Also double check chat porting because this should not be a problem on straight over port...

**Comment by CDAGaming** [comment]
@RealIndrit The original rebase is based on a commit 3 months old. A New rebase is planned for this weekend

**Comment by dominikaaaa** [comment]
Looking forward to that, but perhaps an issue on the Baritone github isn't the best place to discuss it

**Comment by CDAGaming** [comment]
@dominikaaaa Completed it a few hours ago, but yeah here's not the best spot. But the ports should be way nicer but feel free to report issues **ON THE FABRITONE REPO**

**Comment by dominikaaaa** [comment]
@CDAGaming yes, and a way to prevent dumb people from reporting issues here is to remove the Baritone repo URL from Fabritone.

**Comment by CDAGaming** [comment]
@dominikaaaa That I plan to do tonight (Got a flight today that cuts in the middle of that lol)

**Comment by justbecauseyouwereacompletedick** [comment]
> Yes it does. You're using Fabritone. This is not Fabritone, this is Baritone. It is not Baritone's fault that Fabritone provides the wrong help URL.

Hello 5HT2, 
I was scrolling through pages rather mindlessly, when I came across this interaction. It baffled me so greatly that I simply had to say something. I spent about 20 minutes of my day creating and verifying an account just so I could say: You are one of the rudest, most unaware, illogical creatures I have ever seen in recent times. You were incredibly rude to someone who doesn't know any better, and was literally following instructions and researching. You blame them personally at every point, and make great efforts to belittle them. You lack basic understanding that not everyone shares the knowledge that you have. You completely contradict yourself and ignore critical information, and continue to shit on this person. OP did everything right, and yet you call them dumb, and treat every tid bit of information as if it were obvious. You could have so easily been nice and understanding, and resolved the error in 1 or 2 sentences, but instead you go on a lengthy tirade, making some stranger feel like shit even when you are the one who is completely missing any sense of decency and understanding. I sincerely hope you have improved as a person two years later, I really do. I hope you can look back on this and feel a twinge of guilt for making a stranger's day worse due to your own intolerance of other human beings. I want you to live life being better than that. For your own sake.
