### ISSUE TITLE
Crash on dimension change

### ISSUE THREAD

**Issue by atheran2** [cabaletta/baritone#1839]
## Some information
Operating system: Windows 10
Java version: jre1.8.0_251
Minecraft version: 1.12.2
Baritone version: baritone-standalone-forge-1.2.14
Forge mods (if used): A whole bunch.

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Create a new dimension from RFTools dimensions and step through it. I know it's an incompatibility with baritone, since without it I have no problems changing dimensions. I don't expect any real support or fixes since it's a huge list of mods, just thought I'd throw it out here in case anyone else faces a similar issue.

EDIT: I'll fire up a new modded version with just forge, baritone and RFTools Dimensions in a couple of hours to test those two mods alone to see if there's an incompatibily between them or other mods are getting in the middle to cause the crash. So far on my heavily modded game it crashes with baritone when going through the new dimension and works fine without baritone. Also so far baritone doesn't have a problem with the Nether or the End but haven't tried it with modded dimensions yet. 

[latest.log](https://github.com/cabaletta/baritone/files/4855718/latest.log)

Debug file was too big but here's a copy paste of the specific error from the MultiMC console.

`[07:33:00] [Client thread/ERROR] [FML]: Cannot Hotload Dim: 7892
java.lang.IllegalArgumentException: Could not get provider type for dimension 7892, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:164) ~[DimensionManager.class:14.23.5.2854]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:257) [DimensionManager.class:14.23.5.2854]
	at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:832) [MinecraftServer.class:?]
	at baritone.ew.a(Unknown Source) [ew.class:1.2.14]
	at baritone.hf.a(Unknown Source) [hf.class:1.2.14]
	at net.minecraft.client.Minecraft.handler$postLoadWorld$zdh000(Minecraft.java) [bib.class:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2536) [bib.class:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2430) [bib.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleRespawn(NetHandlerPlayClient.java:2258) [brz.class:?]
	at net.minecraft.network.play.server.SPacketRespawn.processPacket(SourceFile:31) [jw.class:?]
	at net.minecraft.network.play.server.SPacketRespawn.processPacket(SourceFile:12) [jw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
	at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

and

`java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
    at baritone.ew.a(Unknown Source)
    at baritone.hf.a(Unknown Source)
    at net.minecraft.client.Minecraft.handler$postLoadWorld$zdh000(Minecraft.java)
    at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2430)
    at net.minecraft.client.network.NetHandlerPlayClient.handleRespawn(NetHandlerPlayClient.java:2258)
    at net.minecraft.network.play.server.SPacketRespawn.processPacket(SourceFile:31)
    at net.minecraft.network.play.server.SPacketRespawn.processPacket(SourceFile:12)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 17 more`

EDIT: The dimension number is not something I can change in configs. RF Dimensions generates a new ID on the fly each time taking into account already registered dimension IDs.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
This is caused by the mods you're using, not baritone
