### ISSUE TITLE
Baritone settings unhanded exception

### ISSUE THREAD

**Issue by diap3rsnip3r** [cabaletta/baritone#1858]
When doing @ settings and using the click menu to see more settings it wont go past and has an unhandled exception,
heres the log:
[14:26:48] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.runCommand(BaritoneChatControl.java:168)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.BaritoneChatControl.onSendChatMessage(BaritoneChatControl.java:90)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:71)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler$$Lambda$4376/1509427980.accept(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:71)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zfd000$sendChatMessage(class_746.java:1274)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:309)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25430(class_437.java:289)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25402(class_408.java:150)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:92)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312$$Lambda$3451/298321972.run(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:431)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:92)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:162)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312$$Lambda$3347/1439252493.run(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:162)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_312$$Lambda$2818/119176807.invoke(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[14:26:48] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[14:26:48] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[14:26:48] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:308)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1041)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:654)
[14:26:48] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[14:26:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:26:48] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:26:48] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:26:48] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:26:48] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[14:26:48] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[14:26:48] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[14:26:48] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil$Parser$1.lambda$toString$1(SettingsUtil.java:258)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil$Parser$1$$Lambda$4462/1223781477.apply(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:26:48] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil$Parser$1.toString(SettingsUtil.java:259)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.settingValueToString(SettingsUtil.java:148)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.settingValueToString(SettingsUtil.java:153)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.defaults.SetCommand.lambda$execute$4(SetCommand.java:92)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.defaults.SetCommand$$Lambda$4442/602255637.apply(Unknown Source)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.command.helpers.Paginator.display(Paginator.java:67)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.api.command.helpers.Paginator.paginate(Paginator.java:144)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.defaults.SetCommand.execute(SetCommand.java:70)
[14:26:48] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[14:26:48] [main/INFO]: [STDERR]: 	... 37 more

**Comment by dominikaaaa** [comment]
This is Baritone.

**Comment by UltraBlackLinux** [comment]
@dominikaaaa wdym? An unstable bot for minecraft that iften decides to spit out errors?

**Comment by dominikaaaa** [comment]
No, I mean they're asking for help with not Baritone.

**Comment by dominikaaaa** [comment]
People need to stop asking for help with not Baritone here

**Comment by diap3rsnip3r** [comment]
i forgot this was fapritone

**Comment by UltraBlackLinux** [comment]
Fa*b*ritone
