### ISSUE TITLE
#follow player reporting an error instead of telling you that you can't follow that player

### ISSUE THREAD

**Issue by ZacSharp** [cabaletta/baritone#1926]
## Some information
Operating system: Linux / Windows 10 / Linux / ?
Java version: 1.8
Minecraft version: 1.12.2 / 1.14.4 / 1.15.2 / 1.15.2
Baritone version: 1.2.14 / 1.4.3 / 1.5.2 / 1.5.3
Forge mods (if used): None / None / None / ? 

## Exception, error or logs
<details><summary>log1</summary>
<pre>[01:38:09] [main/INFO]: [CHAT] [Baritone] > follow player ThePlayer
[01:38:09] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[01:38:09] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[01:38:09] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:143)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:127)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:83)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:145)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:70)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:69)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:69)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java:1416)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:456)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:446)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:126)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:607)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:556)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1852)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1165)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:439)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:115)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:38:09] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:38:09] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:38:09] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:38:09] [main/INFO]: [STDERR]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[01:38:09] [main/INFO]: [STDERR]: 	at GradleStart.main(GradleStart.java:25)
[01:38:09] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:38:09] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand.execute(FollowCommand.java:79)
[01:38:09] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:140)
[01:38:09] [main/INFO]: [STDERR]: 	... 30 more
</pre></details>
<details><summary>log2</summary>
<pre>[18:07:26] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[18:07:26] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:07:26] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[18:07:26] [main/INFO]: [STDERR]: at baritone.cb.execute(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at baritone.w.a(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at baritone.w.onSendChatMessage(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at baritone.cd.a(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at baritone.cd$$Lambda$3005/254087276.accept(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[18:07:26] [main/INFO]: [STDERR]: at baritone.cd.onSendChatMessage(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at dmp.handler$sendChatMessage$zzb000(SourceFile)
[18:07:26] [main/INFO]: [STDERR]: at dmp.f(SourceFile)
[18:07:26] [main/INFO]: [STDERR]: at dcl.sendMessage(SourceFile:318)
[18:07:26] [main/INFO]: [STDERR]: at dcl.sendMessage(SourceFile:311)
[18:07:26] [main/INFO]: [STDERR]: at dbl.keyPressed(SourceFile:129)
[18:07:26] [main/INFO]: [STDERR]: at cya.a(SourceFile:410)
[18:07:26] [main/INFO]: [STDERR]: at cya$$Lambda$2994/1387022456.run(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at dcl.wrapScreenError(SourceFile:441)
[18:07:26] [main/INFO]: [STDERR]: at cya.a(SourceFile:408)
[18:07:26] [main/INFO]: [STDERR]: at cya$$Lambda$1479/1795330205.invoke(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[18:07:26] [main/INFO]: [STDERR]: at org.lwjgl.system.JNI.invokeV(Native Method)
[18:07:26] [main/INFO]: [STDERR]: at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[18:07:26] [main/INFO]: [STDERR]: at cuo.k(SourceFile:408)
[18:07:26] [main/INFO]: [STDERR]: at cuo.c(SourceFile:279)
[18:07:26] [main/INFO]: [STDERR]: at cyc.b(SourceFile:1023)
[18:07:26] [main/INFO]: [STDERR]: at cyc.e(SourceFile:976)
[18:07:26] [main/INFO]: [STDERR]: at cyc.b(SourceFile:410)
[18:07:26] [main/INFO]: [STDERR]: at net.minecraft.client.main.Main.main(SourceFile:155)
[18:07:26] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:07:26] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:07:26] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:07:26] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:497)
[18:07:26] [main/INFO]: [STDERR]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:07:26] [main/INFO]: [STDERR]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:07:26] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[18:07:26] [main/INFO]: [STDERR]: at baritone.av$$Lambda$3277/422342907.apply(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[18:07:26] [main/INFO]: [STDERR]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:07:26] [main/INFO]: [STDERR]: at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[18:07:26] [main/INFO]: [STDERR]: at baritone.av.execute(Unknown Source)
[18:07:26] [main/INFO]: [STDERR]: ... 32 more).</pre></details>
<details><summary>log3</summary>
<pre>[23:21:26] [main/INFO]: [CHAT] [Baritone] > follow player spegg69
[23:21:26] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[23:21:26] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:21:26] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.cc.execute(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.ce.a(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	at dqb.handler$zza000$sendChatMessage(SourceFile)
[23:21:26] [main/INFO]: [STDERR]: 	at dqb.f(SourceFile)
[23:21:26] [main/INFO]: [STDERR]: 	at dgb.sendMessage(SourceFile:326)
[23:21:26] [main/INFO]: [STDERR]: 	at dgb.sendMessage(SourceFile:319)
[23:21:26] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[23:21:26] [main/INFO]: [STDERR]: 	at dfa.keyPressed(SourceFile:95)
[23:21:26] [main/INFO]: [STDERR]: 	at dbl.lambda$onKeyEvent$4(KeyboardListener.java:451)
[23:21:26] [main/INFO]: [STDERR]: 	at dgb.wrapScreenError(SourceFile:447)
[23:21:26] [main/INFO]: [STDERR]: 	at dbl.a(KeyboardListener.java:418)
[23:21:26] [main/INFO]: [STDERR]: 	at dbl.lambda$null$7(KeyboardListener.java:627)
[23:21:26] [main/INFO]: [STDERR]: 	at ais.execute(ThreadTaskExecutor.java:104)
[23:21:26] [main/INFO]: [STDERR]: 	at dbl.lambda$setupCallbacks$8(KeyboardListener.java:626)
[23:21:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[23:21:26] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[23:21:26] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[23:21:26] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)
[23:21:26] [main/INFO]: [STDERR]: 	at cxx.e(MainWindow.java:363)
[23:21:26] [main/INFO]: [STDERR]: 	at dbn.d(SourceFile:1012)
[23:21:26] [main/INFO]: [STDERR]: 	at dbn.d(SourceFile:619)
[23:21:26] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:204)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:21:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:21:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:21:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:21:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:21:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:21:26] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[23:21:26] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[23:21:26] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[23:21:26] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[23:21:26] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:21:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[23:21:26] [main/INFO]: [STDERR]: 	at baritone.ba.execute(Unknown Source)
[23:21:26] [main/INFO]: [STDERR]: 	... 40 more
</pre></details>
no log4 available

## How to reproduce
Try to follow a player that is either offline or not in render distance.
Baritone will log an error and tell you to report it here, but following players that are not in render distance or offline is unsupported, so it should tell you that it can't follow instead.

## Modified settings
None / ? / parkour (place) and backtrackCostFavoringCoefficient / ?

## Final checklist
- [x] I know how to properly use check boxes.
- [x] I have included the versions of Minecraft that the players were running, baritone's versions and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue, except for the two in this line.

**Comment by calloutplayed** [comment]
Helpp
same problem
its saying to report here @l1ving

**Comment by l1ving** [comment]
This should actually be fixed on master, I can't reproduce the issue

**Comment by ZacSharp** [comment]
I can still reproduce this on d34f37c563449684656d18163462d81dd5100b60 (latest as of this writing)
I simply checked d34f37c563449684656d18163462d81dd5100b60 out, started the game, joined a new world and ran `follow player haha`

**Comment by l1ving** [comment]
Which jar are you running and which platform did you compile on?

**Comment by ZacSharp** [comment]
jar : None (runClient, still nothing better)
plattform: Linux, java 8

**Comment by ZacSharp** [comment]
jar: baritone-standalone-forge-1.2.14.jar
plattform: Linux, java8, Forge 14.23.0.2512
once again, error message with link to this repo

**Comment by l1ving** [comment]
oh my god

**Comment by Anonymus1181** [comment]
same problem here
It says it doesn't work and gives me a link to the github.

**Comment by scorbett123** [comment]
Ok, that is why this is still open, it hasn't been fixed yet.

**Comment by ZacSharp** [comment]
Fixed in #3024
