### ISSUE TITLE
Mining function doesn't work on the client i use.

### ISSUE THREAD

**Issue by iamPwnda** [cabaletta/baritone#1972]
## Some information
Operating system: Windows 10
Java version: fabric 0.9.1+build.205-1.16.2
Minecraft version: 1.16.2
Baritone version: No Idea, i use the latest Meteor Client
Forge mods (if used): 

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/5120675/latest.log)

## How to reproduce
i run either the command .b mine iron_ore or @mine iron_ore and it doesn't work unfortunately.
## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [[x] ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Fabritone issue.

**Comment by CDAGaming** [comment]
`[19:25:15] [main/INFO]: [CHAT] [Fabritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:25:15] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_1232
[19:25:15] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[19:25:15] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[19:25:15] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[19:25:15] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:77)
[19:25:15] [main/INFO]: [STDERR]: 	at minegame159.meteorclient.c9828.m6980(Unknown Source)
[19:25:15] [main/INFO]: [STDERR]: 	at minegame159.meteorclient.c5831.m5833(Unknown Source)
[19:25:15] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zzl000$onSendChatMessage(class_746.java)`

This error is a LootContextParameter that should be impossible to encounter, so id chalk this up to an old build or just related to the client, which fabritone nor baritone supports officially @iamPwnda
