### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by CZ2zZz** [cabaletta/baritone#1975]
## Some information
Operating system: what
Java version: 1.12.2
Minecraft version: 1.12.2
Baritone version: latest version for 1.12.2
Forge mods (if used):  none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[19:06:56] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[19:06:56] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[19:06:56] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker
[19:06:56] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[19:06:56] [main/INFO]: Injecting into ClassLoader
[19:06:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/crist/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[19:06:57] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[19:06:57] [main/INFO]: Initialized Mixin bootstrap
[19:06:57] [main/INFO]: Setup Mixin Environment
[19:06:57] [main/INFO]: Compatibility level set to JAVA_8
[19:06:57] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property
[19:06:57] [main/INFO]: Loaded Mixin Configurations
[19:06:57] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
[19:06:57] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[19:06:57] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:06:57] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinBlock, name: clientapi.load.mixin.MixinBlock
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntity, name: clientapi.load.mixin.MixinEntity
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityLivingBase, name: clientapi.load.mixin.MixinEntityLivingBase
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityPlayerSP, name: clientapi.load.mixin.MixinEntityPlayerSP
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinEntityRenderer, name: clientapi.load.mixin.MixinEntityRenderer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinFontRenderer, name: clientapi.load.mixin.MixinFontRenderer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiBossOverlay, name: clientapi.load.mixin.MixinGuiBossOverlay
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiIngame, name: clientapi.load.mixin.MixinGuiIngame
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinGuiSpectator, name: clientapi.load.mixin.MixinGuiSpectator
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinItemRenderer, name: clientapi.load.mixin.MixinItemRenderer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinLayerArmorBase, name: clientapi.load.mixin.MixinLayerArmorBase
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinMinecraft, name: clientapi.load.mixin.MixinMinecraft
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerLoginClient, name: clientapi.load.mixin.MixinNetHandlerLoginClient
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetHandlerPlayClient, name: clientapi.load.mixin.MixinNetHandlerPlayClient
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketDecoder, name: clientapi.load.mixin.MixinNettyPacketDecoder
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNettyPacketEncoder, name: clientapi.load.mixin.MixinNettyPacketEncoder
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinNetworkManager, name: clientapi.load.mixin.MixinNetworkManager
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinParticleManager, name: clientapi.load.mixin.MixinParticleManager
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRender, name: clientapi.load.mixin.MixinRender
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderItem, name: clientapi.load.mixin.MixinRenderItem
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderLivingBase, name: clientapi.load.mixin.MixinRenderLivingBase
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinRenderManager, name: clientapi.load.mixin.MixinRenderManager
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.capi.json:MixinTimer, name: clientapi.load.mixin.MixinTimer
[19:06:57] [main/WARN]: Error loading class: Config (java.lang.ClassNotFoundException: The specified class 'Config' was not found)
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinAnvilChunkLoader, name: baritone.launch.mixins.MixinAnvilChunkLoader
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBitArray, name: baritone.launch.mixins.MixinBitArray
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinBlockStateContainer, name: baritone.launch.mixins.MixinBlockStateContainer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChatTabCompleter, name: baritone.launch.mixins.MixinChatTabCompleter
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderClient, name: baritone.launch.mixins.MixinChunkProviderClient
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkProviderServer, name: baritone.launch.mixins.MixinChunkProviderServer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderContainer, name: baritone.launch.mixins.MixinChunkRenderContainer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinChunkRenderWorker, name: baritone.launch.mixins.MixinChunkRenderWorker
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityLivingBase, name: baritone.launch.mixins.MixinEntityLivingBase
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityPlayerSP, name: baritone.launch.mixins.MixinEntityPlayerSP
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinEntityRenderer, name: baritone.launch.mixins.MixinEntityRenderer
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinGuiScreen, name: baritone.launch.mixins.MixinGuiScreen
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinItemStack, name: baritone.launch.mixins.MixinItemStack
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinMinecraft, name: baritone.launch.mixins.MixinMinecraft
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetHandlerPlayClient, name: baritone.launch.mixins.MixinNetHandlerPlayClient
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinNetworkManager, name: baritone.launch.mixins.MixinNetworkManager
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinPlayerControllerMP, name: baritone.launch.mixins.MixinPlayerControllerMP
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderChunk, name: baritone.launch.mixins.MixinRenderChunk
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinRenderList, name: baritone.launch.mixins.MixinRenderList
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinStateImplementation, name: baritone.launch.mixins.MixinStateImplementation
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinTabCompleter, name: baritone.launch.mixins.MixinTabCompleter
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinVboRenderList, name: baritone.launch.mixins.MixinVboRenderList
[19:06:57] [main/ERROR]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.baritone.json:MixinWorldClient, name: baritone.launch.mixins.MixinWorldClient
[19:06:57] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:06:58] [main/INFO]: Setting user: Dxrts
[19:07:00] [main/INFO]: LWJGL Version: 2.9.4
[19:07:00] [main/INFO]: Reloading ResourceManager: Default
[19:07:00] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:07:01] [Thread-4/INFO]: Initializing LWJGL OpenAL
[19:07:01] [Thread-4/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:07:01] [Thread-4/INFO]: OpenAL initialized.
[19:07:01] [Sound Library Loader/INFO]: Sound engine started
[19:07:04] [main/INFO]: Created: 1024x512 textures-atlas
[19:07:06] [main/INFO]: Narrator library for x64 successfully loaded
[19:07:06] [main/INFO]: Initializing Fonts
[19:07:09] [main/ERROR]: Error getting Impact API token from minecraft login
java.io.IOException: /login/minecraft is not ok, it's 401
	at net.impactclient.5V.0(5V.java:4) [5V.class:?]
	at net.impactclient.7.<init>(7.java:21) [7.class:?]
	at net.impactclient.0H.0(0H.java:7) [0H.class:?]
	at net.impactclient.0ay.2(0ay.java:95) [0ay.class:?]
	at net.impactclient.4t.0(4t.java:5) [4t.class:?]
	at bib.handler$init$zzl000(SourceFile:3114) [bib.class:?]
	at bib.aq(SourceFile:583) [bib.class:?]
	at bib.a(SourceFile:404) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:07:09] [main/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:07:09] [main/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:07:09] [main/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:07:09] [main/INFO]: [STDOUT]: Sending event category=client action=launch label=4.9.1-1.12.2 cid=297632961.1597299695
[19:07:09] [pool-6-thread-1/INFO]: Checking for Updates
[19:07:09] [pool-6-thread-1/INFO]: [STDOUT]: Offering updates to betas: false
[19:07:09] [pool-6-thread-1/INFO]: [STDOUT]: Fetching releases from ImpactDevelopment/ImpactReleases
[19:07:09] [pool-6-thread-1/INFO]: [STDOUT]: DOWNLOADING http://impactclient.net/releases.json
[19:07:10] [main/INFO]: Initialized 119 mods!
[19:07:10] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[19:07:11] [main/INFO]: [STDOUT]: Initializing took 4271ms
[19:07:11] [main/ERROR]: Setting skin to impaste
[19:07:18] [main/INFO]: Connecting to 172.81.129.78, 25613
[19:07:24] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.nio.file.InvalidPathException: Trailing char < > at index 70: C:\Users\crist\AppData\Roaming\.minecraft\baritone\172.81.129.78_25613 \DIM0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at h.a(SourceFile:47) [h.class:?]
	at bib.az(SourceFile:991) [bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 70: C:\Users\crist\AppData\Roaming\.minecraft\baritone\172.81.129.78_25613 \DIM0
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:172) ~[?:1.8.0_51]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:1.8.0_51]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_51]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_51]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[?:1.8.0_51]
	at java.io.File.toPath(File.java:2234) ~[?:1.8.0_51]
	at baritone.v.a(Unknown Source) ~[v.class:1.2.14]
	at baritone.cf.onWorldEvent(Unknown Source) ~[cf.class:1.2.14]
	at bib.handler$postLoadWorld$zel000(SourceFile) ~[bib.class:?]
	at bib.a(SourceFile:2297) ~[bib.class:?]
	at bib.a(SourceFile:2218) ~[bib.class:?]
	at brz.a(SourceFile:297) ~[brz.class:?]
	at jh.a(SourceFile:76) ~[jh.class:?]
	at jh.a(SourceFile:13) ~[jh.class:?]
	at net.impactclient.31.run(31.java:7) ~[31.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at h.a(SourceFile:46) ~[h.class:?]
	... 9 more
[19:07:25] [main/WARN]: Received passengers for unknown entity
[19:07:25] [main/WARN]: Received passengers for unknown entity
[19:07:26] [main/INFO]: Loaded 338 advancements
[19:07:31] [main/INFO]: [CHAT] [Baritone] > mine stone
[19:07:31] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:07:31] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.cd.execute(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.cf.a(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.cf$$Lambda$699/1323741703.accept(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zei000(SourceFile)
[19:07:31] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[19:07:31] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[19:07:31] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[19:07:31] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[19:07:31] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[19:07:31] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[19:07:31] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[19:07:31] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[19:07:31] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[19:07:31] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:07:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:07:31] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:07:31] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:07:31] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:07:31] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:07:31] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:07:31] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.w.repack(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.w.repack(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	at baritone.bk.execute(Unknown Source)
[19:07:31] [main/INFO]: [STDERR]: 	... 24 more

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
Fill out the template.
