### ISSUE TITLE
Follow Entity Command Not Working

### ISSUE THREAD

**Issue by BMax-sudo** [cabaletta/baritone#2033]
Some information:
Operating system: Windows 10
Java version: Version 8
Minecraft version: 1.12.2 ForgeOptiFine
Baritone version: 4.5
Forge mods (if used): 

Exception, error or logs:

[18:36:01] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > follow entity sheep
[18:36:01] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_191308_b
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.a(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zej000(EntityPlayerSP.java)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:36:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldError: field_191308_b
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.ag.getDatatypeFor(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.bb.execute(Unknown Source)
[18:36:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 24 more

How to reproduce:
1. Open Chat
2. Write Command #follow entity sheep
3. Baritone gives error:
An unhandled exception ocurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

Modified settings:
All modified settings:
allowParkour (True)
allowParkourPlace (True)
chatControl (False)

Final checklist:
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment]
already fixed.

**Comment by BMax-sudo** [comment]
> 
> 
> already fixed.

But I just Installed Impact today and it happened right now

**Comment by dominikaaaa** [comment]
Impact is not using the latest version.

**Comment by dominikaaaa** [comment]
Impact Forge isn't officially supported either.
