### ISSUE TITLE
.follow entity  command can't be used on Inertia Client

### ISSUE THREAD

**Issue by ljm12914-1** [cabaletta/baritone#2065]
As the title says,when I typed ".b follow entity sheep" or ".b follow entity chicken" or everything else, it didn't work and asked me to report it on Github.So I'm here.The details in game log are here:
[23:28:17] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > follow entity donkey
[23:28:17] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_191308_b
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.a(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at inertia.EHBm.eAdv(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at inertia.jphK.awJh(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at inertia.QTto.JbBq(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$rpDE$zck000(EntityPlayerSP.java:1900)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:28:17] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchFieldError: field_191308_b
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.ag.getDatatypeFor(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.bb.execute(Unknown Source)
[23:28:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 26 more

**Comment by ljm12914-1** [comment]
btw I don't know how to add a tag.excuse me.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.
