### ISSUE TITLE
#Mine in 1.12.2 standalone mod doesn't work

### ISSUE THREAD

**Issue by TheNolle** [cabaletta/baritone#2089]
## Some information
Operating system: Windows 10 Pro 64bit
Java version: Java "15" 2020-09-15
Minecraft version: Forge 1.12.2
Baritone version: v1.2.14
Forge mods (if used): ReAuth, Bookshelf, OreLib, Clumps, Foam Fix, Vanilla Fix, BetterFPS, Optifine, Phosphore, Hwyla, Waila Harvestability, Better Advancements, Better Ping Display, Durability Viewer, Equipment Tooltip, No potion shift, Overloaded Armor Bar, Toughness Bar, Voxel Map, Baritone, Neat, No Nausea, No Night Vision Flashing, Smooth Water, Ding, Dynamic Surroundings, Sound Filters, Apple Skin, Better Placements, Enchantment Description, Inventory Tweaks, Mouse Tweaks.

## Exception, error or logs
__Latest.log:__ https://pastebin.com/nsjSK4CF
__Specific Error Section:__ https://pastebin.com/QKxrQdjT

## How to reproduce
Simply launch the game with the Baritone v1.2.14 standalone mod and execute the command **#mine** and a block ID *(example: **log**)*.
*(Path finding still works when doing #goto and a block ID)*

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
In your reproduction steps you failed to mention which mod is causing the issue. Please correct this and reopen.

**Comment by TheNolle** [comment]
I don't know what is causing this, I would like to know How I can check this so I can fix this error, if you can tell me of course

**Comment by TheNolle** [comment]
It doesn't crash my game actually, what it says exactly is:
**[Baritone] An unhandled exception occurred. The error is in your game's log, please report it at https://github.com/cabelatta/baritone/issues**

And in the game's log (starting from my command **#mine diamond_ore** it says:


```
[00:09:43] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > mine diamond_ore
[00:09:43] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: baritone.aw: java.lang.NullPointerException
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.he.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.hd.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.ey.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.ey.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.hf.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.hf$$Lambda$425/432285369.accept(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at baritone.hf.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$zcl000$sendChatMessage(EntityPlayerSP.java)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:09:43] [Client thread/INFO] [STDERR]: [baritone.aw:a:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:09:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[00:09:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.ex.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.gk.a(Unknown Source)
[00:09:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 26 more
```

**Comment by TheNolle** [comment]
So if you can tell me where I can find what you are asking me to add in the reproduction steps, It would really help me @l1ving

**Comment by l1ving** [comment]
>  I would like to know How I can check this so I can fix this error

Remove each mod 1 by 1 until it works

**Comment by TheNolle** [comment]
I'll try it right now, thank you

**Comment by TheNolle** [comment]
It seems like it is VanillaFix, but it's weird, with this mod it launchs perfectly but the automine doesn't work, and when I remove it my game doesn't launch at all and there is no crash reports

**Comment by TheNolle** [comment]
Ok problem resolved, it was VanillaFix, it was fixing things baritone needed (I think), thank you for helping and have a great day!

**Comment by l1ving** [comment]
Of course. VanillaFix should be called ForgeBreak, it's incompatible with a shit ton of mods
