### ISSUE TITLE
Unhandled exception issue with #follow entity command

### ISSUE THREAD

**Issue by term88nator** [cabaletta/baritone#2105]
So I just got the baritone api for 1.12.4 (1.12.2) And im using a client with the api and I typed the message #follow entity donkey and it said "An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues" So if you could help me solve this problem i would appreciate it thanks.

**Comment by l1ving** [comment]
This is a duplicate. Please search before creating an issue next time.

**Comment by term88nator** [comment]
I'm looking everywhere with the same problem but with no fix to the actual issue could you send me the link to the post that fixes the issue?

**Comment by l1ving** [comment]
Use the latest version of Baritone

**Comment by ZacSharp** [comment]
Freshly built on master@5a5d1192 (latest as of this writing) <details> <summary>screenshot</summary> ![screenshot](https://raw.githubusercontent.com/ZacSharp/uploads/master/cabaletta/baritone/issues/2105/2020-10-24_02.32.41.png) </details>
<details><summary>log</summary><pre>[02:32:08] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > follow entity chicken
[02:32:08] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_191308_b
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cc.execute(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.z.a(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.z.onSendChatMessage(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.a(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:32:08] [main/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NoSuchFieldError: field_191308_b
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.api.command.datatypes.EntityClassById.get(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.ah.getDatatypeFor(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.command.defaults.FollowCommand.execute(Unknown Source)
[02:32:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 23 more
</pre>

**Comment by l1ving** [comment]
Trolled. Make a proper bug report then

**Comment by ZacSharp** [comment]
No need, there is a pull (#1971) and 3 reports mentioned in it

**Comment by l1ving** [comment]
Oh I *thought* the pull was merged, which is why I said to use the latest version.
