### ISSUE TITLE
Baritone will calculate the path, but not actually move.

### ISSUE THREAD

**Issue by NotPetyaPog** [cabaletta/baritone#2179]
## Some information
Operating system: Windows 10
Java version: Latest
Minecraft version: Inertia Client 1.16.4
Baritone version:
Mods (if used): Inertia Client

## Exception, error or logs
It just spams this:
        java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException

## How to reproduce
No clue

## Modified settings
assumeWalkOnWater (Boolean)
chatControl (Boolean)
followRadius (Integer)

**Comment by l1ving** [comment]
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.
