### ISSUE TITLE
1.16.4 .json file results in error log

### ISSUE THREAD

**Issue by GameCenterJerry** [cabaletta/baritone#2187]
## Some info
Operating system: macOS
Java version: 12
Minecraft version: 1.16.4
Baritone version: 1.6.1
Forge mods (if used): N/A

As shown in Leiji's video (https://www.youtube.com/watch?v=_4eVJ9Qz2J8&ab_channel=LurfJurv), there IS a .json only file for Minecraft 1.16.2, but changing everything inside the .json file Leji provided that has "1.16.2" in it to "1.16.4" doesn't work and results in an error log.

### File after changing:
```
{
  "id": "1.16.4-Baritone",
  "type": "release",
  "inheritsFrom": "1.16.4",
  "jar": "1.16.4",
  "time": "2019-07-23T20:50:21Z",
  "releaseTime": "2019-07-23T20:50:21Z",
  "downloads": {},
  "minimumLauncherVersion": 0,
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "arguments": {
    "game": [
     "--tweakClass",
     "baritone.launch.BaritoneTweaker"
    ]
  },
  "libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    },
    {
      "name": "cabaletta:baritone-api:1.6",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "com.github.ImpactDevelopment:SimpleTweaker:1.2",
      "url": "https://impactdevelopment.github.io/maven/"
    },
    {
      "name": "org.spongepowered:mixin:0.7.11-SNAPSHOT",
      "url": "http://dl.liteloader.com/versions/"
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "url": "https://repo1.maven.org/maven2/"
    }
  ]
}
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
> results in an error log.

where?

**Comment by GameCenterJerry** [comment]
@l1ving 
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 17/11/20 12:32 PM
Description: Initializing game

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: djw
	at djz.<init>(SourceFile:434)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: djw
	... 8 more
Caused by: java.lang.ClassNotFoundException: djw
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinMinecraft] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field s was not located in the target class djw. Using refmap mixins.baritone.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at djz.<init>(SourceFile:434)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1358835264 bytes (1295 MB) / 1711276032 bytes (1632 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.4-Baritone
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by GameCenterJerry** [comment]
@l1ving 
took me many excruciating minutes but finally figured it out. 
1.16.5 JSON ONLY Baritone w Optifine. I will do a pull req
