### ISSUE TITLE
Baritone 1.12.2 no longer works at all.

### ISSUE THREAD

**Issue by me-rgb** [cabaletta/baritone#2222]
All versions of forge/baritone:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/29/20 12:12 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.hn
	at baritone.hn.b(Unknown Source)
	at baritone.ek.a(Unknown Source)
	at baritone.ek.a(Unknown Source)
	at baritone.hf.a(Unknown Source)
	at baritone.hf$$Lambda$187/1356749081.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.hf.a(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zzh000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.hn.b(Unknown Source)
	at baritone.ek.a(Unknown Source)
	at baritone.ek.a(Unknown Source)
	at baritone.hf.a(Unknown Source)
	at baritone.hf$$Lambda$187/1356749081.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.hf.a(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zzh000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['mememememe1'/13899, l='MpServer', x=8.50, y=65.00, z=8.50], EntityOtherPlayerMP['Kxwiz'/774, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['Tupinamba4'/787, l='MpServer', x=67.54, y=152.00, z=162.40], EntityOtherPlayerMP['_UberEats_'/13274, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['terjanq'/13825, l='MpServer', x=69.25, y=152.00, z=166.38], EntityOtherPlayerMP['jjisafag'/634, l='MpServer', x=69.54, y=3.00, z=145.53], EntityOtherPlayerMP['ZimStopAbusing'/11229, l='MpServer', x=71.68, y=2.00, z=145.30], EntityOtherPlayerMP['Keckinq'/9612, l='MpServer', x=79.19, y=3.25, z=158.30], EntityOtherPlayerMP['PineappleGod__'/1863, l='MpServer', x=69.30, y=3.00, z=145.70]]
	Chunk stats: MultiplayerChunkCache: 3, 3
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityPlayerSP['mememememe1'/13899, l='MpServer', x=8.50, y=65.00, z=8.50], EntityOtherPlayerMP['terjanq'/13825, l='MpServer', x=69.25, y=152.00, z=166.38], EntityOtherPlayerMP['Kxwiz'/774, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['Tupinamba4'/787, l='MpServer', x=67.54, y=152.00, z=162.40], EntityOtherPlayerMP['_UberEats_'/13274, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['terjanq'/13825, l='MpServer', x=69.25, y=152.00, z=166.38], EntityOtherPlayerMP['Kxwiz'/774, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['jjisafag'/634, l='MpServer', x=69.54, y=3.00, z=145.53], EntityOtherPlayerMP['ZimStopAbusing'/11229, l='MpServer', x=71.68, y=2.00, z=145.30], EntityOtherPlayerMP['PineappleGod__'/1863, l='MpServer', x=69.30, y=3.00, z=145.70], EntityOtherPlayerMP['Keckinq'/9612, l='MpServer', x=79.19, y=3.25, z=158.30], EntityOtherPlayerMP['PineappleGod__'/1863, l='MpServer', x=69.30, y=3.00, z=145.70], EntityOtherPlayerMP['Keckinq'/9612, l='MpServer', x=79.19, y=3.25, z=158.30], EntityEnderCrystal['entity.EnderCrystal.name'/79, l='MpServer', x=69.50, y=256.00, z=164.50], EntityOtherPlayerMP['Tupinamba4'/787, l='MpServer', x=67.54, y=152.00, z=162.40], EntityOtherPlayerMP['_UberEats_'/13274, l='MpServer', x=69.40, y=152.00, z=164.58], EntityOtherPlayerMP['jjisafag'/634, l='MpServer', x=69.54, y=3.00, z=145.53], EntityOtherPlayerMP['ZimStopAbusing'/11229, l='MpServer', x=71.68, y=2.00, z=145.30]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:a86e191:320) <- PaperBin
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 374052744 bytes (356 MB) / 603979776 bytes (576 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xverify:none -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.38' Renderer: 'GeForce RTX 2080 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by l1ving** [comment]
User error. Don't use noverify.
