### ISSUE TITLE
Mixin problem while creating a new mod

### ISSUE THREAD

**Issue by DontHUrTMe** [cabaletta/baritone#2228]
Operating system: Windows 10
Java version: 1.8.0 212
Minecraft version: 1.16.2
Baritone version: 1.6.1
Forge version: 33.0.61
Forge mods (if used): Only an empty mod, that i'm trying to write
## What do you need help with?
The minecraft client stops while loading, maybe you can find a version mismatch, or have some ideas why this doesnt work.
Im trying to create a custom mod, thats using baritone, but i fail to run with it. Please help. UwU.

[21:51:07] [main/FATAL] [mixin/]: Mixin apply failed mixins.baritone.json:MixinEntity -> net.minecraft.entity.Entity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_70177_z was not located in the target class net.minecraft.entity.Entity. Using refmap mixins.baritone.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_70177_z was not located in the target class net.minecraft.entity.Entity. Using refmap mixins.baritone.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135) ~[mixin-0.8.jar:0.8+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-7.0.1.jar:7.0.1+78+master.e9771d8] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:140) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:149) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:34) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:177) ~[modlauncher-7.0.1.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:99) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:59) ~[modlauncher-7.0.1.jar:?] {}
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1299) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1197) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:408) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:132) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-7.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_212] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-7.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
	at net.minecraft.client.main.Main.main(Main.java:118) ~[forge-1.16.2-33.0.61_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.16.2-33.0.61_mapped_snapshot_20200514-1.16-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.16.2-33.0.61_mapped_snapshot_20200514-1.16-recomp.jar:?] {}

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
> field field_70177_z was not located in the target class net.minecraft.entity.Entity. Using refmap mixins.baritone.refmap.json

You're mixing an obfuscated env and a non-obfuscated one. This isn't a Baritone issue, you should ask in the Minecraft Mod Development Discord or the Forge Discord

**Comment by DontHUrTMe** [comment]
I use the following package: "API: Only the non-api packages are obfuscated. This should be used in environments where other mods would like to use Baritone's features."

**Comment by DontHUrTMe** [comment]
I found this useful: https://github.com/cabaletta/baritone/issues/2040
