### ISSUE TITLE
Crashes game when #build command issued

### ISSUE THREAD

**Issue by andythoman** [cabaletta/baritone#2230]
## Some information
Operating system: windows 10 home
Java version: 1.8.0_65
Minecraft version: 1.16.4 with fabric-loader-0.10.6
Baritone version: 1.6.1
Forge mods (if used): I removed all fabric mods and tested, it still crashed.

## Exception, error or logs
[08:54:20] [main/INFO]: [CHAT] [Baritone] > build brewingMachine.schem
[08:54:20] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[08:54:20] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=1,y=65,z=2142}
[08:54:20] [main/INFO]: [CHAT] [Baritone] Starting layer 0
[08:54:21] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at baritone.process.BuilderProcess.valid(BuilderProcess.java:797) ~[baritone-1.6.1.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:481) ~[baritone-1.6.1.jar:?]
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:201) ~[baritone-1.6.1.jar:?]
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:90) ~[baritone-1.6.1.jar:?]
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:99) ~[baritone-1.6.1.jar:?]
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:61) ~[baritone-1.6.1.jar:?]
	at baritone.event.GameEventHandler$$Lambda$3067/2146410956.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_51]
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:61) ~[baritone-1.6.1.jar:?]
	at net.minecraft.class_310.handler$zeo000$runTick(class_310.java:5934) ~[intermediary-fabric-loader-0.10.6+build.214-1.16.4.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1525) ~[intermediary-fabric-loader-0.10.6+build.214-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-fabric-loader-0.10.6+build.214-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.10.6+build.214-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.10.6+build.214-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
[08:54:22] [main/INFO]: [STDOUT]: Minimap session finalized.

## How to reproduce
inventory is full of supplies needed.
Near a beacon with haste.
On an online server.
#build brewingMachine.schem

## Modified settings
allowInventory true
blockReachDistance 4
buildInLayers true

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Csquaredaap** [comment]
I had the same problem and i turned off allowinventory and for some weird reason it works just fine now....... i dont know why that is but try that

**Comment by ZacSharp** [comment]
Should not happen anymore since #3413 was merged.
