### ISSUE TITLE
When I use #build my game crashes

### ISSUE THREAD

**Issue by lalamapaka** [cabaletta/baritone#2231]
## Some information
Operating system: Mav
Java version: java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
Minecraft version: 1.16.4
Baritone version: 1.6.1
Forge mods (if used): 
Fabric mods: OptiFabric, CraftPresense, dontdropit, Time to live, Fabric API, malilib, Name Pain, Optifine, sheepconsitensy, Tweakeroo, litematica

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
latest: crash report:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/2/20 7:11 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.process.BuilderProcess.valid(BuilderProcess.java:797)
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:492)
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:201)
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:90)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:99)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:61)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:61)
	at net.minecraft.class_310.handler$zed000$runTick(class_310.java:5434)
	at net.minecraft.class_310.method_1574(class_310.java:1525)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.process.BuilderProcess.valid(BuilderProcess.java:797)
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:492)
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:201)
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:90)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:99)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:61)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:61)
	at net.minecraft.class_310.handler$zed000$runTick(class_310.java:5434)

-- Affected level --
Details:
	All players: 1 total; [class_746['lalamapaka'/3453, l='ClientLevel', x=208.56, y=91.00, z=201.72]]
	Chunk stats: Client Chunk Cache: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (13,79,-48), Chunk: (at 13,4,0 in 0,-3; contains blocks 0,0,-48 to 15,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 30256 game time, 1043 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 387038744 bytes (369 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		baritoe: Baritone 1.6.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		craftpresence: CraftPresence 1.7.5
		dontdropit: Don't Drop It! 2.1.0+1.16
		fabric: Fabric API 0.27.1+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		lionutils: LionUtils 6.0.1+1.16
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		optifabric: OptiFabric 1.8.10
		sheepconsistency: Sheep Consistency 1.0.2
		timetolive: Time To Live 0.2
		tweakeroo: Tweakeroo 0.10.0-dev.20201110.132827
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-16.0.49, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fast
	Resource Packs: vanilla, file/lalamapaka_recource_pack
	Current Language: English (United Kingdom)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-16.0.49
	OpenGlRenderer: Intel(R) Iris(TM) Graphics 6100
	OpenGlVendor: Intel Inc.
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /Users/obe/Library/Application Support/minecraft/.optifine/OptiFine_1.16.4_HD_U_G5/Optifine-mapped.jar
	OptiFabric error: <None>

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
#2230
