### ISSUE TITLE
Baritone Crashes When Trying to Render Chiseled Blocks

### ISSUE THREAD

**Issue by mthp1999** [cabaletta/baritone#2307]
When Baritone is installed and you try looking at a block that has been chiseled at all (From the Chisels & Bits mod) the game will crash. The Crash report is below, I can upload it in a different method if needed.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/28/20 1:13 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mod.chiselsandbits.helpers.ModUtil.getTileEntitySafely(ModUtil.java:289) ~[chiselsandbits:?] {re:classloading}
	at mod.chiselsandbits.chiseledblock.BlockChiseled.getTileEntity(BlockChiseled.java:167) ~[chiselsandbits:?] {re:classloading}
	at mod.chiselsandbits.chiseledblock.BlockChiseled.func_220071_b(BlockChiseled.java:364) ~[chiselsandbits:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:543) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:539) ~[?:?] {re:mixin,re:classloading}
	at baritone.ci.h(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.c(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.b(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.b(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.i.a(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.i.onTick(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.cc.a(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at baritone.cc.onTick(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zzh000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1448) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.15.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.chiselsandbits.helpers.ModUtil.getTileEntitySafely(ModUtil.java:289) ~[chiselsandbits:?] {re:classloading}
	at mod.chiselsandbits.chiseledblock.BlockChiseled.getTileEntity(BlockChiseled.java:167) ~[chiselsandbits:?] {re:classloading}
	at mod.chiselsandbits.chiseledblock.BlockChiseled.func_220071_b(BlockChiseled.java:364) ~[chiselsandbits:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:543) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:539) ~[?:?] {re:mixin,re:classloading}
	at baritone.ci.h(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.c(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.b(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.ci.b(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.i.a(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.i.onTick(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at baritone.cc.a(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at baritone.cc.onTick(Unknown Source) ~[baritoe:1.6.2] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zzh000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Matrix119'/355, l='ClientLevel', x=96.98, y=4.00, z=-182.39]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,4,-176), Chunk: (at 0,0,0 in 5,-11; contains blocks 80,0,-176 to 95,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 9788 game time, 9788 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.15.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1223544904 bytes (1166 MB) / 2347761664 bytes (2239 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.15.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.15
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.15-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		baritone-api-forge-1.6.2.jar                      |Baritone                      |baritoe                       |1.6.2               |DONE      |NOSIGNATURE
		structurize-0.13.100-RELEASE-universal.jar        |Structurize                   |structurize                   |0.13.100-RELEASE    |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3b.jar                         |Create                        |create                        |mc1.16.3_v0.3b      |DONE      |NOSIGNATURE
		chiselsandbits-0.2.8-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		buildinggadgets-3.7.2.jar                         |Building Gadgets              |buildinggadgets               |3.7.2               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.15-universal.jar                |Forge                         |forge                         |35.1.15             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-283.jar                                |Quark                         |quark                         |r2.4-283            |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
	Crash Report UUID: cf67d214-f978-42bb-a3e8-68c28d889d54
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7927, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

**Comment by l1ving** [comment]
lol

**Comment by leijurv** [comment]
lmao

**Comment by scorbett123** [comment]
Closing in favour of #2752.
