### ISSUE TITLE
Crash when running multiple instances on the same device

### ISSUE THREAD

**Issue by TudbuT** [cabaletta/baritone#2394]
[latest.log](https://github.com/cabaletta/baritone/files/5887068/latest.log)
## Some information
Operating system: Ubuntu 20.04
Java version: 1.8
Minecraft version: 1.12.2
Baritone version: Unknown, the one in Impact 4.9.1
Forge mods (if used): Impact, Optifine, TTC (Impact is the one with baritone, TTC does not have mixins or interfaces with the api)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

I know the problem: It starts saving the minecraft world, then it stops for some reason, then, after you close instance 2, a lock gets released and it continues. (
  Proof:
  ```
  [13:17:21] [pool-5-thread-3/INFO] [STDOUT]: [baritone.u:c:-1]: Started saving the world in a new thread
  [13:17:21] [Client thread/INFO] [STDOUT]: [baritone.v:a:-1]: Baritone world data dir: /home/tudbut/.minecraft/8b/./baritone/8b8t.xyz/DIM-1
  [13:17:21] [Client thread/INFO] [STDOUT]: [baritone.n:<init>:-1]: Cached world directory: /home/tudbut/.minecraft/8b/./baritone/8b8t.xyz/DIM-1/cache
  [13:17:21] [pool-5-thread-3/INFO] [STDOUT]: [baritone.m:a:-1]: Saving region 1,17 to disk /home/tudbut/.minecraft/8b/./baritone/8b8t.xyz/DIM1/cache
  [13:17:21] [pool-5-thread-4/INFO] [STDOUT]: [baritone.u:b:-1]: Started saving saved containers in a new thread
  [13:17:21] [Client thread/INFO] [STDOUT]: [baritone.t:<init>:-1]: Would save waypoints to /home/tudbut/.minecraft/8b/./baritone/8b8t.xyz/DIM-1/waypoints
  [ A WHOLE LOT OF: 
  [13:17:21] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
  java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
  Caused by: java.lang.NullPointerException
	at net.minecraft.scoreboard.Scoreboard.func_96519_k(SourceFile:178) ~[bhk.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147291_a(NetHandlerPlayClient.java:1929) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketScoreboardObjective.func_148833_a(SourceFile:54) ~[kj.class:?]
	at net.minecraft.network.play.server.SPacketScoreboardObjective.func_148833_a(SourceFile:10) ~[kj.class:?]
	at net.impactclient.31.run(31.java:7) ~[31.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 9 more ]
  [13:18:35] [pool-5-thread-3/INFO] [STDOUT]: [baritone.m:a:-1]: Saved region successfully
  ```
)
I'm 50% sure the world caching is the problem here!

## How to reproduce
1. Run minecraft with baritone
2. Run minecraft with baritone
3. One will lock up after ~5-20 mins
4. Close the other one
5. It works again

## Modified settings
Happens after resetting too.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue. UwU

**Comment by scorbett123** [comment]
This is a impact issue, from the log none of these null pointers originate from baritone, at least as far as I know, but impact isn't open source so I can't check for certain.

**Comment by TudbuT** [comment]
I already saw that, but when i saw that directly after it stops locking, it said "Region saved", so i thought i may be baritone

**Comment by scorbett123** [comment]
No, baritone just does that periodically, that is normal behaviour.

**Comment by TudbuT** [comment]
what i meant is that its INSTANTLY, DIRECTLY after

**Comment by TudbuT** [comment]
not just randomly - it may still be impact tho

**Comment by scorbett123** [comment]
baritone saves on crash, so in your log of course it says saved after it has crashed. However as I said before this could be to do with this, however the issue is in IMPACT, not in baritone. But idk what would cause this and don't have impact source to check.

**Comment by TudbuT** [comment]
Ok, im gonna close this then
