### ISSUE TITLE
Minecraft Freezing when running commands

### ISSUE THREAD

**Issue by AimHigher-boo** [cabaletta/baritone#2396]
I try to run commands my game will freeze and not let me tab out. Here is my log. 

IF THE ISSUE IS THERE BEING -noverify OR SOMETHING LIKE THAT THEN PLEASE TELL ME HOW TO DO IT. - *cries in newbie*

[10:29:44] [main/INFO]: Loading for game Minecraft 1.16.4
[10:29:45] [ForkJoinPool-1-worker-2/WARN]: The mod "inertia" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 7 column 9
- Unsupported root entry "initializers" at line 18 column 17
[10:29:45] [main/INFO]: [FabricLoader] Loading 5 mods: mm@2.0.1, minecraft@1.16.4, inertia@1.16.4, java@8, fabricloader@0.11.1
[10:29:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/balok/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[10:29:55] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:29:56] [main/INFO]: Setting user: BleachGoBrr
[10:29:56] [main/INFO]: Definitely not up to no good
[10:29:57] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[10:30:10] [main/INFO]: Narrator library for x64 successfully loaded
[10:30:10] [main/INFO]: Reloading ResourceManager: Default, Better+Leaves+Add-on+V2.3-1.16.zip, Tiny_Tools_1.16.zip
[10:30:11] [main/INFO]: [STDOUT]: Unable to parse line noverify on
[10:30:11] [main/INFO]: [STDERR]: java.lang.IllegalStateException: No setting by that name
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.parseAndApply(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.lambda$readAndApply$0(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil$$Lambda$2846/1692784612.accept(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.forEachLine(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.utils.SettingsUtil.readAndApply(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at baritone.api.BaritoneAPI.<clinit>(Unknown Source)
[10:30:11] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zej000$postInit(class_310.java)
[10:30:11] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:592)
[10:30:11] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[10:30:11] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:30:11] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:30:11] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:30:11] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:30:11] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[10:30:11] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[10:30:11] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[10:30:20] [main/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[10:30:20] [main/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[10:30:20] [main/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[10:30:21] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[10:30:21] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[10:30:21] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[10:30:21] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[10:30:21] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[10:30:21] [Via-Mappingloader-1/INFO]: Loading 1.16 -> 1.16.2 mappings...
[10:30:21] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[10:30:21] [main/INFO]: Loading translations...
[10:30:21] [main/INFO]: Registering protocols...
[10:30:21] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.12 mappings...
[10:30:21] [Via-Mappingloader-0/INFO]: Loading 1.13.2 -> 1.13 mappings...
[10:30:21] [Via-Mappingloader-0/INFO]: Loading 1.14 -> 1.13.2 mappings...
[10:30:22] [Via-Mappingloader-0/INFO]: Loading 1.15 -> 1.14 mappings...
[10:30:22] [Via-Mappingloader-0/INFO]: Loading 1.16 -> 1.15 mappings...
[10:30:22] [Via-Mappingloader-0/INFO]: Loading 1.16.2 -> 1.16 mappings...
[10:30:22] [ViaVersion-0/INFO]: ViaVersion detected server version: 1.16.4(754)
[10:30:22] [ViaVersion-0/INFO]: Shutting down mapping loader executor!
[10:30:22] [main/INFO]: OpenAL initialized.
[10:30:22] [main/INFO]: Sound engine started
[10:30:23] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[10:30:23] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10:30:23] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10:30:23] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10:30:23] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10:30:23] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10:30:23] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:30:23] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:30:23] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:30:23] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:30:35] [main/INFO]: Connecting to EPICGAMERSMP.shockbyte-server.com, 25565
[10:30:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:30:36] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com
[10:30:36] [main/INFO]: [STDOUT]: Cached world directory: C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:30:36] [main/INFO]: [STDOUT]: Would save waypoints to C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\waypoints
[10:30:36] [main/WARN]: Unknown custom packed identifier: minecraft:register
[10:30:37] [main/INFO]: [CHAT] BleachGoBrr joined the game
[10:30:37] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,-4 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:30:37] [main/INFO]: Loaded 584 advancements
[10:30:37] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 189ms
[10:30:37] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 1,-4 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:30:37] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 304ms
[10:30:38] [main/INFO]: [CHAT] Please, login with the command: /login <password>
[10:30:42] [main/INFO]: [CHAT] Please, login with the command: /login <password>
[10:30:44] [main/INFO]: [CHAT] Successful login!
[10:30:44] [main/INFO]: [CHAT] Welcome BleachGoBrr on Your Minecraft Server server
[10:30:44] [main/INFO]: [CHAT] 
[10:30:44] [main/INFO]: [CHAT] This server uses AuthMeReloaded protection!
[10:31:02] [main/INFO]: [CHAT] [Baritone] > mine diamond_ore
[10:31:02] [main/INFO]: Reloading ResourceManager: Default
[10:31:03] [main/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]
[10:31:03] [main/INFO]: [STDOUT]: Loading region 0,-5 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:03] [main/INFO]: [STDOUT]: Loaded region successfully in 83ms
[10:31:03] [main/INFO]: [STDOUT]: Loading region 0,-3 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:03] [main/INFO]: [STDOUT]: Loaded region successfully in 289ms
[10:31:03] [main/INFO]: [STDOUT]: Loading region 1,-5 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:03] [main/INFO]: [STDOUT]: Loaded region successfully in 57ms
[10:31:03] [main/INFO]: [STDOUT]: Loading region 1,-3 from disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:03] [main/INFO]: [STDOUT]: Loaded region successfully in 33ms
[10:31:06] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saving region 1,-4 to disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:06] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region 0,-4 to disk C:\Users\balok\AppData\Roaming\.minecraft\baritone\EPICGAMERSMP.shockbyte-server.com\cache
[10:31:06] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[10:31:06] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[10:31:06] [pool-3-thread-2/INFO]: [STDOUT]: World save took 239ms

I have tried baritone itself as well as clients but it does the same. This one is me using fabric and Inertia client. Running 1.16.4 let me know if you need anything else.

**Comment by AimHigher-boo** [comment]
**[10:30:11] [main/INFO]: [STDOUT]: Unable to parse line noverify on** Just read this line, I think I put it in my baritone config file but that didn't seem to change the result, let me know if you want a new log though

**Comment by l1ving** [comment]
Baritone is incompatible with noverify, and I have no idea what the hell you're doing to your config. 
General troubleshooting should either be done on the [Impact Discord](https://impactclient.net/discord) or you should open a [Bug Report](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
