### ISSUE TITLE
An unhandled exception occurred

### ISSUE THREAD

**Issue by NalCol** [cabaletta/baritone#2418]
## Some information
Operating system:Windows 10 20H2
Java version:1.8.0.281
Minecraft version:Forge 1.12.2
Baritone version:From Impact 4.9.1(Null version)
Forge mods (if used): Many optimization mods like BetterFPS

## Exception, error or logs
[23:47:34] [Client thread/INFO]: [CHAT] [Baritone] > mine diamond_ore
[23:47:34] [Client thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.a(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.65.0(65.java:2)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.65.0(65.java:11)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.6f.0(6f.java:43)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.4K.0(4K.java:47)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.4l.0(4l.java:24)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.impactclient.1X.post(1X.java:2)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.redirect$zcm000$sendChatPacket(EntityPlayerSP.java:1828)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java:303)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:47:34] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:47:34] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[23:47:34] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.w.repack(Unknown Source)
[23:47:34] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.w.repack(Unknown Source)
[23:47:34] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.bk.execute(Unknown Source)
[23:47:34] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 38 more
## How to reproduce
Not have exact step

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
uninstall other mods

**Comment by Ben1701A** [comment]
> uninstall other mods

Issue persists with Impact 4.9.1 (no mods). Should I create a new issue, or...
