### ISSUE TITLE
Unhandled exception occurred when trying to follow a player

### ISSUE THREAD

**Issue by SkimmerZ** [cabaletta/baritone#2500]
## Some information
Operating system: Windows 10
Java version:8
Minecraft version: 1.16.3
Baritone version: 1.6.3
Forge mods (if used): 

## Exception, error or logs
[22Feb2021 17:19:23.581] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, SkimmerZ, --version, 1.16.3-forge-34.1.34, --gameDir, C:\Users\windows10\AppData\Roaming\.minecraft, --assetsDir, C:\Users\windows10\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, ea4176b68d174ba0a6d4a16249b1c11b, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.34, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201025.185957]
[22Feb2021 17:19:23.583] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.5+84+master.3310fe0 starting: java version 1.8.0_51 by Oracle Corporation
[22Feb2021 17:19:23.781] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22Feb2021 17:19:23.806] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/windows10/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[22Feb2021 17:19:24.784] [main/ERROR] [mixin/]: Mixin config mixins.baritone.json does not specify "minVersion" property
[22Feb2021 17:19:24.834] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[22Feb2021 17:19:24.835] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [baritone.launch.BaritoneMixinConnector]
[22Feb2021 17:19:24.836] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.3-forge-34.1.34, --gameDir, C:\Users\windows10\AppData\Roaming\.minecraft, --assetsDir, C:\Users\windows10\AppData\Roaming\.minecraft\assets, --uuid, ea4176b68d174ba0a6d4a16249b1c11b, --username, SkimmerZ, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[22Feb2021 17:19:28.011] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[22Feb2021 17:19:28.015] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: SkimmerZ
[22Feb2021 17:19:28.099] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[22Feb2021 17:19:28.631] [modloading-worker-11/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 34.1.34, for MC 1.16.3 with MCP 20201025.185957
[22Feb2021 17:19:28.631] [modloading-worker-11/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v34.1.34 Initialized
[22Feb2021 17:19:28.928] [Render thread/WARN] [net.minecraft.resources.ResourcePackInfo/]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\windows10\AppData\Roaming\.minecraft\resourcepacks\Telly 60k Pack edit2.zip'
[22Feb2021 17:19:28.942] [Render thread/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack Fabric Mods from options because it doesn't seem to exist anymore
[22Feb2021 17:19:29.533] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[22Feb2021 17:19:29.574] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Default
[22Feb2021 17:19:29.599] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[22Feb2021 17:19:29.618] [Render thread/INFO] [STDOUT/]: [baritone.dw:a:-1]: Baritone settings file not found, resetting.
[22Feb2021 17:19:31.050] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: OUTDATED Current: 34.1.34 Target: 34.1.42
[22Feb2021 17:19:32.510] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[22Feb2021 17:19:32.512] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[22Feb2021 17:19:32.718] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22Feb2021 17:19:32.744] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22Feb2021 17:19:32.745] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22Feb2021 17:19:32.746] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22Feb2021 17:19:32.747] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22Feb2021 17:19:32.748] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22Feb2021 17:19:32.748] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22Feb2021 17:19:33.248] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22Feb2021 17:19:33.249] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22Feb2021 17:19:33.250] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22Feb2021 17:19:39.431] [Render thread/INFO] [net.minecraft.client.gui.screen.ConnectingScreen/]: Connecting to 34.87.145.211, 25565
[22Feb2021 17:19:40.153] [Netty Client IO #5/INFO] [net.minecraftforge.fml.network.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.
[22Feb2021 17:19:40.558] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[22Feb2021 17:19:40.567] [Render thread/INFO] [STDOUT/]: [baritone.ex:a:-1]: Baritone world data dir: C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211
[22Feb2021 17:19:40.569] [Render thread/INFO] [STDOUT/]: [baritone.ep:<init>:-1]: Cached world directory: C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\cache
[22Feb2021 17:19:40.570] [Render thread/INFO] [STDOUT/]: [baritone.ev:<init>:-1]: Would save waypoints to C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\waypoints
[22Feb2021 17:19:40.871] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Server] Welcome back, SkimmerZ
[22Feb2021 17:19:40.871] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Server whispers to you: Hey there, SkimmerZ!
[22Feb2021 17:19:40.872] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Server whispers to you: Welcome to The Hobbit Hole
[22Feb2021 17:19:40.888] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 606 advancements
[22Feb2021 17:19:40.913] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loading region -1,-2 from disk C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\cache
[22Feb2021 17:19:41.024] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loaded region successfully in 112ms
[22Feb2021 17:19:41.962] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loading region -2,-2 from disk C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\cache
[22Feb2021 17:19:41.980] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loaded region successfully in 18ms
[22Feb2021 17:19:42.204] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loading region -1,-1 from disk C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\cache
[22Feb2021 17:19:42.209] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loaded region successfully in 4ms
[22Feb2021 17:19:42.532] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loading region -2,-1 from disk C:\Users\windows10\AppData\Roaming\.minecraft\baritone\34.87.145.211\cache
[22Feb2021 17:19:42.534] [pool-4-thread-1/INFO] [STDOUT/]: [baritone.eo:b:-1]: Loaded region successfully in 1ms
[22Feb2021 17:19:44.628] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > help
[22Feb2021 17:19:44.629] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] All Baritone commands (clickable):
[22Feb2021 17:19:44.629] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] help - View all commands or help on specific ones
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] set - View or change settings
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] modified - List modified settings
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] reset - Reset all settings or just one
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] goal - Set or clear the goal
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] goto - Go to a coordinate or block
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] path - Start heading towards the goal
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] proc - View process state information
[22Feb2021 17:19:44.630] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] << | >> 1/5
[22Feb2021 17:19:50.294] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > follow player jajohall
[22Feb2021 17:19:50.296] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] Following these types of entities:
[22Feb2021 17:19:50.297] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[22Feb2021 17:19:50.297] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: baritone.ay: java.lang.NullPointerException
[22Feb2021 17:19:50.297] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hc.a(Unknown Source)
[22Feb2021 17:19:50.297] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hb.a(Unknown Source)
[22Feb2021 17:19:50.297] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.ez.a(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.ez.a(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hd.a(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hd$$Lambda$4800/1655397987.accept(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hd.a(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.entity.player.ClientPlayerEntity.handler$zza000$sendChatMessage(ClientPlayerEntity.java)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.entity.player.ClientPlayerEntity.func_71165_d(ClientPlayerEntity.java)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231159_b_(Screen.java:308)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231161_c_(Screen.java:297)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.ChatScreen.func_231046_a_(SourceFile:98)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$onKeyEvent$4(KeyboardListener.java:302)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener$$Lambda$4790/1277946450.run(Unknown Source)
[22Feb2021 17:19:50.298] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:391)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener$$Lambda$4780/1920846948.run(Unknown Source)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:390)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener$$Lambda$2866/109175108.invoke(Unknown Source)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:304)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:973)
[22Feb2021 17:19:50.299] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/209360767.call(Unknown Source)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[22Feb2021 17:19:50.300] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.command.defaults.FollowCommand$$Lambda$4814/935886796.apply(Unknown Source)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[22Feb2021 17:19:50.301] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22Feb2021 17:19:50.302] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[22Feb2021 17:19:50.302] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.command.defaults.FollowCommand.a(Unknown Source)
[22Feb2021 17:19:50.302] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 41 more
[22Feb2021 17:19:55.202] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

## How to reproduce
Log onto a server and type "follow player <username>"

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
This is a duplicate, however please make sure that you update to 1.6.5.

**Comment by scorbett123** [comment]
Wait, sorry, I thought that 1.6.5 was out, disregard my previous comment.

**Comment by l1ving** [comment]
It's still a duplicate of the million other follow issues
