### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Miniflint** [cabaletta/baritone#2547]
## Some information
Operating system: Windows 10. Pro Edition
Java version: Last version - (jre1.8.0_281)
Minecraft version: 1.16.5
Baritone version: baritone-standalone-fabric-1.6.3.jar
Forge mods (if used): None (fabric)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Windows: '%appdata%/.minecraft/logs/' :
[19:47:25] [main/INFO]: Loading for game Minecraft 1.16.5
[19:47:25] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16.5, java@8, fabricloader@0.11.2, baritone@1.6.3
[19:47:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Tristan/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[19:47:26] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/SodiumChunkManager)
[19:47:26] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable)
[19:47:34] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:47:35] [main/INFO]: Setting user: flintjunior
[19:47:36] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:47:40] [main/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_15267(class_3518.java:495) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:545) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:553) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:74) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:66) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3288.method_14456(class_3288.java:39) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:40) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:44) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:37) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:485) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:493) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	... 17 more
[19:47:40] [main/WARN]: Couldn't find pack meta for pack file/§3 Equinox Edited§3.zip
[19:47:42] [main/INFO]: Narrator library for x64 successfully loaded
[19:47:42] [main/INFO]: Reloading ResourceManager: Default
[19:47:47] [main/INFO]: OpenAL initialized.
[19:47:47] [main/INFO]: Sound engine started
[19:47:48] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:47:48] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:47:48] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:47:48] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:47:48] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:47:48] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:47:48] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:47:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:47:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:47:49] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:48:26] [pool-2-thread-3/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:48:45] [pool-2-thread-3/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:49:43] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:50:03] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:50:43] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:51:23] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:52:04] [pool-2-thread-3/ERROR]: Couldn't get trial availability
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21033(class_4341.java:380) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4365.method_21105(class_4360.java:255) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4365.run(class_4360.java:247) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:52:13] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:53:03] [pool-2-thread-2/ERROR]: Couldn't get trial availability
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21033(class_4341.java:380) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4365.method_21105(class_4360.java:255) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4365.run(class_4360.java:247) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:53:13] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:53:43] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:54:03] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:54:22] [pool-2-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:55:23] [pool-2-thread-2/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:442) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:324) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:319) ~[intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.method_21103(class_4360.java:235) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4360$class_4362.run(class_4360.java:228) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

## How to reproduce
I did some test :
every time i want to fill / walls using (pos1 + pos2) it crash

## Modified settings
allowInventory true
allowDownward false
allowParkour true
mobAvoidanceCoefficient 2.0

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Is it possible that you can put the log in a paste bin, it just makes it a lot nicer to view.

**Comment by Miniflint** [comment]
Yep, sorry :)
https://pastebin.com/72sX6Bjw
