### ISSUE TITLE
Help how do I add the baritone api to my client

### ISSUE THREAD

**Issue by wallhacks0** [cabaletta/baritone#2564]
I already tried adding
    compile 'com.github.cabaletta:baritone:1.2.14'
    compile 'cabaletta:baritone-api:1.2'
to my dependencies but it did not work did I forget anything?

**Comment by l1ving** [comment]
You'll have to be more specific than "it did not work"

**Comment by scorbett123** [comment]
Use an example of the correct implementation of it [here](https://github.com/kami-blue/client/blob/master/build.gradle#L158)

**Comment by l1ving** [comment]
Along with the Mixin registration, which depends on which platform you're running your utility mod on

**Comment by wallhacks0** [comment]
thanks I got it to correctly import. a small problem is that its now crashing future (It was not doing that before), Il try fix it myself first thanks!

**Comment by wallhacks0** [comment]
I am leaving this log here anyway in the hope someone knows whats going wrong its not giving any direct errors.
[10:50:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:50:18] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:50:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint
[10:50:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[10:50:21] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[10:50:21] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy
[10:50:21] [main/INFO] [FML]: Searching C:\Users\----\AppData\Roaming\.minecraft\mods for mods
[10:50:21] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from baritone-api-forge-1.2.14 (1).jar
[10:50:21] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from ConstHack.cc-b-0.1-release.jar
[10:50:21] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[10:50:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint
[10:50:33] [main/ERROR] [LaunchWrapper]: The jar file C:\Users\----\AppData\Roaming\.minecraft\libraries\net\futureclient\loader\1.0\loader-1.0.jar has a security seal for path org.spongepowered.asm.launch, but that path is defined and not secure
[10:50:33] [main/ERROR] [LaunchWrapper]: The jar file C:\Users\----\AppData\Roaming\.minecraft\libraries\net\futureclient\loader\1.0\loader-1.0.jar has a security seal for path org.spongepowered.asm.service, but that path is defined and not secure
[10:50:33] [main/ERROR] [LaunchWrapper]: The jar file C:\Users\----\AppData\Roaming\.minecraft\libraries\net\futureclient\loader\1.0\loader-1.0.jar has a security seal for path org.spongepowered.asm.service, but that path is defined and not secure
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap not a subtype
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.futureclient.loader.injector.Injector$$Lambda$1/1417126346.load_2$0(Unknown Source)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.futureclient.loader.injector.Injector$$Lambda$1/1417126346.load_2(Unknown Source)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.futureclient.loader.injector.Injector.load(wl)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at java.lang.invoke.MethodHandleImpl$BindCaller$T/40191541.invoke_V(MethodHandleImpl.java:1221)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.futureclient.loader.en.a(Unknown Source)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint.injectIntoClassLoader(ma:188)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:50:33] [main/INFO] [STDERR]: [net.futureclient.loader.injector.Injector$$Lambda$1/1417126346:load_2$0:201]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by l1ving** [comment]
> thanks I got it to correctly import. a small problem is that its now crashing future (It was not doing that before), Il try fix it myself first thanks!

Not an issue on Baritone's end

**Comment by fawwaz1234** [comment]
future works fine with baritone. what baritone version are you using?

**Comment by l1ving** [comment]
Depends on what Baritone / Mixin / Future version you're running
