### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by MrFast-js** [cabaletta/baritone#2623]
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): https://cdn.discordapp.com/attachments/672080192319127582/826604465301356564/ZoeHack.jar

## Exception, error or logs

[19:45:19] [Client thread/INFO] [STDOUT]: [me.ionar.salhack.CommandUtil:onChat:27]: .b path
19:45:19.180
[19:45:19] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
19:45:19.181
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
19:45:19.181
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
19:45:19.182
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
19:45:19.182
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at me.ionar.salhack.CommandUtil.onChat(CommandUtil.java:98)
19:45:19.182
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_CommandUtil_onChat_ClientChatEvent.invoke(.dynamic)
19:45:19.182
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraftforge.event.ForgeEventFactory.onClientSendMessage(ForgeEventFactory.java:436)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:416)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
19:45:19.183
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
19:45:19.184
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
19:45:19.184
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.w.repack(Unknown Source)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.w.repack(Unknown Source)
19:45:19.200
[19:45:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.bl.execute(Unknown Source)
19:45:19.201
[19:45:19] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 22 more

## How to reproduce
Im not sure? OwO

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment]
Salbug breaks Baritone
