### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Greeenman999** [cabaletta/baritone#2641]
## Some information
Operating system: Mac Os Big Sur
Java version: 1.8
Minecraft version: 1.16.4
Baritone version: 1.6.3
Forge mods (if used): 

- Apple Skin
- architectury
- autoreglib
- better f3
- biomes o plenty
- cloth-config
- clumps
- createmc
- createplus
- dynamicsurroundings
- fast leaf decay
- ftb-chunks
- ftb-giu-library
- ftb-ranks
- ftb-teams
- gravestone
- jei
- journeymap
- keystrokes mod
- light-overlay
- mixin bootstrap
- morpheus
- moustweaks
- optiforge
- pack menu
- placebo
- quark
- storagedrawers
- theoneprobe

## Exception, error or logs
 ---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 4/7/21 5:54 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.ku.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_74] {}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zzn000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1448) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.ku.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_74] {}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zzn000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 729, 204
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,67,144), Chunk: (at 0,4,0 in -6,9; contains blocks -96,0,144 to -81,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11214203 game time, 9215225 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 499358888 bytes (476 MB) / 2041577472 bytes (1947 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.6.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.36.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.6.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.6.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.36
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.36-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		ftb-ranks-1604.1.1.11.jar                         |FTB Ranks                     |ftbranks                      |1604.1.1.11         |DONE      |NOSIGNATURE
		BetterF3-1.1.2-forge-1.16.4.jar                   |BetterF3 Forge                |betterf3forge                 |1.1.2               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.73.jar                           |Just Enough Items             |jei                           |7.6.1.73            |DONE      |NOSIGNATURE
		OptiForge-MC1.16.4-0.4.6.jar                      |OptiForge                     |optiforge                     |0.4.6               |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1.jar                        |Create                        |create                        |mc1.16.5_v0.3.1+122 |DONE      |NOSIGNATURE
		gravestone-1.16.4-1.0.9.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.9        |DONE      |NOSIGNATURE
		Clumps-6.0.0.15.jar                               |Clumps                        |clumps                        |6.0.0.15            |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		keystrokesmod-1.1.1.jar                           |Array's Keystrokes Mod        |keystrokesmod                 |1.1.1               |DONE      |NOSIGNATURE
		architectury-1.9.132-forge.jar                    |Architectury                  |architectury                  |1.9.132             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		light-overlay-5.8.0.jar                           |Light Overlay                 |lightoverlay                  |5.8.0               |DONE      |NOSIGNATURE
		cloth-config-4.11.19-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.19             |DONE      |NOSIGNATURE
		baritone-standalone-forge-1.6.3.jar               |Baritone                      |baritoe                       |1.6.3               |DONE      |NOSIGNATURE
		ftb-teams-1604.1.0.16-forge.jar                   |FTB Teams                     |ftbteams                      |1604.1.0.16         |DONE      |NOSIGNATURE
		ftb-chunks-1605.2.3-build.71.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.71   |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-305.jar                                |Quark                         |quark                         |r2.4-305            |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.12.jar           |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.12     |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		PackMenu-1.16.4-2.4.0.jar                         |Pack Menu                     |packmenu                      |2.4.0               |DONE      |NOSIGNATURE
		createplus-1.16.4_v0.3.1.3.jar                    |Create Plus                   |createplus                    |1.16.4_v0.3.1.3     |DONE      |NOSIGNATURE
	Crash Report UUID: 9f30a755-9525-4b52-a542-da1928ed374e
	Launched Version: forge-35.1.36
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Apple M1 GL version 2.1 Metal - 71.0.7, Apple
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/VanillaTweaks_r746365.zip, packmenu, quark:emote_resources (incompatible)
	Current Language: English (US)
	CPU: 8x Apple M1
	OptiFine Version: OptiFine_1.16.4_HD_U_G7
	OptiFine Build: 20210221-012854
	Render Distance Chunks: 27
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 Metal - 71.0.7
	OpenGlRenderer: Apple M1
	OpenGlVendor: Apple
	CpuCount: 8

## How to reproduce
I've started Forge tryed to join my server an then it crashed whilst "loading terrain"

## Modified settings
To get the modified settings run `#modified` in game -> I cant join my server so i cant run #modified

## Final checklist

- [x ]  I know how to properly use check boxes 

- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

PS: I'm german, so sorry for my bad englisch :D

**Comment by l1ving** [comment]
try without other mods

**Comment by Greeenman999** [comment]
> try without other mods

its an modpack so difficulty haha
