### ISSUE TITLE
fail to launch baritone on 1.14.4 minecraft

### ISSUE THREAD

**Issue by afafw** [cabaletta/baritone#2674]
here are the logs
[14:37:08] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at io.github.impactdevelopment.simpletweaker.SimpleTweaker.doInitialSetup(SimpleTweaker.java:96)
	at io.github.impactdevelopment.simpletweaker.SimpleTweaker.injectIntoClassLoader(SimpleTweaker.java:57)
	at baritone.launch.BaritoneTweaker.injectIntoClassLoader(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more

PS: The baritone json seems like it needs an update too(at least the 1.14.4 version). Http is not supported anymore, if you failed to download asm, you can try to replace "http" with "https".

**Comment by l1ving** [comment]
Please fill out the issue template properly. 

Choose the appropriate one and fill out the requested information
- [**Bug**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=bug&template=bug.md)
- [**Suggestion**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=enhancement&template=suggestion.md)
- [**Question**](https://github.com/cabaletta/baritone/issues/new?assignees=&labels=question&template=question.md)
