### ISSUE TITLE
#mine Command not breaking blocks. v1.2.15, Minecraft 1.12.2.

### ISSUE THREAD

**Issue by Katsun** [cabaletta/baritone#2777]
Baritone isn't breaking blocks. 
INFO: 
I'm using Minecraft 1.12.2, and using the command '#mine block' it breaks.
A full list in the log reveals it's a nullPointerException

> [11:30:37] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > mine stone
[11:30:37] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: baritone.ax: java.lang.NullPointerException
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hh.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hg.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hi$$Lambda$483/2003943757.accept(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:30:37] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:30:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[11:30:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fb.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.gm.a(Unknown Source)
[11:30:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 26 more

My guess is that baritone isn't able to recognize block type in 1.12, or something similar. 
Weirdly enough, the error is some remedied when hopping to seperate servers, which is quite strange.

**Comment by scorbett123** [comment]
What block is this trying to mine and on what server?
