### ISSUE TITLE
got this error and was told to report

### ISSUE THREAD

**Issue by ionburger** [cabaletta/baritone#2793]
Operating system: windows 10
Java version: 8
Minecraft version: 1.16.5(meteor client)
Baritone version: not sure
Other mods (if used): 
got a error while trying to follow a player and was told to report here:

[10:17:03] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:145)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:70)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:70)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:70)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zeo000$sendChatMessage(class_746.java:2269)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:313)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:306)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:98)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:345)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:435)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:343)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:433)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:433)
[10:17:03] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[10:17:03] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[10:17:03] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[10:17:03] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:308)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1068)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[10:17:03] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[10:17:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[10:17:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[10:17:03] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[10:17:03] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:17:03] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:17:03] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand.execute(FollowCommand.java:82)
[10:17:03] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[10:17:03] [main/INFO]: [STDERR]: 	... 41 more

**Comment by scorbett123** [comment]
Can you send the full log file if possible please.

**Comment by ionburger** [comment]
deleted the original instance but reproducible by doing #follow player <ign> doesn't appear to happen when following self


[17:37:50] [main/INFO]: Loading for game Minecraft 1.16.5
[17:37:51] [main/INFO]: [FabricLoader] Loading 5 mods: minecraft@1.16.5, java@8, meteor-client@0.4.3, fabricloader@0.11.3, baritone@1.6.3
[17:37:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Program%20Files%20(x86)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:37:51] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[17:37:51] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache was not found meteor-client-sodium.mixins.json:SodiumBlockOcculsionCacheMixin
[17:37:51] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer)
[17:37:51] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer was not found meteor-client-sodium.mixins.json:SodiumBlockRendererMixin
[17:37:51] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer)
[17:37:51] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer was not found meteor-client-sodium.mixins.json:SodiumFluidRendererMixin
[17:37:51] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/SodiumChunkManager)
[17:37:51] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable)
[17:37:59] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:38:02] [main/INFO]: Setting user: ionburger
[17:38:03] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:38:22] [main/INFO]: Narrator library for x64 successfully loaded
[17:38:22] [main/INFO]: Reloading ResourceManager: Default
[17:38:22] [main/INFO]: Initializing Meteor Client
[17:38:24] [main/INFO]: Loading
[17:38:24] [main/INFO]: Loaded in 204 milliseconds
[17:38:26] [main/INFO]: OpenAL initialized.
[17:38:26] [main/INFO]: Sound engine started
[17:38:26] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:38:26] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:38:26] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:38:26] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:38:26] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:38:26] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:38:26] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/users/profiles/minecraft/ghnrfhzdtjhpztgpnjzdtgnfgyn
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.utils.network.HttpUtils.request(HttpUtils.java:39)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.utils.network.HttpUtils.get(HttpUtils.java:50)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.utils.network.HttpUtils.get(HttpUtils.java:77)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.systems.accounts.types.CrackedAccount.fetchHead(CrackedAccount.java:29)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.systems.accounts.Accounts.lambda$fromTag$0(Accounts.java:87)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.utils.misc.NbtUtils.listFromTag(NbtUtils.java:27)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at minegame159.meteorclient.systems.accounts.Accounts.lambda$fromTag$1(Accounts.java:71)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:38:26] [pool-4-thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[17:38:27] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:38:27] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:38:27] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:38:29] [main/INFO]: Checking latest version of Meteor Client
[17:38:53] [main/INFO]: Connecting to _dc-srv.69d1867ceec8._minecraft._tcp.anarchy.theluckymilkcrate.tk., 25561
[17:38:55] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:38:55] [main/INFO]: [STDOUT]: Baritone world data dir: C:\Program Files (x86)\MultiMC\instances\1.16.5\.minecraft\baritone\anarchy.theluckymilkcrate.tk
[17:38:55] [main/INFO]: [STDOUT]: Cached world directory: C:\Program Files (x86)\MultiMC\instances\1.16.5\.minecraft\baritone\anarchy.theluckymilkcrate.tk\cache
[17:38:55] [main/INFO]: [STDOUT]: Would save waypoints to C:\Program Files (x86)\MultiMC\instances\1.16.5\.minecraft\baritone\anarchy.theluckymilkcrate.tk\waypoints
[17:38:56] [main/INFO]: [CHAT] [DriveBackupV2] An update is available, get it here: http://bit.ly/2M14uVD
[17:38:56] [main/INFO]: [CHAT] ionburger joined the game
[17:38:56] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Program Files (x86)\MultiMC\instances\1.16.5\.minecraft\baritone\anarchy.theluckymilkcrate.tk\cache
[17:38:56] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 418ms
[17:38:57] [main/INFO]: Loaded 311 advancements
[17:39:13] [main/INFO]: [CHAT] [Baritone] > follow player ionburger
[17:39:13] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[17:39:13] [main/INFO]: [CHAT] [Baritone] class_746['ionburger'/3250, l='ClientLevel', x=-252.87, y=42.00, z=-224.80]
[17:39:21] [main/INFO]: [CHAT] [Baritone] > follow player skinnyduckracing'
[17:39:21] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[17:39:21] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:39:21] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:145)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.access$000(CommandManager.java:128)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:145)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:70)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:70)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:70)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zeo000$sendChatMessage(class_746.java:2269)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:313)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:306)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:98)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:345)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:435)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:343)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:433)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:433)
[17:39:21] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:39:21] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:39:21] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[17:39:21] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1071)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[17:39:21] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[17:39:21] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[17:39:21] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:39:21] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:39:21] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:39:21] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:39:21] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand.execute(FollowCommand.java:82)
[17:39:21] [main/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[17:39:21] [main/INFO]: [STDERR]: 	... 40 more
[17:39:25] [pool-3-thread-2/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Program Files (x86)\MultiMC\instances\1.16.5\.minecraft\baritone\anarchy.theluckymilkcrate.tk\cache
[17:39:25] [pool-3-thread-2/INFO]: [STDOUT]: Saved region successfully
[17:39:25] [pool-3-thread-2/INFO]: [STDOUT]: World save took 210ms
Clipboard copy at: 07 Jun 2021 17:39:53 -0600

**Comment by Flurrrr** [comment]
duplicate of #1926
