### ISSUE TITLE
baritone keeps crashiong for me with this eroor

### ISSUE THREAD

**Issue by REAPER077** [cabaletta/baritone#2873]
this is the crash report 
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/17/21 10:55 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.cl
	at baritone.cl.b(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$170/1350662065.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdg000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.cl.b(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$170/1350662065.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zdg000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['Nman33'/7096681, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['Waffles_400'/7096344, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['zack2606'/7096571, l='MpServer', x=0.00, y=121.50, z=0.00], EntityOtherPlayerMP['zb0b'/7050414, l='MpServer', x=0.00, y=121.50, z=0.00], EntityOtherPlayerMP['dazed680'/7096241, l='MpServer', x=-0.13, y=121.50, z=1.27], EntityOtherPlayerMP['NiklasJaMikael'/7091364, l='MpServer', x=-5.30, y=2.00, z=21.70], EntityOtherPlayerMP['Zikky666'/7059257, l='MpServer', x=-4.70, y=1.00, z=23.30], EntityOtherPlayerMP['NicoBolle'/7094770, l='MpServer', x=-24.31, y=3.92, z=12.88], EntityOtherPlayerMP['WoshEpitaph'/7090579, l='MpServer', x=-19.30, y=5.00, z=26.58]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,122,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12366 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityPlayerSP['Nman33'/7096681, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['Waffles_400'/7096344, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['zack2606'/7096571, l='MpServer', x=0.00, y=121.50, z=0.00], EntityOtherPlayerMP['zb0b'/7050414, l='MpServer', x=0.00, y=121.50, z=0.00], EntityOtherPlayerMP['dazed680'/7096241, l='MpServer', x=-0.13, y=121.50, z=1.27], EntityOtherPlayerMP['zb0b'/7050414, l='MpServer', x=0.00, y=121.50, z=0.00], EntityOtherPlayerMP['NiklasJaMikael'/7091364, l='MpServer', x=-5.30, y=2.00, z=21.70], EntityOtherPlayerMP['Zikky666'/7059257, l='MpServer', x=-4.70, y=1.00, z=23.30], EntityEnderCrystal['entity.EnderCrystal.name'/7096682, l='MpServer', x=-21.50, y=5.00, z=18.50], EntityOtherPlayerMP['NicoBolle'/7094770, l='MpServer', x=-24.31, y=3.92, z=12.88], EntityOtherPlayerMP['NiklasJaMikael'/7091364, l='MpServer', x=-5.30, y=2.00, z=21.70], EntityOtherPlayerMP['WoshEpitaph'/7090579, l='MpServer', x=-19.30, y=5.00, z=26.58], EntityOtherPlayerMP['Zikky666'/7059257, l='MpServer', x=-4.70, y=1.00, z=23.30], EntityOtherPlayerMP['Waffles_400'/7096344, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['zack2606'/7096571, l='MpServer', x=0.00, y=121.50, z=0.00], EntityEnderCrystal['entity.EnderCrystal.name'/7094836, l='MpServer', x=-8.50, y=3.00, z=-27.50], EntityOtherPlayerMP['dazed680'/7096241, l='MpServer', x=-0.13, y=121.50, z=1.27], EntityOtherPlayerMP['NicoBolle'/7094770, l='MpServer', x=-24.31, y=3.92, z=12.88], EntityOtherPlayerMP['WoshEpitaph'/7090579, l='MpServer', x=-19.30, y=5.00, z=26.58]]
	Retry entities: 0 total; []
	Server brand: Crystal (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 523199512 bytes (498 MB) / 939524096 bytes (896 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | kamiblue  | 2.04.01      | kamiblue-2.04.01.jar          | None                                     |

	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-2.04.01.jar)
  
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) G41 Express Chipset GL version 2.1.0 - Build 8.15.10.2413, Intel
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by ehylo** [comment]
Remove the `-Xverify:none` jvm flag
