### ISSUE TITLE
#build issue

### ISSUE THREAD

**Issue by SpringTec3D** [cabaletta/baritone#2932]
## Some information
Operating system:                  Windows 10 
Java version:                           1.8.0_51, Oracle Corporation
Minecraft version:                  1.16.4
Baritone version:                    baritone-api-fabric-1.6.3
Other mods (if used):             fabric-api-0.29.3+1.16
                                               fabric-carpet-1.16.4-1.4.22+v210113
                                               litematica-fabric-1.16.3-1.6
                                               MaLiLib-Fabric-1.16.3
                                               worldedit-mod-7.2.3
                                                Xaeros-Minimap-Fair-Play-1.16.2    (idek why that one is in the mod list, it doesn't even run with 
                                                                                                          fabric)

## Exception, error or logs
 
**Crash Report:**

---- Minecraft Crash Report ----
// You're mean.

Time: 12.08.21 09:14
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.i.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$3087/1738089531.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zdm000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1525)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.i.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$3087/1738089531.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zdm000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['Chemist1'/5480648, l='ClientLevel', x=-[RED], y=[RED], z=[RED]]]
	Chunk stats: Client Chunk Cache: 529, 359
	Level dimension: minecraft:overworld
	Level spawn location: World: (329,127,-3227), Chunk: (at 9,7,5 in 20,-202; contains blocks 320,0,-3232 to 335,255,-3217), Region: (0,-7; contains chunks 0,-224 to 31,-193, blocks 0,0,-3584 to 511,255,-3073)
	Level time: 38411 game time, 600582131 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4395467712 bytes (4191 MB) / 8959033344 bytes (8544 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.6.3
		carpet: Carpet Mod in Fabric 1.4.22
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		litematica: Litematica 0.0.0-dev.20210106.181551
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.4
		worldedit: WorldEdit 7.2.3+5680-135941e
	Launched Version: fabric-loader-0.11.1-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**latest.log copied from starting the build**

[09:10:28] [main/INFO]: [CHAT] [Baritone] > build TheRick_ServerOptimized.schem
[09:10:28] [main/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[09:10:28] [main/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=**[Redacted]**,y=**[Redacted**],z=**[Redacted]**}
[09:10:44] [main/INFO]: [CHAT] [Baritone] > pause
[09:10:44] [main/INFO]: [CHAT] [Baritone] Already paused
[09:10:48] [main/INFO]: [CHAT] [Baritone] > resume
[09:10:48] [main/INFO]: [CHAT] [Baritone] Resumed
[09:11:20] [main/INFO]: [CHAT] [Baritone] > pause
[09:11:20] [main/INFO]: [CHAT] [Baritone] Paused
[09:12:31] [main/INFO]: [CHAT] §lExcavation increased to §r§a§l791§r§f.
[09:13:20] [main/INFO]: [CHAT] [Baritone] > resume
[09:13:20] [main/INFO]: [CHAT] [Baritone] Resumed
[09:13:36] [main/INFO]: [CHAT] [Baritone] > pause
[09:13:36] [main/INFO]: [CHAT] [Baritone] Paused
[09:14:07] [main/INFO]: [CHAT] [Baritone] > resume
[09:14:07] [main/INFO]: [CHAT] [Baritone] Resumed
[09:14:07] [main/INFO]: [STDOUT]: FAR AWAY FROM PATH FOR 1 TICKS. Current distance: 99.48542486606996. Threshold: 2.0
[09:14:14] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at baritone.dy.a(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at baritone.dy.onTick(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at baritone.fu.a(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at baritone.i.onTick(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at baritone.cd.a(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at baritone.cd$$Lambda$3087/1738089531.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_51]
	at baritone.cd.onTick(Unknown Source) ~[baritone-api-fabric-1.6.3.jar:?]
	at net.minecraft.class_310.handler$zdm000$runTick(class_310.java) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1525) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]

## How to reproduce

I have no idea what might have caused this error so I will just explain what happened:

1) loaded the schematic for a relatively large building.litematic in Litematica 
2) built a part of the schematic manually
3) installed Baritone
4) turned the .litematic into a .schem by building the litematic and saving it as a .schem using worldedit
5) let Baritone build the .schem (on a server, if this is relevant)
6) Baritone builds the .schem for a few hours successfully 
7) Game crashes
8) Restart the build by issuing the #build command again at the start position
9) Baritone starts pathfinding again
10) Baritone breaks a block
11) crashes game again
12) tried resuming build at a different location. Baritone builds a bit, game crashes again
13) I have tried deleting the ./minecraft/baritone/[Servername]/cache   --doesn't help

## Modified settings

allowInventory true
acceptableThrowawayItems minecraft:stone
blocksToAvoidBreaking crafting_table,furnace,chest,trapped_chest,dark_oak_leaves,oak_leaves,vine
allowParkour true
avoidance true
chatControl false
freeLook false
legitMine true
desktopNotifications true

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
Two questions:
1. I don't expect litematica or worldedit to cause this, but carpet is nothing but changes to vanilla code and bugs should generally be reproduced with as few mods as possible, so could you please try doing so with only Baritone and fabric loader/Forge/Nothing and without any changed settings (unless you strictly need them of course)?
2. Could you please use the unoptimized baritone jar so the log contains readable class names?
