### ISSUE TITLE
Crash in forge 1.12.2

### ISSUE THREAD

**Issue by Peter1224** [cabaletta/baritone#2972]
## Some information
Operating system:
Java version: openj9
Minecraft version: 1.12.2 forge 14.23.5.2855
Baritone version: 1.2.15
Other mods (if used): 
the modpack of Enigmatica 2: Expert - E2E
## Exception, error or logs

[latest.log](https://github.com/cabaletta/baritone/files/7075409/latest.log)

## How to reproduce
start the game

## Modified settings
It's crash

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Peter1224** [comment]
the log

[16:28:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:28:43] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:28:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:28:43] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[16:28:43] [main/INFO] [FML]: Java is Eclipse OpenJ9 VM, version 1.8.0_302, running on Windows 10:amd64:10.0, installed at C:\Program Files\Semeru\jdk-8.0.302.8-openj9\jre
[16:28:43] [main/INFO] [FML]: Searching E:\MultiMC\instances\Enigmatica2Expert-1.81a\minecraft\mods for mods
[16:28:43] [main/INFO] [FML]: Searching E:\MultiMC\instances\Enigmatica2Expert-1.81a\minecraft\mods\1.12.2 for mods
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.12.2-1.7.0-221-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod AdvancedRocketryPlugin (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.23.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/INFO] [Astral Core]: [AstralCore] Initialized.
[16:28:43] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from baritone-api-forge-1.2.15.jar
[16:28:43] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Born+In+A+Barn+V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[16:28:43] [main/WARN] [FML]: The coremod io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimiterCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: The coremod ChunkGenLimiterCoremod (io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimiterCoremod) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in colytra-1.12.2-1.2.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod c4.colytra.asm.ColytraLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EntityCulling-1.12.2-2.0.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod EntityCullingPlugin (meldexun.entityculling.plugin.EntityCullingPlugin) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.11-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:43] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:43] [main/WARN] [FML]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[16:28:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64+dev.151.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[16:28:44] [main/WARN] [FML]: The coremod PluginLoader (kaptainwutax.memorytester.utility.PluginLoader) is not signed!
[16:28:44] [MemoryTesterThread/INFO] [STDOUT]: [kaptainwutax.memorytester.init.InitData:initializeConfigs:29]: DataConfig{MemoryTesterVersion, RecommendedMemoryAllocation, UseMenu, CrashWhenNotEnoughMemory, WindowIconDir} at config/MemoryTester/General.txt
[16:28:44] [MemoryTesterThread/INFO] [STDOUT]: [kaptainwutax.memorytester.init.InitData:initializeConfigs:29]: DataConfig{Header, Line1WhenOptimalMemory, Line1WhenNonoptimalMemory, ButtonStartText, ButtonStartBgColor, ButtonQuitText, ButtonQuitBgColor, BackgroundImageDir} at config/MemoryTester/Menu.txt
[16:28:44] [MemoryTesterThread/INFO] [STDOUT]: [kaptainwutax.memorytester.init.InitData:initializeConfigs:29]: DataConfig{InfoHeader, InfoLine1, InfoLine2, InfoFooter, RedirectLink, RedirectBgColor, BackgroundImageDir} at config/MemoryTester/Crash.txt
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.5.192.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5.jar
[16:28:44] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from particleculling-1.12.2-v1.0.1.jar
[16:28:44] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from performant-1.12.2-1.10.jar
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[16:28:44] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.79.jar
[16:28:44] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in TickDynamic-1.12.2-1.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:28:44] [main/WARN] [FML]: The coremod LoadingPlugin (com.wildex999.tickdynamic.LoadingPlugin) is not signed!
[16:28:44] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[16:28:44] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:28:44] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-forge-mc1.12.2-0.2.7-universal.jar
[16:28:44] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:28:44] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:28:44] [main/ERROR] [mixin]: Catching
org.spongepowered.asm.service.ServiceInitialisationException: ModLauncher is not available
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap.bootstrap(MixinServiceModLauncherBootstrap.java:52) ~[particleculling-1.12.2-v1.0.1.jar:?]
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:79) [baritone-api-forge-1.2.15.jar:1.2.15]
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72) [baritone-api-forge-1.2.15.jar:1.2.15]
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92) [baritone-api-forge-1.2.15.jar:1.2.15]
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102) [baritone-api-forge-1.2.15.jar:1.2.15]
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76) [baritone-api-forge-1.2.15.jar:1.2.15]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [baritone-api-forge-1.2.15.jar:1.2.15]
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) [?:1.8.0_302]
	at java.lang.Class.newInstance(Class.java:2062) [?:1.8.0_302]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[16:28:44] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/E:/MultiMC/instances/Enigmatica2Expert-1.81a/minecraft/mods/baritone-api-forge-1.2.15.jar Service=LaunchWrapper Env=CLIENT
[16:28:44] [main/WARN] [FML]: The coremod ParticleCullingLoadingPlugin (bl4ckscor3.mod.particleculling.ParticleCullingLoadingPlugin) is not signed!
[16:28:44] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[16:28:44] [main/WARN] [FML]: The coremod PerformantLoadingPlugin (com.performant.coremod.PerformantLoadingPlugin) is not signed!
[16:28:44] [main/INFO] [VanillaFix]: Initializing VanillaFix
[16:28:45] [main/INFO] [VanillaFix]: Initializing StacktraceDeobfuscator
[16:28:45] [main/INFO] [VanillaFix]: Found MCP method mappings: methods-stable_39.csv
[16:28:45] [main/INFO] [VanillaFix]: Done initializing StacktraceDeobfuscator
[16:28:45] [main/INFO] [VanillaFix]: Initializing Bug Fix Mixins
[16:28:45] [main/INFO] [VanillaFix]: Initializing Crash Fix Mixins
[16:28:45] [main/INFO] [VanillaFix]: Initializing Profiler Improvement Mixins
[16:28:45] [main/INFO] [VanillaFix]: Initializing Texture Fix Mixins
[16:28:45] [main/INFO] [VanillaFix]: Initializing Mod Support Mixins
[16:28:45] [main/WARN] [FML]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[16:28:45] [main/WARN] [FML]: The coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin) is not signed!
[16:28:45] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:28:45] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[16:28:45] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:28:45] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:28:45] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:28:45] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:28:45] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:28:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:28:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:28:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:28:45] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[16:28:45] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[16:28:45] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[16:28:45] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[16:28:45] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: E:\MultiMC\instances\Enigmatica2Expert-1.81a\minecraft\mods\OptiFine_1.12.2_HD_U_G5.jar
[16:28:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:28:46] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:28:46] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[16:28:46] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@e2bca570
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:28:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:28:46] [main/INFO] [Astral Core]: [AstralTransformer] Loading patches...
[16:28:46] [main/INFO] [Astral Core]: [AstralTransformer] Initialized! Loaded 14 class patches!
[16:28:47] [main/FATAL] [FML]: A CRITICAL PROBLEM OCCURRED INITIALIZING MINECRAFT - LIKELY YOU HAVE AN INCORRECT VERSION FOR THIS FML
[16:28:47] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:67) ~[forge-1.12.2-14.23.5.2855-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.Loader
	at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_302]
	at java.lang.Class.forName(Class.java:417) ~[?:1.8.0_302]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2855-universal.jar:?]
	... 10 more
[16:28:47] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[16:28:47] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:390)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exception in thread "main" net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:390)
	at org.multimc.EntryPoint.main(EntryPoint.java:38)

**Comment by rebane2001** [comment]
You're running an awful lot of mods, try removing them first and see what causes the issue.

**Comment by scorbett123** [comment]
Are you sure that you are using the correct FML version in the log it says::

`[16:28:47] [main/FATAL] [FML]: A CRITICAL PROBLEM OCCURRED INITIALIZING MINECRAFT - LIKELY YOU HAVE AN INCORRECT VERSION FOR THIS FML`

Anyway, this is an issue with another one of your mods, not baritone, but you can try removing them one by one to find which is causing this issue.

**Comment by ApeaSuperz** [comment]
Disabling VanillaFix and related mods will fix this problem.

**Comment by chucasor** [comment]
Solve my crash when removing environment mods, in my case the Dynamic Surroundings, maybe it solves the problem of some more!
