### ISSUE TITLE
[1.12.2] Crash from trying to drag/hold down box to select multiple blocks when using #click

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#2988]
## Some information
Operating system: Windows 10
Java version: latest for Java 8
Minecraft version: 1.12.2
Baritone version: 1.2.15
Other mods (if used): 
Just Enough Items (JEI) (by mezz)
ConnectedTexturesMod (by tterrag1098)
EverlastingAbilities-PotionCore (by kroeser)
Village Spawn Point (by Serilum)
Player Tracking Compass (by Serilum)
Spartan Weaponry (by ObliviousSpartan)
AppleSkin (by squeek502)
Doctor Who - Regeneration (by Suff99)
Mo' Bends (by iwoplaza)
Sit (by bl4ckscor3)
OreLib (by OreCruncher)
Wawla - What Are We Looking At (by DarkhaxDev)
Cyclops Core (by kroeser)
Spartan and Fire (by cbkovak)
LLibrary (by _ForgeUser11902522)
Auto Network Lib (by aurocosh)
Wings (by pau101)
Dragon Mounts 2 (DISCONTINUED) (by TheRPGAdventurer101)
Schematica (by Lunatrius)
LunatriusCore (by Lunatrius)
Patchouli (by Vazkii)
[Backport] 1.13 Water Mechanics [Bubble Columns] (by xFrah)
JourneyMap (by techbrew)
Divine Favor (by aurocosh)
Doggy Talents (by percivalalb)
No Recipe Book (by Seneschal_Luwin)
Fancy Block Particles (by TominoCZ)
EverlastingAbilities (by kroeser)
Spartan Shields (by ObliviousSpartan)
Astral Sorcery (by HellFirePvP)
Dynamic Surroundings: HUDs (by OreCruncher)
Netherite (by ShadowRapZA)
Additional Resources (by Portablejim)
Audio Death (by Portablejim)
CreativeCore (by CreativeMD)
Collective (by Serilum)
Potion Core (by Tmtravlr)
Baubles (by Azanor13)
Extra Arcane Knowledge (Electroblob's Wizardry) (by Ghostrider231_)
Extra Spells (Electroblob's Wizardry) (by meldexun)
Village Names (by AstroTibs)
Ice and Fire: Dragons (by alex_khaan)
Mouse Tweaks (by YaLTeR)
Shadowfacts' Forgelin (by ShadowfactsDev)
Hwyla (by TehNut)
EnhancedVisuals (by CreativeMD)
Electroblob's Wizardry (by Electroblob)

## Exception, error or logs

Crash report: 
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.6-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  CreativePatchingLoader (CreativeCore_v1.10.63_mc1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Regeneration (Regeneration-3.0.3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 9/8/21 9:51 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.ku
	at baritone.ku.a(Unknown Source)
	at baritone.ky.a(Unknown Source)
	at baritone.eo.a(Unknown Source)
	at baritone.hi.a(Unknown Source)
	at baritone.hi$$Lambda$1730/239481773.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.hi.a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.handler$renderWorldPass$zzf000(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1963)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.ku.a(Unknown Source)
	at baritone.ky.a(Unknown Source)
	at baritone.eo.a(Unknown Source)
	at baritone.hi.a(Unknown Source)
	at baritone.hi$$Lambda$1730/239481773.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.hi.a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.handler$renderWorldPass$zzf000(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1963)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Shibva_'/2, l='MpServer', x=75966.49, y=60.00, z=-111814.64]]
	Chunk stats: MultiplayerChunkCache: 2208, 2208
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (75893,60,-111769), Chunk: (at 5,3,7 in 4743,-6986; contains blocks 75888,0,-111776 to 75903,255,-111761), Region: (148,-219; contains chunks 4736,-7008 to 4767,-6977, blocks 75776,0,-112128 to 76287,255,-111617)
	Level time: 190586 game time, 1665231217 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityXPOrb['Experience Orb'/642, l='MpServer', x=75909.75, y=58.00, z=-111861.54], EntityPig['Pig'/647, l='MpServer', x=75898.45, y=57.00, z=-111834.64], EntityPig['Pig'/648, l='MpServer', x=75906.24, y=58.00, z=-111827.66], EntityPlayerSP['Shibva_'/2, l='MpServer', x=75966.49, y=60.00, z=-111814.64], EntityXPOrb['Experience Orb'/653, l='MpServer', x=75859.92, y=58.00, z=-111826.53], EntityPig['Pig'/655, l='MpServer', x=75898.53, y=57.00, z=-111763.10], EntityPig['Pig'/656, l='MpServer', x=75898.61, y=57.00, z=-111760.94], EntityPig['Pig'/657, l='MpServer', x=75898.55, y=57.00, z=-111766.02], EntityPig['Pig'/658, l='MpServer', x=75898.45, y=57.00, z=-111767.01], EntityPig['Pig'/659, l='MpServer', x=75899.50, y=57.00, z=-111768.40], EntityPig['Pig'/660, l='MpServer', x=75899.55, y=57.00, z=-111760.45], EntityPig['Pig'/661, l='MpServer', x=75898.45, y=57.00, z=-111768.25], EntityPig['Pig'/663, l='MpServer', x=75899.50, y=57.00, z=-111767.39], EntityPig['Pig'/665, l='MpServer', x=75898.45, y=57.00, z=-111764.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3395426144 bytes (3238 MB) / 5536481280 bytes (5280 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 59 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version             | Source                                                | Signature                                |
	|:------ |:--------------------- |:------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2              | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                   | 9.42                | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                   | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | additionalresources   | 0.1.1               | additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar | None                                     |
	| LCHIJA | creativecoredummy     | 1.0.0               | minecraft.jar                                         | None                                     |
	| LCHIJA | jei                   | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LCHIJA | appleskin             | 1.0.14              | AppleSkin-mc1.12-1.0.14.jar                           | None                                     |
	| LCHIJA | baubles               | 1.5.2               | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCHIJA | astralsorcery         | 1.10.27             | astralsorcery-1.12.2-1.10.27.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | audiodeath            | 0.7.0_1.9-87aeca7   | audiodeath-1.9-0.7.0.50+87aeca7.jar                   | None                                     |
	| LCHIJA | autonetworklib        | 1.0.45              | autonetworklib-1.12.2-1.0.45.jar                      | None                                     |
	| LCHIJA | collective            | 2.60                | collective-1.12.2-2.60.jar                            | None                                     |
	| LCHIJA | creativecore          | 1.10.0              | CreativeCore_v1.10.63_mc1.12.2.jar                    | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| LCHIJA | cyclopscore           | 1.6.7               | CyclopsCore-1.12.2-1.6.7.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | patchouli             | 1.0-22              | Patchouli-1.0-22.jar                                  | None                                     |
	| LCHIJA | divinefavor           | 1.0.754             | divinefavor-1.0.754.jar                               | None                                     |
	| LCHIJA | doggytalents          | 1.15.1.6            | DoggyTalents-1.12.2-1.15.1.6.jar                      | None                                     |
	| LCHIJA | dragonmounts          | 1.12.2-1.6.3        | DragonMounts2-1.12.2-1.6.3.jar                        | None                                     |
	| LCHIJA | ebwizardry            | 4.3.4               | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| LCHIJA | enhancedvisuals       | 1.3.0               | EnhancedVisuals_v1.4.1_mc1.12.2.jar                   | None                                     |
	| LCHIJA | everlastingabilities  | 1.5.3               | EverlastingAbilities-1.12.2-1.5.3.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | potioncore            | 1.9_for_1.12.2      | PotionCore-1.9_for_1.12.2.jar                         | None                                     |
	| LCHIJA | eapotioncore          | 1.0.2               | EverlastingAbilities-PotionCore-1.12.2-1.0.2.jar      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | extra_spells          | 1.2.0               | ExtraSpells-1.12.2-1.2.0.jar                          | None                                     |
	| LCHIJA | fbp                   | 2.4.1               | FancyBlockParticles-1.12.x-2.4.1.jar                  | None                                     |
	| LCHIJA | forgelin              | 1.8.4               | Forgelin-1.8.4.jar                                    | None                                     |
	| LCHIJA | ghostspells           | 0.7-alpha           | Ghostspells-0.7-alpha.jar                             | None                                     |
	| LCHIJA | hbm                   | hbm-1.4.4A-1.12.2   | hbm-1.4.4a.jar                                        | None                                     |
	| LCHIJA | waila                 | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LCHIJA | llibrary              | 1.7.20              | llibrary-1.7.20-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.9.1               | iceandfire-1.9.1-1.12.2.jar                           | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1        | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| LCHIJA | lunatriuscore         | 1.2.0.42            | LunatriusCore-1.12.2-1.2.0.42-universal.jar           | None                                     |
	| LCHIJA | mobends               | 1.0.0-beta-20.06.20 | MoBends_1_12_2.jar                                    | None                                     |
	| LCHIJA | mousetweaks           | 2.10                | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	| LCHIJA | netherite1_12_2       | 1.1                 | Netherite1.12.2.jar                                   | None                                     |
	| LCHIJA | norecipebook          | 1.2.1               | noRecipeBook_v1.2.2formc1.12.2.jar                    | None                                     |
	| LCHIJA | playertrackingcompass | 1.6                 | playertrackingcompass_1.12.2-1.6.jar                  | None                                     |
	| LCHIJA | regeneration          | 3.0.3               | Regeneration-3.0.3.jar                                | None                                     |
	| LCHIJA | schematica            | 1.8.0.169           | Schematica-1.12.2-1.8.0.169-universal.jar             | None                                     |
	| LCHIJA | geckolib3             | 1.0                 | SchnurriTV's Sexmod - 1.1.jar                         | None                                     |
	| LCHIJA | sit                   | v1.3                | sit-1.12.2-v1.3.jar                                   | None                                     |
	| LCHIJA | spartanweaponry       | beta 1.3.8          | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	| LCHIJA | spartanfire           | 0.08                | spartanfire-0.08.jar                                  | None                                     |
	| LCHIJA | spartanshields        | 1.5.4               | SpartanShields-1.12.2-1.5.4.jar                       | None                                     |
	| LCHIJA | villagenames          | 4.3.4b              | VillageNames-1.12.2-4.3.4b.jar                        | None                                     |
	| LCHIJA | villagespawnpoint     | 1.5                 | villagespawnpoint_1.12.2-1.5.jar                      | None                                     |
	| LCHIJA | 113_water_mechanics   | 1.0.2               | WaterMechanicsBackport-1.0.3-1.12.2-NETHERFIX.jar     | None                                     |
	| LCHIJA | wawla                 | 2.6.275             | Wawla-1.12.2-2.6.275.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wings                 | 1.1.6               | wings-1.1.6-1.12.2.jar                                | None                                     |
	| LCHIJA | bauble_wings          | 1.0.0               | wings-1.1.6-1.12.2.jar                                | None                                     |
	| LCHIJA | ancientspellcraft     | 1.12.2-1.2.0.35     | ancientspellcraft-1.12.2-1.2.0.35.jar                 | None                                     |
	| LCHIJA | orelib                | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dshuds                | 3.6.0.0             | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UD     | mowzies_wings         | 1.0.0               | wings-1.1.6-1.12.2.jar                                | None                                     |
	| UD     | mobends_wings         | 1.0.0               | wings-1.1.6-1.12.2.jar                                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.63_mc1.12.2.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Regeneration (Regeneration-3.0.3.jar)
  me.suff.mc.regen.asm.RegenClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.68' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.68, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: DoggyTalent - Dogs - 1.12.2 v1.3.1.zip, F32-1.12.2.zip, Faithful 1.12.2-rv4, Lich's 3D Wands.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 23
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.68
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
![image](https://user-images.githubusercontent.com/38770780/132610520-ca460688-b9e2-48a5-add4-1de6b606ac42.png)
![image](https://user-images.githubusercontent.com/38770780/132610547-bdbaaee9-9403-42d5-a77b-67f40bc20197.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment]
Seems like the issue with no verify, but can't see the tag, can you check if you have it, or an equivalent installed?

**Comment by SteamDoge9000** [comment]
yes, but how would I do that, im still new to baritone
Can you please walk me though with what you mean?. Apologizes for my lack of understanding.

**Comment by scorbett123** [comment]
This would be a jvm argument that you have added, if you haven't then this is a different issue

**Comment by SteamDoge9000** [comment]
ah, of course

-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Allowcaed ram is around 10-12gb

Using a curseforge mod-management system

**Comment by SteamDoge9000** [comment]
fixed the title

**Comment by SteamDoge9000** [comment]
This issue seems to be a repost of #2865's issue. Maybe this can be the more info it needs

**Comment by scorbett123** [comment]
Closing in preference of #2865, it has less mods installed and now provides all the required information
