### ISSUE TITLE
Bug when i try to follow someone

### ISSUE THREAD

**Issue by mei2011** [cabaletta/baritone#2994]
## Some information
Operating system: Windows 10
Java version: azul zulu java runtime enviroment 8
Minecraft version: 1.12.2
Baritone version: 1.2.15
Other mods (if used): AutoPickup, ConsleHUD, Aristois Client for Forge and optifine

occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: baritone.ax: java.lang.NullPointerException
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hh.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hg.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:18:31] [Client thread/INFO] [STDERR]: [baritone.ax:a:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NullPointerException
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.command.defaults.FollowCommand.a(Unknown Source)
[19:18:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 33 more

## How to reproduce
follow a player

## Modified settings
To get the modified settings run `#modified` in game

none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
- why would i use "uwu"

**Comment by ZacSharp** [comment]
Is the player actually in render distance?

**Comment by mei2011** [comment]
No i didnt know they have to be. Thanks
