### ISSUE TITLE
Help tyring to locate a baritone 1.16.5 version that works wtih Immersive Portals [Forge issue]

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3016]
## What do you need help with?
I need help trying to find a download that will allow for immersive portals to run without baritone not being able to move and the only one I found does not have a relaease that can be done and moreover seems to be for 1.15.3

Some assistance would be apreciated

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by SteamDoge9000** [comment]
again, sorry about earlier

**Comment by SteamDoge9000** [comment]
probaly should have added that this was for forge so if it was fixed on fabric it hasent been yet for forge

**Comment by ehylo** [comment]
you would need to port the fix from the 1.15.2 branch that it is on to 1.16.5 and then build it yourself, there is no built version of it just floating around currently

**Comment by SteamDoge9000** [comment]
oh I tired

**Comment by SteamDoge9000** [comment]
I cant compile it for some reason

**Comment by ZacSharp** [comment]
What did you do to compile it?

**Comment by ZacSharp** [comment]
How did you run it? Double clicking some file is not what you need.
You need a shell so you can pass the extra arguments to gradle and I can't help you on how to get the shell, I can just give you the command again `gradlew build -Pbaritone.forge_build`. Just double clicking gradlew.bat should be equal to running `gradlew` which is the same as `gradlew help` and not what you need.

**Comment by SteamDoge9000** [comment]
nope I included that and it still gave me the same error

**Comment by SteamDoge9000** [comment]
can you try to compile the ImmersivePortalFix that you gave me the link to and see if your able to compile it?

**Comment by ehylo** [comment]
I tried compiling the branch myself and with the right commands and stuff it seems the branch does not compile, its because theres a + in the dependencies somewhere and that requires java 16 when baritone needs 8, changing it to a 1 fixed it, anyway here are the jars 
[baritone-unoptimized-forge-1.6.3](https://cdn.discordapp.com/attachments/819449117561585704/895867689011118131/baritone-unoptimized-forge-1.6.3.jar)
[baritone-api-forge-1.6.3](https://cdn.discordapp.com/attachments/819449117561585704/895867692484026378/baritone-api-forge-1.6.3.jar)
[baritone-standalone-forge-1.6.3](https://cdn.discordapp.com/attachments/819449117561585704/895867690093256724/baritone-standalone-forge-1.6.3.jar)

**Comment by SteamDoge9000** [comment]
ok, I tried plugging it in and I got this yeeted at me

```org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at com.qouteall.immersive_portals.ModMainClient.init(ModMainClient.java:104) ~[?:0.16-mc1.16.5-forge] {re:mixin,re:classloading}
	at com.qouteall.hiding_in_the_bushes.ModMainForge.lambda$doClientStuff$2(ModMainForge.java:132) ~[?:0.16-mc1.16.5-forge] {re:classloading,re:mixin}
	at com.qouteall.hiding_in_the_bushes.ModMainForge$$Lambda$21750/1296986777.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.timecore.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.timecore.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/56840345.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinImmersivePortalsChunkProvicer] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	... 31 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Conflicting opcodes UNKNOWN and UNKNOWN at offset 1 in synthetic bridge method func_212849_a_(IILnet/minecraft/world/chunk/ChunkStatus;Z)Lnet/minecraft/world/chunk/IChunk;
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachUniqueMethod(MixinPreProcessorStandard.java:557) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:341) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	... 31 more```

**Comment by SteamDoge9000** [comment]
thanks, but that was the immersiveportalsfix 1.16 

a value was changed because of a statement that was something only in java 16 and the value was replaced with a 1 instead of a + on the build.gradle I guess the right question to ask rn is what mixin would it be or If someone wtih java 16 could compile the build (due to me having some issues currently trying to compile the thing on my computer)

**Comment by wagyourtail** [comment]
https://github.com/wagyourtail/baritone/actions/runs/1320977237

**Comment by SteamDoge9000** [comment]
on your respertoy I mean

**Comment by wagyourtail** [comment]
wait no, that one's broke with the newest version of 1.16 ip, i tested with an older version...

**Comment by SteamDoge9000** [comment]
ah

**Comment by SteamDoge9000** [comment]
though quick question, is there currenty no way to mine modded ores using #2535

**Comment by ZacSharp** [comment]
Why should that be any different from the official versions?
You just use `#mine modid:blockname` as usual.

**Comment by SteamDoge9000** [comment]
idk, I do have Dynamic Trees. thats the only thing I know that might have irregular shapes
ill sent a irrelivennt crash report of me donig a forced game crash to provide context to what mods are present, maybe one of them will stand out to zall

**Comment by ZacSharp** [comment]
Dynamic trees sounds like it is the cause.

**Comment by SteamDoge9000** [comment]
wonder what it will take for some compat to be added? oh well not worried about it for now, I can remove it
