### ISSUE TITLE
java.lang.IncompatibleClassChangeError was thrown when i move around the world.

### ISSUE THREAD

**Issue by xiguajerry** [cabaletta/baritone#3075]
## Some information
Operating system: Windows 11
Java version: 1.8.0_202
Minecraft version: 1.12.2
Baritone version: 1.2.15
Other mods (if used): HyperLethal(utility mod), Pyro(utility mod), Stay(utility mod)

## Exception, error or logs
StackTrace:
java.lang.IncompatibleClassChangeError: Expected non-static field baritone.api.utils.BetterBlockPos.field_177990_b
	at baritone.k.a(Unknown Source) ~[k.class:?]
	at baritone.k.onTick(Unknown Source) ~[k.class:?]
	at baritone.cf.a(Unknown Source) ~[cf.class:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_251]
	at baritone.cf.onTick(Unknown Source) ~[cf.class:?]
	at net.minecraft.client.Minecraft.handler$runTick$zbh000(Minecraft.java) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

## How to reproduce
1.Enter a world
2.Use a module called Step
3.Use the module to climb over a block

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
1. Can you remove the clients not needed to reproduce this?
2. Clients often use bytecode manipulation to inject code for their hacks into minecraft code, so it's probably just one of the clients doing a change that does not work with Baritone subclassing BlockPos. In that case this issue is the fault of the client and not Baritone.
