### ISSUE TITLE
Baritone crashes after trying to path something

### ISSUE THREAD

**Issue by Xtreme678** [cabaletta/baritone#3116]
## Some information
Operating system: Windows 
Java version: 8
Minecraft version: 1.18
Baritone version: 1.18?
Other mods (if used): Iris and Sodium and Mathax

## Exception, error or logs
---- Minecraft Crash Report ----
// You're mean.

Time: 12/5/21, 4:23 PM
Description: Unexpected error

java.lang.IllegalArgumentException: fromIndex(50) > toIndex(17)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at java.base/java.util.Collections$UnmodifiableRandomAccessList.subList(Collections.java:1439)
	at baritone.pathing.path.CutoffPath.<init>(Unknown Source)
	at baritone.pathing.path.PathExecutor.a(Unknown Source)
	at baritone.pathing.path.PathExecutor.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1720)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at java.base/java.util.Collections$UnmodifiableRandomAccessList.subList(Collections.java:1439)
	at baritone.pathing.path.CutoffPath.<init>(Unknown Source)
	at baritone.pathing.path.PathExecutor.a(Unknown Source)
	at baritone.pathing.path.PathExecutor.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['oTysxn'/139, l='ClientLevel', x=4746.54, y=69.00, z=-5977.12]]
	Chunk stats: 1024, 474
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,72,-16), Section: (at 0,8,0 in 1,4,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 204104 game time, 74578 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 643631792 bytes (613 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18800.63
	Virtual memory used (MB): 14888.08
	Swap memory total (MB): 2465.54
	Swap memory used (MB): 98.59
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.8-1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	CPU: 6x AMD Ryzen 5 3500X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['oTysxn'/139, l='ServerLevel[asdasdsada]', x=4746.54, y=69.00, z=-5977.12]]
	Data Packs: vanilla

--- MatHax Legacy ---
Version: v1.6.4

[Movement]:
Sprint (sprint)

[Render]:
Background (background)
Nametags (nametags)

[Misc]:
Inventory Tweaks (inventory-tweaks)

[Client]:
Middle Click Friend (middle-click-friend)

## How to reproduce
Use anything that needs pathing in Baritone

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by Clausable** [comment]
one of your mods is probably conflicting with baritone.
