### ISSUE TITLE
Just trying to use with replay mod!

### ISSUE THREAD

**Issue by ejsupernova** [cabaletta/baritone#3174]
---- Minecraft Crash Report ----
// You're mean.

Time: 3/01/22 8:34 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.ea.desiredState(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.i.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$3095/1113321384.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1525)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.ea.desiredState(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.ee.a(Unknown Source)
	at baritone.dy.a(Unknown Source)
	at baritone.dy.onTick(Unknown Source)
	at baritone.fu.a(Unknown Source)
	at baritone.i.onTick(Unknown Source)
	at baritone.cd.a(Unknown Source)
	at baritone.cd$$Lambda$3095/1113321384.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cd.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['########'/183, l='ClientLevel', x=202.62, y=64.00, z=202.56]]
	Chunk stats: Client Chunk Cache: 529, 341
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,68,162), Chunk: (at 0,4,2 in 14,10; contains blocks 224,0,160 to 239,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 422458 game time, 422458 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1085288240 bytes (1035 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.6.3
		fabric: Fabric API 0.41.3+1.16
		fabric-api-base: Fabric API Base 0.3.0+f74f7c7d7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+f74f7c7d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+c16be54b7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+f74f7c7d7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+f74f7c7d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.7+c16be54b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+77df1b337d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+35ff49a47d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+f74f7c7d7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ede6dcf77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+f74f7c7d7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+f74f7c7d7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+f74f7c7d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+f74f7c7d7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+9385714e7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f74f7c7d7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+f74f7c7d7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4579bd497d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+f74f7c7d7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+f74f7c7d7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+f74f7c7d7d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+c16be54b7d
		fabricloader: Fabric Loader 0.12.12
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		replaymod: Replay Mod 1.16.4-2.6.3
		worldedit: WorldEdit 7.2.5+57d5ac9
	Launched Version: fabric-loader-0.12.12-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: #######################
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by ejsupernova** [comment]
Can someone help?

**Comment by wagyourtail** [comment]
duplicate #2619 #2769

**Comment by ejsupernova** [comment]
alright thank you
