### ISSUE TITLE
Baritone does not support modded mining levels.

### ISSUE THREAD

**Issue by pudy248** [cabaletta/baritone#3217]
Obligatory stacktrace:
[18:00:43] [Client thread/INFO]: [CHAT] [Baritone] > mine appliedenergistics2:quartz_ore
[18:00:43] [Client thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=BlockQuartzOre[quartz_ore],meta=null}]
[18:00:43] [Client thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: baritone.ax: java.lang.IllegalArgumentException: No enum constant net.minecraft.item.Item.ToolMaterial.COPPER
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.hh.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.hg.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.fc.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.hi$$Lambda$5782/533179264.accept(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at baritone.hi.a(Unknown Source)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:00:43] [Client thread/INFO]: [baritone.ax:a:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Likely caused by the Tool Progression mod overwriting mining levels. I do not know near enough about forge modding (or Java in general) to fix this myself, otherwise I would have. I haven't tested with Tinkers Construct tools yet, but I would be surprised if everything works as intended, even without TP mining levels.

## Final checklist
- [x] I know how to properly use check boxes 
- [uwu] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
duplicate #3008
