### ISSUE TITLE
renderCachedChunks random crash maybe?

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#327]
```
java.lang.ArrayIndexOutOfBoundsException: 28
	at net.minecraft.world.ChunkCache.getLightForExt(ChunkCache.java:151)
	at net.minecraft.world.ChunkCache.getCombinedLight(ChunkCache.java:79)
	at net.minecraft.block.Block.getPackedLightmapCoords(Block.java:513)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPackedLightmapCoords(BlockStateContainer.java:352)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.updateVertexBrightness(BlockModelRenderer.java:351)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:125)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:69)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:44)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:35)
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:75)
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:198)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.ChunkCache.getLightForExt(ChunkCache.java:151)
	at net.minecraft.world.ChunkCache.getCombinedLight(ChunkCache.java:79)
	at net.minecraft.block.Block.getPackedLightmapCoords(Block.java:513)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPackedLightmapCoords(BlockStateContainer.java:352)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.updateVertexBrightness(BlockModelRenderer.java:351)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:125)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:69)

-- Block model being tesselated --
Details:
	Block: minecraft:stone[variant=stone]
	Block location: World: (-625,62,392), Chunk: (at 15,3,8 in -40,24; contains blocks -640,0,384 to -625,255,399), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:44)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:35)

-- Block being tesselated --
Details:
	Block type: ID #1 (tile.stone // net.minecraft.block.BlockStone)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-625,62,392), Chunk: (at 15,3,8 in -40,24; contains blocks -640,0,384 to -625,255,399), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:75)
```

**Comment by leijurv** [comment]
only happens with smooth lighting lmao

**Comment by leijurv** [comment]
```---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/13/19 6:37 PM
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: 26
	at net.minecraft.world.ChunkCache.getLightForExt(ChunkCache.java:151)
	at net.minecraft.world.ChunkCache.getCombinedLight(ChunkCache.java:79)
	at net.minecraft.block.Block.getPackedLightmapCoords(Block.java:513)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPackedLightmapCoords(BlockStateContainer.java:352)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.updateVertexBrightness(BlockModelRenderer.java:351)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:125)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:69)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:44)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:35)
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:75)
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:198)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.ChunkCache.getLightForExt(ChunkCache.java:151)
	at net.minecraft.world.ChunkCache.getCombinedLight(ChunkCache.java:79)
	at net.minecraft.block.Block.getPackedLightmapCoords(Block.java:513)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPackedLightmapCoords(BlockStateContainer.java:352)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.updateVertexBrightness(BlockModelRenderer.java:351)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:125)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:69)

-- Block model being tesselated --
Details:
	Block: minecraft:stone[variant=stone]
	Block location: World: (-230,65,-729), Chunk: (at 10,4,7 in -15,-46; contains blocks -240,0,-736 to -225,255,-721), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:44)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:35)

-- Block being tesselated --
Details:
	Block type: ID #1 (tile.stone // net.minecraft.block.BlockStone)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-230,65,-729), Chunk: (at 10,4,7 in -15,-46; contains blocks -240,0,-736 to -225,255,-721), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:75)```

**Comment by leijurv** [comment]
ok so this can actually happen lol =/

**Comment by Wferr** [comment]
Not sure if this is related to the rendercahcedchunks not working with optifine but is optifine ever going to work with it? Thanks.

**Comment by 0-x-2-2** [comment]
prob will never work with optifine
