### ISSUE TITLE
baritone.dm.a() returns null

### ISSUE THREAD

**Issue by Boobies** [cabaletta/baritone#3289]
Sometimes when I try to load a world, I get this:

```
[01:11:34] [pool-14-thread-2/ERROR]: Uncaught exception in thread "pool-14-thread-2"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_19538()" because the return value of "baritone.dm.a()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at baritone.dm.a(Unknown Source) ~[baritone-standalone-fabric-1.8.2.jar:?]
	at baritone.eo.c(Unknown Source) ~[baritone-standalone-fabric-1.8.2.jar:?]
	at baritone.eo.b(Unknown Source) ~[baritone-standalone-fabric-1.8.2.jar:?]
	at baritone.eo.d(Unknown Source) ~[baritone-standalone-fabric-1.8.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by wagyourtail** [comment]
please fill out the issue template properly.

**Comment by Boobies** [comment]
This was on 1.18.1, under Fabric. If you need the whole log, I can upload it later when I have access to it. That said, the rest of the template is retarded because it asks for information already in the log.

**Comment by wagyourtail** [comment]
> the template is retarded because it asks for information already in the log

some of that info isn't on forge.
and you didn't even provide the whole log so you don't have that excuse as that info isn't present here

**Comment by scorbett123** [comment]
To fix this for now disable pruneRegionsFromRAM, however I will look in to a more permanent fix for this
