### ISSUE TITLE
#build results in java.lang.NullPointerException if allowInventory is enabled.

### ISSUE THREAD

**Issue by banana-man95** [cabaletta/baritone#3298]
## Some information
Operating system: Windows 10 version 20H2 OS Build 19042.1466
Java version: Version 8 update 321 
Minecraft version: 1.17.1
Baritone version: v1.7.2
Other mods (if used): Fabric loader (if that's considered a mod)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
```
[14:56:17] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.13.1
[14:56:17] [main/INFO]: Loading 4 mods:
	- baritone 1.7.2
	- fabricloader 0.13.1
	- java 16
	- minecraft 1.17.1
[14:56:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Alejandro/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.1+mixin.0.8.5/sponge-mixin-0.11.1+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:56:17] [main/INFO]: Compatibility level set to JAVA_16
[14:56:24] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:56:25] [Render thread/INFO]: Setting user: echo_skeppy
[14:56:26] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[14:56:28] [Render thread/WARN]: Removed resource pack Fabric Mods from options because it doesn't seem to exist anymore
[14:56:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[14:56:29] [Render thread/INFO]: Reloading ResourceManager: Default
[14:56:38] [Render thread/INFO]: OpenAL initialized.
[14:56:38] [Render thread/INFO]: Sound engine started
[14:56:38] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[14:56:38] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[14:56:38] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[14:56:38] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[14:56:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[14:56:38] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[14:56:38] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:56:40] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:56:40] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:56:40] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:57:44] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:57:44] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:57:44] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:57:44] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:57:44] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:57:44] [Render thread/INFO]: Reloading ResourceManager: Default
[14:57:45] [Render thread/INFO]: Loaded 7 recipes
[14:57:45] [Render thread/INFO]: Loaded 1137 advancements
[14:57:46] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:57:46] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[14:57:46] [Server thread/INFO]: Generating keypair
[14:57:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:57:46] [Render thread/INFO]: Preparing spawn area: 0%
[14:57:47] [Render thread/INFO]: Preparing spawn area: 0%
[14:57:47] [Render thread/INFO]: Preparing spawn area: 8%
[14:57:48] [Render thread/INFO]: Preparing spawn area: 31%
[14:57:48] [Render thread/INFO]: Preparing spawn area: 84%
[14:57:48] [Render thread/INFO]: Time elapsed: 2456 ms
[14:57:49] [Server thread/INFO]: Changing view distance to 2, from 10
[14:57:49] [Server thread/INFO]: echo_skeppy[local:E:bac4ea6e] logged in with entity id 1 at (-80.23880921120232, 5.001335979112147, -99.25518755035587)
[14:57:49] [Server thread/INFO]: echo_skeppy joined the game
[14:57:50] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256
[14:57:50] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[14:57:50] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\waypoints
[14:57:50] [Server thread/INFO]: Saving and pausing game...
[14:57:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[14:57:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[14:57:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[14:57:50] [Render thread/INFO]: Loaded 185 advancements
[14:57:50] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[14:57:50] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 249ms
[14:58:20] [pool-3-thread-2/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[14:58:20] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[14:58:20] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[14:58:20] [pool-3-thread-2/INFO]: [STDOUT]: Saved region successfully
[14:58:20] [pool-3-thread-2/INFO]: [STDOUT]: World save took 119ms
[14:58:32] [Render thread/INFO]: [CHAT] [Baritone] > build modernflorida4.schem
[14:58:32] [Render thread/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[14:58:32] [Render thread/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=-74,y=4,z=7}
[14:58:32] [Render thread/INFO]: [STDOUT]: Loading region 0,-1 from disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[14:58:32] [Render thread/INFO]: [STDOUT]: Loaded region successfully in 9ms
[14:59:46] [Render thread/INFO]: [CHAT] [Baritone] > stop
[14:59:46] [Render thread/INFO]: [CHAT] [Baritone] ok canceled
[15:00:05] [Server thread/INFO]: [echo_skeppy: Set the time to 1000]
[15:00:05] [Render thread/INFO]: [CHAT] Set the time to 1000
[15:00:09] [Server thread/INFO]: [echo_skeppy: Set the weather to clear]
[15:00:09] [Render thread/INFO]: [CHAT] Set the weather to clear
[15:00:24] [Render thread/INFO]: [CHAT] [Baritone] > build modernflorida4.schem
[15:00:24] [Render thread/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[15:00:24] [Render thread/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=-141,y=4,z=-17}
[15:02:10] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "<parameter1>" is null
	at baritone.ja.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at baritone.ja.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at baritone.kw.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at baritone.ek.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at baritone.hd.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at baritone.hd.a(Unknown Source) ~[baritone-standalone-fabric-1.7.2.jar:?]
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1719) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
[15:02:10] [Server thread/INFO]: Stopping server
[15:02:10] [Server thread/INFO]: Saving players
[15:02:10] [Server thread/INFO]: Saving worlds
[15:02:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[15:02:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[15:02:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[15:02:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (2)): All chunks are saved
[15:02:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:02:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:02:10] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

## How to reproduce
1. set allowInventory to true
2. run a schematic.
3. give it some time, and it will crash.

## Modified settings
To get the modified settings run `#modified` in game
allowInventory (Boolean) set to true
allowParkour (Boolean) set to true
allowParkourPlace (Boolean) set to true
avoidance (Boolean) set to true
freeLook (Boolean) set to false

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Mathrandom7910** [comment]
does 1.17 not require java 16 to run?

**Comment by banana-man95** [comment]
Apparently not, because I'm running 1.17 just fine, maybe I'm checking the version in the wrong place?

**Comment by wagyourtail** [comment]
> - java 16

that is java 16

**Comment by wagyourtail** [comment]
I've been having trouble figuring out why `Cannot invoke "net.minecraft.class_2680.method_26204()" because "<parameter1>" is null` is actually happening...
would someone be able to reproduce this using the baritone-unoptimized jar?

**Comment by banana-man95** [comment]
```
[20:57:39] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.13.1
[20:57:39] [main/INFO]: Loading 7 mods:
	- baritone 1.7.2
	- fabric-resource-loader-v0 0.4.8+a00e834b18 via malilib
	- fabricloader 0.13.1
	- java 16
	- litematica 0.9.0
	- malilib 0.10.0-dev.26
	- minecraft 1.17.1
[20:57:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Alejandro/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.1+mixin.0.8.5/sponge-mixin-0.11.1+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:57:39] [main/INFO]: Compatibility level set to JAVA_16
[20:57:48] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:57:49] [Render thread/INFO]: Setting user: echo_skeppy
[20:57:49] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:57:53] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:57:54] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Resource Loader (v0), Fabric Loader, Litematica, MaLiLib)
[20:57:55] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:57:55] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[20:58:00] [Render thread/INFO]: OpenAL initialized.
[20:58:00] [Render thread/INFO]: Sound engine started
[20:58:00] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[20:58:01] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[20:58:01] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[20:58:01] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[20:58:01] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[20:58:01] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[20:58:01] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:58:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:58:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:58:02] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:58:17] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:58:17] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:58:17] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:58:17] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:58:17] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:58:17] [Render thread/INFO]: Reloading ResourceManager: Default
[20:58:17] [Render thread/INFO]: Loaded 7 recipes
[20:58:17] [Render thread/INFO]: Loaded 1137 advancements
[20:58:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:58:19] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[20:58:19] [Server thread/INFO]: Generating keypair
[20:58:19] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:58:20] [Render thread/INFO]: Preparing spawn area: 0%
[20:58:20] [Render thread/INFO]: Preparing spawn area: 0%
[20:58:21] [Render thread/INFO]: Preparing spawn area: 0%
[20:58:21] [Render thread/INFO]: Preparing spawn area: 0%
[20:58:23] [Render thread/INFO]: Preparing spawn area: 2%
[20:58:23] [Render thread/INFO]: Preparing spawn area: 2%
[20:58:23] [Render thread/INFO]: Preparing spawn area: 2%
[20:58:23] [Render thread/INFO]: Preparing spawn area: 6%
[20:58:24] [Render thread/INFO]: Preparing spawn area: 45%
[20:58:24] [Render thread/INFO]: Preparing spawn area: 45%
[20:58:26] [Render thread/INFO]: Preparing spawn area: 51%
[20:58:26] [Render thread/INFO]: Preparing spawn area: 51%
[20:58:26] [Render thread/INFO]: Preparing spawn area: 51%
[20:58:28] [Render thread/INFO]: Preparing spawn area: 57%
[20:58:28] [Render thread/INFO]: Preparing spawn area: 57%
[20:58:28] [Render thread/INFO]: Preparing spawn area: 57%
[20:58:28] [Render thread/INFO]: Preparing spawn area: 57%
[20:58:28] [Render thread/INFO]: Preparing spawn area: 59%
[20:58:30] [Render thread/INFO]: Preparing spawn area: 79%
[20:58:30] [Render thread/INFO]: Preparing spawn area: 79%
[20:58:30] [Render thread/INFO]: Preparing spawn area: 79%
[20:58:31] [Render thread/INFO]: Preparing spawn area: 84%
[20:58:31] [Render thread/INFO]: Preparing spawn area: 84%
[20:58:36] [Render thread/INFO]: Time elapsed: 16537 ms
[20:58:36] [Server thread/INFO]: Changing view distance to 19, from 10
[20:58:39] [Server thread/INFO]: echo_skeppy[local:E:8e41f7a4] logged in with entity id 1 at (-499.24413687624, 5.001335979112147, -81.5678233303364)
[20:58:39] [Server thread/INFO]: echo_skeppy joined the game
[20:58:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2091ms or 41 ticks behind
[20:58:41] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256
[20:58:41] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:58:41] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\waypoints
[20:58:41] [Render thread/INFO]: Using 3 total BufferBuilder caches
[20:58:42] [Server thread/INFO]: Saving and pausing game...
[20:58:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:58:42] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:58:42] [Render thread/INFO]: Loaded 235 advancements
[20:58:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:58:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:58:43] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 698ms
[20:58:50] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,0 from disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:58:50] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 108ms
[20:59:01] [Render thread/INFO]: [CHAT] [Baritone] > build medieval.schem
[20:59:01] [Render thread/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[20:59:01] [Render thread/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=-506,y=4,z=-102}
[20:59:01] [Render thread/INFO]: [CHAT] [Baritone] Starting layer 0
[20:59:12] [pool-3-thread-2/INFO]: [STDOUT]: Saving region -2,0 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:59:12] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saving region -2,-1 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:59:12] [ForkJoinPool.commonPool-worker-7/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:59:12] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\Alejandro\AppData\Roaming\.minecraft\saves\New World (2)\.\baritone\minecraft\overworld_256\cache
[20:59:12] [pool-3-thread-2/INFO]: [STDOUT]: Saved region successfully
[20:59:12] [ForkJoinPool.commonPool-worker-7/INFO]: [STDOUT]: Saved region successfully
[20:59:12] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[20:59:12] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[20:59:12] [pool-3-thread-2/INFO]: [STDOUT]: World save took 281ms
[20:59:14] [Render thread/INFO]: [CHAT] [Baritone] > stop
[20:59:14] [Render thread/INFO]: [CHAT] [Baritone] ok canceled
[20:59:23] [Render thread/INFO]: [CHAT] [Baritone] > allowinventory
[20:59:23] [Render thread/INFO]: [CHAT] [Baritone] Toggled setting allowInventory to true
[20:59:23] [Render thread/INFO]: [CHAT] [Baritone] Old value: false
[20:59:30] [Render thread/INFO]: [CHAT] [Baritone] > build medieval.schem
[20:59:30] [Render thread/INFO]: [CHAT] [Baritone] Successfully loaded schematic for building
[20:59:30] [Render thread/INFO]: [CHAT] [Baritone] Origin: BetterBlockPos{x=-540,y=4,z=-123}
[20:59:30] [Render thread/INFO]: [CHAT] [Baritone] Starting layer 0
[20:59:37] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "current" is null
	at baritone.process.BuilderProcess.valid(BuilderProcess.java:882) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:526) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:381) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:200) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:89) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:102) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:59) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:59) ~[baritone-unoptimized-fabric-1.7.2.jar:?]
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java:3112) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1719) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
[20:59:39] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2508ms or 50 ticks behind
[20:59:39] [Server thread/INFO]: Stopping server
[20:59:39] [Server thread/INFO]: Saving players
[20:59:39] [Server thread/INFO]: Saving worlds
[20:59:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:59:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:59:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:59:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (2)): All chunks are saved
[20:59:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:59:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:59:41] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

**Comment by wagyourtail** [comment]
hmm. I think I found out why (ish) but it's still slightly confusing as to why this happens... can you share the contents of your inventory, I'm thinking a new or weird block might be causing this...

**Comment by banana-man95** [comment]
Alright, so I have stripped spruce log, spruce planks, stone brick slabs, dark prismarine stairs, birch leaves, stone bricks, dark prismarine slabs, stone brick stairs, spruce logs, red nether bricks, lectern, smooth quartz block, chains, spruce stairs, black stained glass, spruce fence, spruce slabs, and a stone button. That's all.

**Comment by banana-man95** [comment]
New info. I deduced that it can move blocks from the inventory to the hotbar. For some reason though, if the hotbar is full, it will crash. Schematics that don't take up a full hotbar (with one of the blocks in the inv) can be built just fine, with the block in the inv being transported to the hotbar when needed.

**Comment by wagyourtail** [comment]
does that have a different crash log? I did manage to reproduce the one by duplicating you inventory and am looking into it rn.

**Comment by banana-man95** [comment]
No, it's the same crash log I sent earlier, except `<parameter1>` is changed to `<current>` (likely because the unoptimized ver is deobfuscated), non-full hotbar works fine.

**Comment by banana-man95** [comment]
How do I get the build of the commit? Or do I have to build it myself.

**Comment by banana-man95** [comment]
Nevermind, found the build. Will test.

**Comment by banana-man95** [comment]
I confirm it works. Thank you!
