### ISSUE TITLE
Baritone crashes on any pathfind command

### ISSUE THREAD

**Issue by KBD2** [cabaletta/baritone#3315]
## Some information
Operating system: Windows 10
Java version: 1.8
Minecraft version: Fabric 1.18.2
Baritone version: 1.8.3
Other mods (if used): None
- Also tested with Fabric 1.18.1/Baritone 1.8.2

## Exception, error or logs
`java.lang.IllegalArgumentException: fromIndex(50) > toIndex(11)
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:509) ~[?:?]
	at java.util.ArrayList.subList(ArrayList.java:1108) ~[?:?]
	at java.util.Collections$UnmodifiableRandomAccessList.subList(Collections.java:1439) ~[?:?]
	at baritone.ds.<init>(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at baritone.dt.a(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at baritone.dt.a(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at baritone.h.onTick(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at baritone.cb.a(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at baritone.cb.onTick(Unknown Source) ~[baritone-api-fabric-1.8.3.jar:?]
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1730) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
`
(NOTE: `toIndex` varies but `fromIndex` is always 50)

## How to reproduce
1. Run any command that involves a pathfind, e.g. `#thisway 10 -> #path`

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
can't reproduce

![Peek 2022-03-11 18-01](https://user-images.githubusercontent.com/6234704/157997019-1c4a9627-ee7f-4823-aea9-f605642c4cdf.gif)

**Comment by KBD2** [comment]
Same issue was reported in #3116. Could it be a Java issue?

**Comment by wagyourtail** [comment]
could you try making a log with the unoptimized jar?

**Comment by KBD2** [comment]
Can also reproduce on the latest version of Impact Client.

**Comment by KBD2** [comment]
> could you try making a log with the unoptimized jar?

[latest.log](https://github.com/cabaletta/baritone/files/8236855/latest.log)

**Comment by KBD2** [comment]
Found that setting `maxPathHistoryLength` to a higher number temporarily solves the problem, but it eventually crashes anyway.

**Comment by wagyourtail** [comment]
you sure this works with a clear `#modified?`

**Comment by NotRexButCaesar** [comment]
I am having the same issue with maxPathHistoryLength of 300 & pathHistoryCutoffAmount of 50.

**Comment by CoderStealer** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 09/09/2022, 21:51
Description: Unexpected error

java.lang.IllegalArgumentException: Load factor must be greater than 0 and smaller than 1
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.<init>(Long2ObjectOpenHashMap.java:107)
	at baritone.pathing.calc.AbstractNodeCostSearch.<init>(Unknown Source)
	at baritone.pathing.calc.AStarPathFinder.<init>(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1730)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.<init>(Long2ObjectOpenHashMap.java:107)
	at baritone.pathing.calc.AbstractNodeCostSearch.<init>(Unknown Source)
	at baritone.pathing.calc.AStarPathFinder.<init>(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 7 total; [class_746['miehsaisoa'/417561, l='ClientLevel', x=-51.36, y=73.00, z=8.19], class_745['§f'/264, l='ClientLevel', x=-31.46, y=66.00, z=22.59], class_745['RockVoice'/417357, l='ClientLevel', x=-35.47, y=67.00, z=16.71], class_745['_Bakastaa'/418989, l='ClientLevel', x=-35.47, y=67.00, z=16.71], class_745['Spicy321'/418445, l='ClientLevel', x=-42.61, y=65.00, z=53.53], class_745['CIT-b316cb591532'/271, l='ClientLevel', x=-59.47, y=66.00, z=55.34], class_745['jgrotot'/418921, l='ClientLevel', x=-23.86, y=64.50, z=54.07]]
	Chunk stats: 121, 49
	Level dimension: minecraft:spawn
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33571 game time, 6000 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 711417856 bytes (678 MiB) / 1744830464 bytes (1664 MiB) up to 2013265920 bytes (1920 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz
	Identifier: Intel64 Family 6 Model 76 Stepping 4
	Microarchitecture: unknown
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x22b1
	Graphics card #0 versionInfo: DriverVersion=20.19.15.5171
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 10152.27
	Virtual memory used (MB): 6337.40
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 2067.05
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx1910M -Xverify:none -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 400 GL version 3.2.0 - Build 20.19.15.5171, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 45996
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Celeron(R) CPU N3160 @ 1.60GHz

-- Meteor Client --
Version: 0.4.8

[Combat]:
arrow-dodge
auto-armor
auto-weapon
crystal-aura

[Player]:
anti-hunger
auto-eat
auto-respawn
auto-tool
ghost-hand

[Movement]:
air-jump
boat-fly
elytra-fly

[Render]:
better-tooltips
entity-owner
esp
fullbright
nametags

[Misc]:
anti-packet-kick
packet-canceller
server-spoof

**Comment by wagyourtail** [comment]
reset the [pathingMapLoadFactor](https://baritone.leijurv.com/baritone/api/Settings.html#pathingMapLoadFactor) setting back to the default value of .75

**Comment by wagyourtail** [comment]
why is this a comment on an unrelated issue
