### ISSUE TITLE
it didnt load

### ISSUE THREAD

**Issue by nightguardian23** [cabaletta/baritone#3349]
13:41:41] [Render thread/INFO]: [STDERR]: baritone.ax: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.hd.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.hc.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.ez.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.ez.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.he.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.he.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zza000$sendChatMessage(class_746.java)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:41:41] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.ab.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.fh.b(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at baritone.gi.a(Unknown Source)
[13:41:41] [Render thread/INFO]: [STDERR]: 	... 33 more
[13:41:41] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[13:41:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:41:41] [Render thread/INFO]: [STDERR]: 	... 36 more

**Comment by wagyourtail** [comment]
please fill out the issue template properly. I can't tell what your problem is without more information

**Comment by wagyourtail** [comment]
actually on closer look; this appears to be a duplicate of pinned issue.
Update to baritone version 1.8.3 and please check for duplicates before posting issues.

**Comment by nightguardian23** [comment]
thankyou very very much
