### ISSUE TITLE
getting error when i run commands (#mine, #tunnel 2 2 100, etc)

### ISSUE THREAD

**Issue by cornernote** [cabaletta/baritone#3351]
## Some information
Operating system: Windows
Java version:
Minecraft version: 1.18.2
Baritone version: fabric api, and fabric api standalone both did the same
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

```
[16:07:57] [Render thread/INFO]: [CHAT] [Baritone] > tunnel 2 2 100
[16:07:57] [Render thread/INFO]: [CHAT] [Baritone] Creating a tunnel 2 block(s) high, 2 block(s) wide, and 100 block(s) deep
[16:07:57] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:07:57] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.bz.execute(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.u.a(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.u.onSendChatMessage(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.cb.a(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.cb.onSendChatMessage(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zza000$sendChatMessage(class_746.java)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:07:57] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.api.schematic.FillSchematic.<init>(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.dx.clearArea(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at baritone.bu.execute(Unknown Source)
[16:07:57] [Render thread/INFO]: [STDERR]: 	... 32 more
[16:07:57] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[16:07:57] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:07:57] [Render thread/INFO]: [STDERR]: 	... 35 more
```

## How to reproduce

Just ran `#mine diamond_ore`, or `#tunnel 2 2 100`.

I can run `#tunnel` on it's own and it works fine

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [?] I have not used any OwO's or UwU's in this issue. (i dont know what this is)

**Comment by wagyourtail** [comment]
see pinned issue, please learn to read before posting issues.

**Comment by cornernote** [comment]
Got it, 1.18.3 is for 1.18.2, and 1.18.2 is for 1.18.1.  Clear as mud.

Recommendation - revisit how you do version numbers?

**Comment by cornernote** [comment]
Recommendation #2, perhaps your code can recognise versions of itself and minecraft, and then rather than saying "REPORT THIS BUG", you could simply output "INCOMPATIBLE MOD VERSION".  You could even output the version they should be using if you want to be really fancy at programming.

**Comment by wagyourtail** [comment]
Its not version 1.18.3 its 1.8.3 and the release page says "for minecraft 1.18.2 only" right on it

**Comment by wagyourtail** [comment]
As for hard coding version numbers, we cant predict the future so we dont know if next version will be compatible, say in the case of 1.18->1.18.1 or .117->1.17.1
