### ISSUE TITLE
An unhandled exception ocurred. 

### ISSUE THREAD

**Issue by Xoloclip** [cabaletta/baritone#3355]
## Some information
Operating system: Windows 10
Java version: 4
Minecraft version: 1.18.2
Baritone version: 1.18-SNAPSHOT
Other mods (if used): No

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[17:14:12] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[17:14:12] [main/INFO]: Loading 4 mods:
	- baritone 1.18-SNAPSHOT
	- fabricloader 0.13.3
	- java 17
	- minecraft 1.18.2
[17:14:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/alann/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:14:12] [main/INFO]: Compatibility level set to JAVA_17
[17:14:20] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:14:22] [Render thread/INFO]: Setting user: xoloismexican
[17:14:22] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:14:27] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:14:27] [Render thread/INFO]: Reloading ResourceManager: Default
[17:14:27] [Render thread/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[17:14:34] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Altavoces (Realtek(R) Audio)
[17:14:34] [Render thread/INFO]: Sound engine started
[17:14:34] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:14:34] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:14:34] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:14:34] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:14:34] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:14:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:14:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:14:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:14:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:14:36] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:14:55] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:14:55] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:14:55] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:14:55] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:14:55] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:14:56] [Render thread/INFO]: Loaded 7 recipes
[17:14:56] [Render thread/INFO]: Loaded 1141 advancements
[17:14:58] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:14:58] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[17:14:58] [Server thread/INFO]: Generating keypair
[17:14:58] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:15:00] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:00] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:00] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:00] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:00] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:01] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:01] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:02] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:02] [Render thread/INFO]: Preparando zona de aparición: 0 %
[17:15:03] [Render thread/INFO]: Preparando zona de aparición: 3 %
[17:15:03] [Render thread/INFO]: Preparando zona de aparición: 6 %
[17:15:04] [Render thread/INFO]: Preparando zona de aparición: 11 %
[17:15:04] [Render thread/INFO]: Preparando zona de aparición: 20 %
[17:15:05] [Render thread/INFO]: Preparando zona de aparición: 40 %
[17:15:05] [Render thread/INFO]: Preparando zona de aparición: 50 %
[17:15:06] [Render thread/INFO]: Preparando zona de aparición: 75 %
[17:15:07] [Render thread/INFO]: Preparando zona de aparición: 77 %
[17:15:07] [Render thread/INFO]: Preparando zona de aparición: 77 %
[17:15:07] [Render thread/INFO]: Preparando zona de aparición: 77 %
[17:15:07] [Render thread/INFO]: Time elapsed: 9108 ms
[17:15:07] [Server thread/INFO]: Changing view distance to 8, from 10
[17:15:07] [Server thread/INFO]: Changing simulation distance to 12, from 0
[17:15:10] [Server thread/INFO]: xoloismexican[local:E:32a11d27] logged in with entity id 187 at (115.06448239830921, 69.0, -67.00044796479732)
[17:15:10] [Server thread/INFO]: xoloismexican se ha unido a la partida
[17:15:12] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384
[17:15:12] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:12] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\waypoints
[17:15:12] [Render thread/INFO]: Loaded 28 advancements
[17:15:13] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:15] [Server thread/INFO]: Saving and pausing game...
[17:15:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:overworld
[17:15:16] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 3303ms
[17:15:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_end
[17:15:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_nether
[17:15:16] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2537ms or 50 ticks behind
[17:15:20] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,0 from disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:20] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 458ms
[17:15:22] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,-1 from disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:23] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 763ms
[17:15:24] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,0 from disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:25] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 1060ms
[17:15:25] [Render thread/INFO]: [CHAT] [Baritone] Command not found: 
[17:15:29] [Render thread/INFO]: [CHAT] [Baritone] Command not found: 
[17:15:34] [Render thread/INFO]: [CHAT] [Baritone] Command not found: 
[17:15:42] [pool-3-thread-2/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:42] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region 0,-1 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:42] [ForkJoinPool.commonPool-worker-2/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:42] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region 0,0 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:15:42] [pool-3-thread-2/INFO]: [STDOUT]: Saved region successfully
[17:15:42] [ForkJoinPool.commonPool-worker-2/INFO]: [STDOUT]: Saved region successfully
[17:15:42] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[17:15:42] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[17:15:42] [pool-3-thread-2/INFO]: [STDOUT]: World save took 525ms
[17:15:45] [Server thread/INFO]: Saving and pausing game...
[17:15:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:overworld
[17:15:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_end
[17:15:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_nether
[17:16:28] [Render thread/INFO]: [CHAT] [Baritone] Command not found: 
[17:16:32] [Render thread/INFO]: [CHAT] [Baritone] Command not found: 
[17:23:28] [Server thread/INFO]: Saving and pausing game...
[17:23:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:overworld
[17:23:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_end
[17:23:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_nether
[17:24:31] [Render thread/INFO]: [CHAT] [Baritone] > mine diamond_ore
[17:24:31] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:24:31] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zza000$sendChatMessage(class_746.java)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17:24:31] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.command.argument.ArgConsumer.getDatatypeFor(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[17:24:31] [Render thread/INFO]: [STDERR]: 	... 32 more
[17:24:31] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[17:24:31] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:24:31] [Render thread/INFO]: [STDERR]: 	... 36 more
[17:24:35] [Server thread/INFO]: Saving and pausing game...
[17:24:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:overworld
[17:24:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_end
[17:24:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Mundo nuevo]'/minecraft:the_nether
[17:25:42] [pool-3-thread-2/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:25:42] [ForkJoinPool.commonPool-worker-4/INFO]: [STDOUT]: Saving region 0,-1 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:25:42] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:25:42] [ForkJoinPool.commonPool-worker-6/INFO]: [STDOUT]: Saving region 0,0 to disk C:\Users\alann\AppData\Roaming\.minecraft\saves\Mundo nuevo (1)\.\baritone\minecraft\overworld_384\cache
[17:25:42] [pool-3-thread-2/INFO]: [STDOUT]: Saved region successfully
[17:25:42] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[17:25:42] [ForkJoinPool.commonPool-worker-6/INFO]: [STDOUT]: Saved region successfully
[17:25:42] [ForkJoinPool.commonPool-worker-4/INFO]: [STDOUT]: Saved region successfully
[17:25:42] [pool-3-thread-2/INFO]: [STDOUT]: World save took 157ms
[17:35:39] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 12726ms or 254 ticks behind
[17:57:35] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 1300838ms or 26016 ticks behind
[17:57:38] [pool-3-thread-2/INFO]: [STDOUT]: World save took 3ms

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Do the "mine" command with anything. 

Uwu Owo

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment]
update to 1.8.3, read pinned issues before posting. marking duplicate
