### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by c0d3rb0y** [cabaletta/baritone#3366]
## What do you need help with?
so i'm trying to add baritone to my 1.12 (not 1.12.2) client. i am using MCP and not forge. i tried my best to get the latest (https://github.com/cabaletta/baritone/pull/3324[](https://github.com/cabaletta/baritone/commit/8c2aae2ddc5b9930ecbdc1d1de9b03d4a9414ee0)) src to work on 1.12, and may have messed a few things up in the process. when i use the example code provided in the readme, executed by command in my client, it produces this error:
`
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1879) ~[bin/:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1181) ~[bin/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:475) [bin/:?]
	at net.minecraft.client.main.Main.main(Main.java:115) [bin/:?]
	at Start.main(Start.java:9) [bin/:?]
Caused by: java.lang.ExceptionInInitializerError
	at myclient.command.impl.Goto.onCommand(Goto.java:19) ~[bin/:?]
	at myclient.command.CommandManager.handleChat(CommandManager.java:43) ~[bin/:?]
	at myclient.Client.onEvent(Client.java:98) ~[bin/:?]
	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java:391) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:458) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:448) ~[bin/:?]
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:131) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:609) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:558) ~[bin/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1866) ~[bin/:?]
	... 4 more
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365) ~[?:1.8.0_312]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_312]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_312]
	at baritone.api.BaritoneAPI.<clinit>(BaritoneAPI.java:42) ~[bin/:?]
	at myclient.command.impl.Goto.onCommand(Goto.java:19) ~[bin/:?]
	at myclient.command.CommandManager.handleChat(CommandManager.java:43) ~[bin/:?]
	at myclient.Client.onEvent(Client.java:98) ~[bin/:?]
	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java:391) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:458) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:448) ~[bin/:?]
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:131) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:609) ~[bin/:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:558) ~[bin/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1866) ~[bin/:?]
	... 4 more`

there is probably some easy solution to this but i am just dumb

also no i cannot use the jar it doesn't work with my java version

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by zukey26** [comment]
Also your error might be here
> [bin/:?] at Start.main(Start.java:9) [bin/:?] Caused by: java.lang.ExceptionInInitializerError at myclient.command.impl.Goto.onCommand(Goto.java:19) ~[bin/:?] at

**Comment by scorbett123** [comment]
We don't support the use of baritone api from a mcp env. Just use forge.
