### ISSUE TITLE
baritone crash when I use #sel r air dirt

### ISSUE THREAD

**Issue by kpXicon** [cabaletta/baritone#3417]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/25/22, 6:05 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "<parameter1>" is null
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.MaskSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.process.BuilderProcess$BuilderCalculationContext.a(Unknown Source)
	at baritone.process.BuilderProcess.a(Unknown Source)
	at baritone.process.BuilderProcess.onTick(Unknown Source)
	at baritone.utils.PathingControlManager.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zdi000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1730)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.api.utils.BlockOptionalMeta.matches(Unknown Source)
	at baritone.api.schematic.FillSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.MaskSchematic.desiredState(Unknown Source)
	at baritone.api.schematic.CompositeSchematic.desiredState(Unknown Source)
	at baritone.process.BuilderProcess$BuilderCalculationContext.a(Unknown Source)
	at baritone.process.BuilderProcess.a(Unknown Source)
	at baritone.process.BuilderProcess.onTick(Unknown Source)
	at baritone.utils.PathingControlManager.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zdi000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 2 total; [class_746['kpXicon'/304, l='ClientLevel', x=-124.34, y=66.00, z=-114.99], FreeCamera['FreeCamera'/6904, l='ClientLevel', x=-126.08, y=66.40, z=-113.44]]
	Chunk stats: 1024, 321
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 134265 game time, 134265 day time
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, 1.18.zip, §c§l[1.17] §aThaiFont.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 601756448 bytes (573 MiB) / 1342177280 bytes (1280 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) CPU 4417U @ 2.30GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 610
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5906
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7372
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 10890.30
	Virtual memory used (MB): 7049.87
	Swap memory total (MB): 6912.00
	Swap memory used (MB): 997.25
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 4.2.50
		baritone: Baritone 1.18.2-SNAPSHOT
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_github_llamalad7_mixinextras: MixinExtras 0.0.6
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.51.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.0+bd8a4a1860
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		freecam: Freecam 0.4.8
		iris: Iris 1.2.1
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.4.2+1.18.2
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.9
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.1
		okzoomer: Ok Zoomer 5.0.0-beta.6+1.18.2
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 3.0.0+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.2+1.18.2-SNAPSHOT
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.3+1.18
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 610 GL version 3.2.0 - Build 26.20.100.7372, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 114
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/1.18.zip, file/§c§l[1.17] §aThaiFont.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Pentium(R) CPU 4417U @ 2.30GHz

**Comment by wagyourtail** [comment]
duplicate #3407 #3308 #3298, #3165, #3106, #3244, #3205, #3102
