### ISSUE TITLE
Error when trying to #mine

### ISSUE THREAD

**Issue by Ozzy4201** [cabaletta/baritone#3430]
[12:00:09] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[12:00:09] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.bz.execute(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.u.a(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.u.onSendChatMessage(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.cb.a(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.cb.onSendChatMessage(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zza000$sendChatMessage(class_746.java)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.method_25427(GuiChatOF.java:41)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:716)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:118)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:715)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:202)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:442)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[12:00:09] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.ac.getDatatypeFor(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at baritone.be.execute(Unknown Source)
[12:00:09] [Render thread/INFO]: [STDERR]: 	... 33 more
[12:00:09] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[12:00:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:00:09] [Render thread/INFO]: [STDERR]: 	... 37 more

**Comment by scorbett123** [comment]
This is due to you using the wrong version of baritone. If you are playing 1.18.1, or 1.18 please use baritone version 1.8.2, for 1.18.2 use baritone version 1.8.3.

**Comment by Ozzy4201** [comment]
> 

oh ok, thats confusing, thank you
