### ISSUE TITLE
Baritone can't execute the mine command

### ISSUE THREAD

**Issue by MrJeffOfficial** [cabaletta/baritone#3434]
Operating system: Windows 10
Java version: 1.8.0_51
Minecraft version: 1.12.2
Baritone version: Latest in impact
[latest.log](https://github.com/cabaletta/baritone/files/8632846/latest.log)
![Screenshot_104](https://user-images.githubusercontent.com/38805169/166965753-ba6684bc-084e-4e94-9f91-091de977eeef.png)

**Comment by dpill83** [comment]
[latest.log](https://github.com/cabaletta/baritone/files/8642985/latest.log)

Getting error when trying to execute mine command

An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[13:36:40] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zfn000$sendChatMessage(class_746.java)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.method_25427(GuiChatOF.java:41)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:716)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:118)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:715)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:225)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1150)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:36:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.api.command.datatypes.ForBlockOptionalMeta.get(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.command.argument.ArgConsumer.getDatatypeFor(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[13:36:40] [Render thread/INFO]: [STDERR]: 	... 32 more
[13:36:40] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[13:36:40] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:36:40] [Render thread/INFO]: [STDERR]: 	... 36 more

**Comment by wagyourtail** [comment]
duplicate of pinned issue

**Comment by wagyourtail** [comment]
o wait, this is on 1.12

**Comment by wagyourtail** [comment]
wait, @dpill83, why is this a comment on someone else's issue, yours is a duplicate of pinned

**Comment by dpill83** [comment]
> wait, @dpill83, why is this a comment on someone else's issue, yours is a duplicate of pinned

do i have to make a new issue for the same issue?

**Comment by wagyourtail** [comment]
well, it's a different issue. and yours is already answered in the pinned issue: use baritone 1.8.3 for 1.18.2

**Comment by MrJeffOfficial** [comment]
so uh any answers?
