### ISSUE TITLE
Minecraft Crashes when stepping/jumping on CBMultiPart blocks

### ISSUE THREAD

**Issue by PlatyPew** [cabaletta/baritone#3530]
## Some information
Operating system: MacOS 12.4 (Monterey)
Java version: Java Zulu8
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used):  [Create Above and Beyond Modpack](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond)

## Exception, error or logs

Full crash report: [crash-2022-06-26_09.30.11-client.txt](https://github.com/cabaletta/baritone/files/8986056/crash-2022-06-26_09.30.11-client.txt)

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/26/22 9:30 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at codechicken.multipart.block.BlockMultiPart.getTile(BlockMultiPart.java:315) ~[cb_multipart:1.16.5-3.0.3.122] {re:classloading}
	at codechicken.multipart.block.BlockMultiPart.func_220071_b(BlockMultiPart.java:82) ~[cb_multipart:1.16.5-3.0.3.122] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:545) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:AbstractBlockMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:541) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:AbstractBlockMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A}
	at baritone.cj.h(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.cj.c(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.cj.b(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.cj.b(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.i.a(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.i.onTick(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at baritone.cd.a(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_332] {}
	at baritone.cd.onTick(Unknown Source) ~[baritoe:1.6.3] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zpk000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1450) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.28-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}
```

## How to reproduce

1. Step on top of a block that is from CBMultipart (e.g. ProjectRed).
2. If game does not crash, try jumping on it

## Modified settings

```
[Baritone] allowDiagonalAscend (Boolean)
[Baritone] allowDiagonalDescend (Boolean)
[Baritone] allowParkour (Boolean)
[Baritone] allowParkourPlace (Boolean)
[Baritone] allowVines (Boolean)
[Baritone] avoidance (Boolean)
[Baritone] blockBreakAdditionalPenalty (Double)
[Baritone] blockReachDistance (Float)
[Baritone] blocksToAvoidBreaking (List<Block>)
[Baritone] chatControl (Boolean)
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by PlatyPew** [comment]
The latest commit b54ddeadf4ff580de68e63a926f2d8d2c2e7b15e on the 1.16.5 branch has fixed this issue
