### ISSUE TITLE
Minecraft keeps freezing when I join a server or create a world

### ISSUE THREAD

**Issue by BlockbenchUser** [cabaletta/baritone#3668]
## Some information
Operating system: Windows
Minecraft version: 1.16.5

If I create a world or join a server, Minecraft freezes, and I have to close it out. This keeps happening every single time.

Exit Code: -805306369

**Comment by Mathrandom7910** [comment]
Baritone version? Other Mods? Crash log?

**Comment by BlockbenchUser** [comment]
Using impact 4.9 for minecraft 1.16.5., no other mods, latest log is attatched.
[latest.log](https://github.com/cabaletta/baritone/files/9636998/latest.log)

**Comment by ZacSharp** [comment]
If I got the mappings right this is thrown in `WorldRenderer.updateCameraAndRender` because your `mc.gameSettings.framerateLimit` is 0.

<details><summary>Stacktrace I reconstructed (mcp names)</summary>
If you want to compare line numbers from the stacktrace and mc bytecode, use those in the original stacktrace and not those I took from my files.
<pre>
java.lang.ArithmeticException: / by zero
	at net.minecraft.client.renderer.WorldRenderer.updateCameraAndRender(WorldRender.java:935) ~[WorldRenderer.class:?]
	at net.minecraft.client.renderer.GameRenderer.renderWorld(GameRenderer.java:600) ~[GameRenderer.class:?]
	at net.minecraft.client.renderer.GameRenderer.updateCameraAndRender(GameRenderer.java:423) ~[GameRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:966) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:603) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
</pre></summary>

As I can't see any sign of mixin messing this up and since Baritone afaik doesn't mess with the frame rate limit I'd say this is caused by Impact and not by Baritone.

**Comment by BlockbenchUser** [comment]
The same crashes were happening with just baritone, too. I tried impact afterwards hoping it would fix the problem.

**Comment by ZacSharp** [comment]
Before joining the world, got to `Options > Video Settings` and you'll see that `Max Framerate` is `0 fps`. Set it to any other value and the problem will be gone (at least I hope so).

**Comment by BlockbenchUser** [comment]
Okay, that did work. Thank you very much.
