### ISSUE TITLE
Cannot mine above level 256

### ISSUE THREAD

**Issue by rjbarber** [cabaletta/baritone#3692]
I would like to mine at level 320, which is the build height on the server I play on, but Baritone will not allow me to. I'm getting an error. Here's the minecraft log from the time I enter the mine command.
 "[19:52:13] [Render thread/INFO]: [CHAT] [Baritone] > mine obsidian
[19:52:13] [Render thread/INFO]: Reloading ResourceManager: Default
[19:52:13] [Render thread/WARN]: Could not resolve dependencies for listener: fabric:private/fire_registry_1!
[19:52:13] [Render thread/WARN]: Could not resolve dependencies for listener: fabric-mining-level-api-v1:cache_invalidator!
[19:52:13] [Render thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:obsidian}}]
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 257 out of bounds for length 257
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.pathing.movement.movements.MovementDescend.a(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.pathing.movement.movements.MovementDescend.a(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.pathing.movement.Moves$11.a(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.pathing.calc.AStarPathFinder.a(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.pathing.calc.AbstractNodeCostSearch.calculate(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.behavior.PathingBehavior.a(Unknown Source)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:52:13] [pool-4-thread-4/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)". 

This looks like a limit in the code preventing mining above 256. Is this configurable? Can it be made configurable?

**Comment by wagyourtail** [comment]
I'm like 90% sure I patched this 2 years ago. can you get this stack trace with an unoptimized version and fill out the bug report template

**Comment by wagyourtail** [comment]
ok. found it. and found why it's still an issue.
https://github.com/cabaletta/baritone/pull/3254
and it was fixed liteally right after the last baritone release

**Comment by rjbarber** [comment]
@wagyourtail-So is it fair to say this is fixed but not released and I should expect this functionality in a future release?

**Comment by wagyourtail** [comment]
yes
