### ISSUE TITLE
mineing not working

### ISSUE THREAD

**Issue by jonasrhee1208** [cabaletta/baritone#3770]
this:
[08:22:55] [Render thread/INFO]: [System] [CHAT] [Baritone] Error at argument #1: Expected ForBlockOptionalMeta
[08:23:05] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine diamond_ore
[08:23:05] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[08:23:05] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zzb000$sendChatMessage(class_634.java)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[08:23:05] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[08:23:05] [Render thread/INFO]: [STDERR]: 	... 28 more

**Comment by Handol224** [comment]
the same thing is happenning to me 
did you solve it?

**Comment by wagyourtail** [comment]
Update baritone
