### ISSUE TITLE
I can't mine

### ISSUE THREAD

**Issue by QuangSon2022** [cabaletta/baritone#3787]
## Some information
Operating system: Windows
Java version: java-runtime-gamma
Minecraft version: Fabric 1.19.3
Baritone version: baritone-fabric-standalone-1.8.3-221-g716562ba
Other mods (if used): exordium-fabric-1.0.3-mc1.19.3, fabric-api-0.69.1+1.19.3, lazydfu-0.1.3, litematica-fabric-1.19.3-0.13.1, lithium-fabric-mc1.19.3-0.10.4, malilib-fabric-1.19.3-0.14.0, smoothboot-fabric-1.19-1.7.1, sodium-fabric-mc1.19.3-0.4.6+build.20, Wurst-Client-v7.31-MC1.19.3

## Exception, error or logs
[13:09:24] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[13:09:24] [ForkJoinPool-1-worker-2/WARN]: Mod wurst uses the version v7.31-MC1.19.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v7'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[13:09:25] [main/INFO]: Loading 61 mods:
	- baritone 1.8.3-221-g716562ba
	- exordium 1.0.3-mc1.19.3
	- fabric-api 0.69.1+1.19.3
	- fabric-api-base 0.4.19+8d1895cf85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.18+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.0.0+689f5e7185 via fabric-api
	- fabric-block-api-v1 1.0.3+12bfe4ea85 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.28+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.9+49abcf7e85 via fabric-api
	- fabric-command-api-v1 1.2.19+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.15+49abcf7e85 via fabric-api
	- fabric-commands-v0 0.2.36+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.44+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.4.12+49abcf7e85 via fabric-api
	- fabric-convention-tags-v1 1.2.0+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.12+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.1+112a38be85 via fabric-api
	- fabric-dimensions-v1 2.1.39+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.5+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.37+422b77fb85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.39+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.28+2894d6df85 via fabric-api
	- fabric-item-api-v1 2.1.5+4d2c606385 via fabric-api
	- fabric-item-group-api-v1 2.1.8+d3d735d085 via fabric-api
	- fabric-key-binding-api-v1 1.0.28+aaaf9d3385 via fabric-api
	- fabric-keybindings-v0 0.2.26+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.8+2894d6df85 via fabric-api
	- fabric-loot-api-v2 1.1.18+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.22+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.12+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.29+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.25+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.14+d9ac3c3985 via fabric-api
	- fabric-networking-v0 0.3.31+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.2.0+e9dee00485 via fabric-api
	- fabric-particles-v1 1.0.18+fbde993d85 via fabric-api
	- fabric-registry-sync-v0 2.0.1+2608564685 via fabric-api
	- fabric-renderer-api-v1 2.1.0+2063beff85 via fabric-api
	- fabric-renderer-indigo 0.6.23+11ba9c3b85 via fabric-api
	- fabric-renderer-registries-v1 3.2.28+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.23+48349a3f85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.16+3067f46385 via fabric-api
	- fabric-rendering-v0 1.1.31+df3654b385 via fabric-api
	- fabric-rendering-v1 1.11.7+49abcf7e85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.0+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.3+a10d22bd85 via fabric-api
	- fabric-screen-api-v1 1.0.39+1d4d0b5785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.10+689f5e7185 via fabric-api
	- fabric-sound-api-v1 1.0.6+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.12+82a2701785 via fabric-api
	- fabric-transitive-access-wideners-v1 2.1.0+0efcd39b85 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- lazydfu 0.1.3
	- litematica 0.13.1
	- lithium 0.10.4
	- malilib 0.14.0
	- minecraft 1.19.3
	- smoothboot 1.19-1.7.1
	- sodium 0.4.6+build.20
	- wurst v7.31-MC1.19.3
[13:09:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/quang/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:09:25] [main/INFO]: Compatibility level set to JAVA_17
[13:09:26] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 0 override(s) found
[13:09:26] [main/INFO]: Loaded configuration file for Sodium: 30 options available, 0 override(s) found
[13:09:28] [main/INFO]: Smooth Boot config initialized
[13:09:37] [main/INFO]: Building unoptimized datafixer
[13:09:41] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[13:09:41] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[13:09:41] [Render thread/INFO]: Setting user: SonNguyen2023
[13:09:41] [Render thread/INFO]: [STDOUT]: Starting Wurst Client...
[13:09:43] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[13:09:44] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[13:09:46] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[13:09:52] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:09:53] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Exordium, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, LazyDFU, Litematica, Lithium, MaLiLib, Smooth Boot, Sodium, Wurst Client)
[13:09:56] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[13:10:04] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:10:04] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:10:05] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speaker (Realtek(R) Audio)
[13:10:05] [Render thread/INFO]: Sound engine started
[13:10:05] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[13:10:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[13:10:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:10:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:10:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:10:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:10:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:10:07] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:10:08] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[13:10:08] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:10:08] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:10:24] [Render thread/INFO]: Connecting to ZeroTier.gotdns.ch, 25598
[13:10:28] [Render thread/INFO]: Started 2 worker threads
[13:10:30] [Render thread/INFO]: Using 3 total BufferBuilder caches
[13:10:31] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:31] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[13:10:32] [Render thread/INFO]: Loaded 48 advancements
[13:10:32] [Render thread/INFO]: [STDOUT]: Brightness started at 0.5
[13:10:34] [WurstUpdater/INFO]: [STDOUT]: [Updater] Current version: 7.31
[13:10:34] [WurstUpdater/INFO]: [STDOUT]: [Updater] Latest version: 7.31
[13:11:03] [Render thread/INFO]: [STDERR]: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:ỉ
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.method_45137(class_2960.java:244)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:47)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:51)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:56)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.au.b(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.u.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.eo.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.fp.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.gg$a.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4717.handler$zzc000$preUpdateSuggestion(class_4717.java)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4717.method_23934(class_4717.java)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_23945(class_408.java:83)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_1874(class_342.java:152)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_1867(class_342.java:147)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_25400(class_342.java:358)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25400(class_4069.java:82)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1458(class_309.java:445)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1457(class_309.java:445)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22677(class_309.java:456)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22675(class_309.java:456)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[13:11:03] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:11:05] [Render thread/INFO]: [STDERR]: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:iron_ỏ
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.method_45137(class_2960.java:244)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:47)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:51)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2960.<init>(class_2960.java:56)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.au.b(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.u.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.eo.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.fp.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.gg$a.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4717.handler$zzc000$preUpdateSuggestion(class_4717.java)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4717.method_23934(class_4717.java)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_23945(class_408.java:83)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_1874(class_342.java:152)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_1867(class_342.java:147)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_342.method_25400(class_342.java:358)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25400(class_4069.java:82)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1458(class_309.java:445)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1457(class_309.java:445)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22677(class_309.java:456)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22675(class_309.java:456)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[13:11:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:11:06] [Render thread/INFO]: Reloading ResourceManager: vanilla
[13:11:07] [Render thread/INFO]: [STDERR]: baritone.ar: java.lang.NullPointerException: Cannot invoke "baritone.k.a()" because the return value of "baritone.df.a()" is null
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.gg$a.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zzb000$sendChatMessage(class_634.java)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:11:07] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.k.a()" because the return value of "baritone.df.a()" is null
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.ek.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	at baritone.fp.a(Unknown Source)
[13:11:07] [Render thread/INFO]: [STDERR]: 	... 29 more
[13:11:20] [Render thread/INFO]: [STDERR]: baritone.ar: java.lang.NullPointerException: Cannot invoke "baritone.k.a()" because the return value of "baritone.df.a()" is null
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.gg$a.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.el.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.gh.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zzb000$sendChatMessage(class_634.java)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:11:20] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.k.a()" because the return value of "baritone.df.a()" is null
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.ek.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	at baritone.fp.a(Unknown Source)
[13:11:20] [Render thread/INFO]: [STDERR]: 	... 29 more
[13:11:30] [Render thread/INFO]: Stopping!
[13:11:30] [Render thread/INFO]: Stopping worker threads

## How to reproduce
Enter the command #mine iron_ore

## Modified settings
![Ảnh chụp màn hình 2023-01-10 134840](https://user-images.githubusercontent.com/113095126/211481682-a3864d27-a124-4c13-b528-5b3989853646.png)
![Ảnh chụp màn hình 2023-01-10 134939](https://user-images.githubusercontent.com/113095126/211481840-3e1626b9-601d-4b20-8ade-4cc5862baef7.png)
![Ảnh chụp màn hình 2023-01-10 134957](https://user-images.githubusercontent.com/113095126/211481857-31a3939f-892c-439e-a590-db6375d34c4d.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.
![2023-01-10_13 11 21](https://user-images.githubusercontent.com/113095126/211476937-d2737368-ed6b-45d1-baac-cced4dc88dee.png)

**Comment by wagyourtail** [comment]
try updating baritone versions, 1.19.3 is now on -226 https://github.com/cabaletta/baritone/actions/runs/3732468264

**Comment by AskewCow** [comment]
I have the exact same error too.

**Comment by AskewCow** [comment]
Yes, the weird thing is, baritone works in singleplayer, but when I join a multiplayer server I get that error. Now that I think about it, I should check if the server is 1.19.3

**Comment by AskewCow** [comment]
The server version:This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by AskewCow** [comment]
does anyone have the fabric jar file for that version?

**Comment by wagyourtail** [comment]
> try updating baritone versions, 1.19.3 is now on 1.8.3-226 https://github.com/cabaletta/baritone/actions/runs/3732468264

click on link, click artifacts, grab fabric jar from in zip

**Comment by AskewCow** [comment]
Yep that fixed it, thanks
