### ISSUE TITLE
#mine is not working, Comes up with the error to check my log and post it here.

### ISSUE THREAD

**Issue by william137m** [cabaletta/baritone#3796]
## Some information
Operating system: Windows 11
Java version: Latest I just updated
Minecraft version: 1.19.3
Baritone version:  1.5.3
Other mods (if used): Fabric API, sodium, reeses extra sodium options, malilibs, sodium extra, and litematica

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[17:52:37] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[17:52:37] [main/INFO]: Loading 60 mods:
	- baritone 1.5.3-704-g1112feff
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- litematica 0.13.1
	- malilib 0.14.0
	- minecraft 1.19.3
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- sodium 0.4.8+build.22
	- sodium-extra 0.4.16+mc1.19.3-build.91
[17:52:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Docto/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:52:37] [main/INFO]: Compatibility level set to JAVA_17
[17:52:38] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[17:52:38] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[17:52:40] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[17:52:46] [main/INFO]: Building optimized datafixer
[17:52:52] [Render thread/INFO]: Launching a new process to probe the system configuration!
[17:52:53] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[17:52:53] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
[17:52:53] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 528.02
[17:52:53] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[17:52:53] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[17:52:54] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:52:55] [Render thread/INFO]: Setting user: william137m
[17:52:56] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[17:52:57] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:52:59] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[17:53:01] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:53:01] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (CaffeineConfig, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Litematica, MaLiLib, Reese's Sodium Options, Sodium, Sodium Extra)
[17:53:02] [Render thread/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[17:53:06] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[17:53:06] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17:53:06] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (6- Echo Dot-803)
[17:53:06] [Render thread/INFO]: Sound engine started
[17:53:07] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[17:53:07] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/signs.png-atlas
[17:53:07] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[17:53:07] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[17:53:07] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[17:53:07] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:53:07] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[17:53:07] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:53:08] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[17:53:08] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:53:08] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:53:18] [Render thread/INFO]: Connecting to 73.33.105.167, 25565
[17:53:21] [Render thread/INFO]: Started 2 worker threads
[17:53:21] [Render thread/INFO]: [STDOUT]: BARITONE: setting current world to null
[17:53:22] [Render thread/INFO]: Using 3 total BufferBuilder caches
[17:53:22] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:22] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[17:53:23] [Render thread/INFO]: [System] [CHAT] william137m joined the game
[17:53:24] [Render thread/INFO]: Loaded 683 advancements
[17:53:27] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine oak_log
[17:53:28] [Render thread/INFO]: Reloading ResourceManager: vanilla
[17:53:28] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[17:53:28] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.bp.execute(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.u.a(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.u.onSendChatMessage(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.bq.a(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.bq.onSendChatMessage(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zzb000$sendChatMessage(class_634.java)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17:53:28] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.s.repack(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.s.repack(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	at baritone.ay.execute(Unknown Source)
[17:53:28] [Render thread/INFO]: [STDERR]: 	... 28 more

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ x] I have not used any OwO's or UwU's in this issue.

**Comment by GenshinMinecraft** [comment]
Yes, I also have this question and request an answer

**Comment by wagyourtail** [comment]
update baritone versions, fixed in 1.8.2-226+
