### ISSUE TITLE
I can't use #mine sand

### ISSUE THREAD

**Issue by Paldun** [cabaletta/baritone#3839]
## Some information
Operating system: Win 10 64 bit
Java version: java version "1.8.0_361"
Minecraft version: 1.19.3
Baritone version: 1.19.3
Other mods (if used): 

## Log

[18:41:46] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine diamond_ore
[18:41:46] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:41:46] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zdc000$sendChatMessage(class_634.java)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:41:46] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[18:41:46] [Render thread/INFO]: [STDERR]: 	... 28 more
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] > modified
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] All modified settings:
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] --
[18:44:44] [Render thread/INFO]: [System] [CHAT] [Baritone] << | >> 1/1

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
You need to update Baritone.
You can find the currently latest build for 1.19.3 [here](https://github.com/cabaletta/baritone/actions/runs/3914210910) (to download it you need to be logged in to GitHub, scroll down and click on artifacts, then unzip the file you just downloaded and select the jar you need).
Future CI builds on the 1.19.3 branch will appear on [this list](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3A1.19.3+event%3Apush+is%3Asuccess).
