### ISSUE TITLE
Can't mine modded ores in the Medieval Minecraft Modpack

### ISSUE THREAD

**Issue by pooloop09** [cabaletta/baritone#3903]
## Some information
Operating system: Windows 10 Pro
Java version: I think update 8 something (Java wont open to show me the exact version :/)
Minecraft version: 1.19.2 Fabric
Baritone version: 1.19.2
Other mods (if used): MMC1 Modpack: https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

I was trying to use baritone to get some ores that I need for a big project but after installing baritone and trying to mine them, I keep getting this error in the chat

"java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "world" is null" 

And when I checked logs this was the error that was being repeated hundreds of times

"[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "world" is null
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$mfi000$things$disallowBreakingLockedContainers(class_4970.java:10156)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.jn.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.jn.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.jn.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at java.base/java.util.function.Function.lambda$compose$0(Function.java:68)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.jn.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.gp.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.hr.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.gs.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.gr.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.gi.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.gj.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at baritone.dz.a(Unknown Source)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:14:51] [pool-8-thread-216/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)"

I tried to read this and figure it out on my own but I have no clue where to really start 

## How to reproduce
Just stand anywhere and try to  "#mine mythicmetals:mythril_ore" or "#mine mythicmetals:kyber_ore" 

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.

ERROR LOG
[latest.log](https://github.com/cabaletta/baritone/files/11184174/latest.log)

**Comment by ZacSharp** [comment]
Already fixed in #3255. Just update Baritone to make it work.
