### ISSUE TITLE
Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null

### ISSUE THREAD

**Issue by EvilEpicPanda** [cabaletta/baritone#3945]
## Some information
Operating system: Windows 10
Java version: 17
Minecraft version: 1.19.2
Baritone version: 1.9.4
Other mods (if used): [Prominence Fabric Modpack](https://www.curseforge.com/minecraft/modpacks/prominence-fabric)

## Exception, error or logs
Uncaught exception in thread "pool-9-thread-3"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
	at net.minecraft.class_4970$class_4971.handler$hlc000$interference$getHardness(class_4970.java:5653) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java) ~[client-intermediary.jar:?]
	at baritone.jp.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.jp.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.jp.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at java.util.function.Function.lambda$compose$0(Unknown Source) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at baritone.jp.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.gp.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.iv.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.iv.d(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at baritone.iv.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.iv.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.iv.a(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at baritone.iv.b(Unknown Source) ~[baritone-standalone-fabric-1.9.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

## How to reproduce
Use modpack
Try to #mine 

## Modified settings
None

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

[latest.log](https://github.com/cabaletta/baritone/files/11447515/latest.log)

**Comment by EvilEpicPanda** [comment]
> 

Was it fixed in #3255?

**Comment by ZacSharp** [comment]
Yes, it's supposed to be fixed.

**Comment by EvilEpicPanda** [comment]
`[21:21:11] [Render thread/INFO]: [CHAT] [Baritone] > mine diamond_ore
[21:21:11] [Render thread/INFO]: [CHAT] [Baritone] > mine diamond_ore
[21:21:11] [Render thread/INFO]: ARRP register - before vanilla
[21:21:11] [Render thread/INFO]: ARRP register - after vanilla
[21:21:11] [Render thread/INFO]: Reloading ResourceManager: Supplementaries Generated Pack
[21:21:11] [Render thread/INFO]: closing rrp minecraft:extrasounds
[21:21:11] [Render thread/INFO]: closing rrp woof:arrp
[21:21:11] [Render thread/INFO]: ARRP register - before vanilla
[21:21:11] [Render thread/INFO]: ARRP register - after vanilla
[21:21:11] [Render thread/WARN]: Could not resolve dependencies for listener: maybedata:conditional_recipes!
[21:21:11] [Render thread/WARN]: Could not resolve dependencies for listener: trinkets:entities!
[21:21:11] [Thread-181/INFO]: Loaded 0 item attribute modifiers
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/black_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/brown_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/cyan_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/yellow_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/green_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/lime_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/orange_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/white_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/light_blue_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/light_gray_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/gray_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/pink_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/magenta_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/purple_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/blue_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-185/WARN]: Ignoring loot modifiers for:woof:tables/block/red_dog_bed use this folder name:lootintegrations
[21:21:11] [Thread-193/ERROR]: [Fabric Seasons] Failed to load hardcoded grass colors
java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.github.lucaargolo.seasons.resources.CropConfigs.method_14491(CropConfigs.java:69) ~[fabric-seasons-2.1+1.19.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[21:21:11] [ForkJoinPool.commonPool-worker-9/INFO]: text.translated_server.loaded.translation_key
[21:21:11] [Thread-204/INFO]: Loaded 0 survival effects
[21:21:11] [Thread-206/INFO]: Loaded 0 trophies
[21:21:11] [Thread-207/INFO]: Reloaded configs for wandering_collector (server/smallest)
[21:21:11] [Thread-208/INFO]: Loaded 0 Stalactite configs!
[21:21:11] [Render thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]
[21:21:11] [Render thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]
[21:21:12] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[21:21:12] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[21:21:12] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:147)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:142)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:67)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:69)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:69)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$bjn000$baritone$sendChatMessage(class_746.java:4922)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_44097(class_746.java)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_44096(class_746.java:324)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:519)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:213)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:374)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:489)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:370)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:462)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:462)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:315)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1205)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:768)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:21:12] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$hlb000$interference$getHardness(class_4970.java:5653)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.utils.ToolSet.calculateSpeedVsBlock(ToolSet.java:180)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.utils.ToolSet.getBestSlot(ToolSet.java:135)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.utils.ToolSet.getBestDestructionTime(ToolSet.java:163)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.function.Function.lambda$compose$0(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.utils.ToolSet.getStrVsBlock(ToolSet.java:75)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.pathing.movement.MovementHelper.getMiningDurationTicks(MovementHelper.java:606)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.plausibleToBreak(MineProcess.java:469)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.lambda$prune$11(MineProcess.java:429)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.DistinctOps$1$2.accept(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.prune(MineProcess.java:444)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.searchWorld(MineProcess.java:377)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.rescan(MineProcess.java:238)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.process.MineProcess.mine(MineProcess.java:495)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.api.process.IMineProcess.mine(IMineProcess.java:75)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(MineCommand.java:50)
[21:21:12] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[21:21:12] [Render thread/INFO]: [STDERR]: 	... 29 more
[21:21:12] [pool-9-thread-4/INFO]: [STDOUT]: 22 movements considered
[21:21:12] [pool-9-thread-4/INFO]: [STDOUT]: Open set size: 0
[21:21:12] [pool-9-thread-4/INFO]: [STDOUT]: PathNode map size: 1
[21:21:12] [pool-9-thread-4/INFO]: [STDOUT]: 52 nodes per second
[21:21:12] [Render thread/INFO]: [CHAT] [Baritone] Unable to find any path to BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]}, canceling mine
[21:21:12] [Render thread/INFO]: [CHAT] [Baritone] Unable to find any path to BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore}}]}, canceling mine
[21:21:12] [pool-9-thread-3/ERROR]: Uncaught exception in thread "pool-9-thread-3"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
	at net.minecraft.class_4970$class_4971.handler$hlb000$interference$getHardness(class_4970.java:5653) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java) ~[client-intermediary.jar:?]
	at baritone.utils.ToolSet.calculateSpeedVsBlock(ToolSet.java:180) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.utils.ToolSet.getBestSlot(ToolSet.java:135) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.utils.ToolSet.getBestDestructionTime(ToolSet.java:163) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.function.Function.lambda$compose$0(Unknown Source) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at baritone.utils.ToolSet.getStrVsBlock(ToolSet.java:75) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.pathing.movement.MovementHelper.getMiningDurationTicks(MovementHelper.java:606) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.plausibleToBreak(MineProcess.java:469) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.lambda$prune$11(MineProcess.java:429) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at baritone.process.MineProcess.prune(MineProcess.java:444) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.searchWorld(MineProcess.java:377) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.rescan(MineProcess.java:238) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.lambda$onTick$1(MineProcess.java:112) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[21:21:12] [pool-9-thread-5/ERROR]: Uncaught exception in thread "pool-9-thread-5"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
	at net.minecraft.class_4970$class_4971.handler$hlb000$interference$getHardness(class_4970.java:5653) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java) ~[client-intermediary.jar:?]
	at baritone.utils.ToolSet.calculateSpeedVsBlock(ToolSet.java:180) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.utils.ToolSet.getBestSlot(ToolSet.java:135) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.utils.ToolSet.getBestDestructionTime(ToolSet.java:163) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.function.Function.lambda$compose$0(Unknown Source) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at baritone.utils.ToolSet.getStrVsBlock(ToolSet.java:75) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.pathing.movement.MovementHelper.getMiningDurationTicks(MovementHelper.java:606) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.plausibleToBreak(MineProcess.java:469) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.lambda$prune$11(MineProcess.java:429) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at baritone.process.MineProcess.prune(MineProcess.java:444) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.searchWorld(MineProcess.java:377) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.rescan(MineProcess.java:238) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at baritone.process.MineProcess.lambda$onTick$1(MineProcess.java:112) ~[baritone-unoptimized-fabric-1.9.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[21:21:14] [Render thread/INFO]: [CHAT] [Baritone] > stop
[21:21:14] [Render thread/INFO]: [CHAT] [Baritone] > stop
[21:21:14] [Render thread/INFO]: [CHAT] [Baritone] ok canceled
[21:21:14] [Render thread/INFO]: [CHAT] [Baritone] ok canceled`

I'm still getting it.

**Comment by ZacSharp** [comment]
Ok, if this is really happening on a "fixed" version (afaik there is no unfixed version for 1.19.4), can you please
1. provide a full log? You can put it inside a `<details><summary>log</summary> . . . log here . . .  </details>` spoiler or drag and drop the file into the comment to avoid flooding the thread.
2. try removing mods and see whether one of them causes the exception?

**Comment by EvilEpicPanda** [comment]
I'll try removing mods, but for now, here is my latest log.

[latest.log](https://github.com/cabaletta/baritone/files/11524861/latest.log)

**Comment by wagyourtail** [comment]
@ZacSharp from the original log, (and the new one) this is a different bug... 
world is null at a different place
> at net.minecraft.class_4970$class_4971.handler$hlc000$interference$getHardness(class_4970.java:5653) ~[client-intermediary.jar:?]

which is related to a different list of issues (ie. carpetmod forks like https://github.com/RubixDev/Rug/issues/44)

now, there are legitimate reasons to get the world in a mod. so it may stay incompatible. but if we figure out which mod it is, that would be very useful. the fastest way to do so is:
1. Remove half of your mods and see if the issue still persists 
2. If the issue is still happening then you know the issue is within this half, If the issue does not still happen it is within the half that you removed 
3. Get the chunk of mods that the issue is still within and repeat until you find the trouble mod

**Comment by ZacSharp** [comment]
Yeah, I pretty much stopped when I saw that the error message was identical and the stack trace was obfuscated baritone names + in a command.

Looking at the log I think Interference (added by Redbits) is the problem. They have a mixin which unconditionally uses the world and position parameters (Baritone passes null for both when checking tool speed) to obtain the blockstate at that position and then decide whether it has dynamic hardness.

**Comment by wagyourtail** [comment]
You sure its redbits? https://github.com/magistermaks/mod-redbits/tree/master/src%2Fmain%2Fjava%2Fnet%2Fdarktree%2Fredbits%2Fmixin not seeing a mixin here

**Comment by ZacSharp** [comment]
I said it's a dependency they ship.
The mixin hides [here](https://github.com/magistermaks/mod-redbits/blob/176be5f5f7b70a5107847e0d7753a617a8a4bb35/build.gradle#L65) and the code I'm talking about is [here](https://github.com/magistermaks/mod-interference/blob/4270b7dfc547a89fca966043ebc8aa1f271c88fd/src/main/java/net/darktree/interference/mixin/HardnessMixin.java#L18).

**Comment by wagyourtail** [comment]
Ahh. I see... well... one things redundant there. but wont be fixable in all cases

**Comment by ZacSharp** [comment]
Maybe, but the nasty party here is definitely us. We're passing null for nonnull parameters and not even catching the exception.

**Comment by ZacSharp** [comment]
Just noticed (from the pr mentioned in the Rug issue mentioned above) that Interference is also just getting `this`.
That's probably the reason why vanilla doesn't use the parameters. All you can do with them without doing crazy things ("my block is as hard as the block below it") is getting `this`.

**Comment by ThGrSoRu** [comment]
I also recently encountered this issue. The mod that caused it was [Light Emitting Diode](https://modrinth.com/mod/led) `1.6.0` for `1.20.1`.
