### ISSUE TITLE
acceptableThrowawayItems bug?

### ISSUE THREAD

**Issue by niggish** [cabaletta/baritone#406]
### **baritone?**

**if adding a block for `acceptableThrowawayItems` is misspelled/invalid, your game crashes and all baritone settings reset
i typed ``andestite`` instead of ``andesite`` and crashed**

- Impact Version: `4.6 for 1.13.2`
- Using Optifine? `yes`
- Using LiteLoader? `no`
- Enabled mods: `barit0ne`
- Operating System: `windows 10 64-bit`

**Comment by leijurv** [comment]
I blame @ZeroMemes  lol

```
java.lang.NullPointerException: Updating screen events
	at baritone.api.utils.SettingsUtil$Parser.lambda$static$4(SettingsUtil.java:186)
	at baritone.api.utils.SettingsUtil$Parser.lambda$new$5(SettingsUtil.java:232)
	at baritone.api.utils.SettingsUtil$Parser.toString(SettingsUtil.java:242)
	at baritone.api.utils.SettingsUtil$Parser$1.lambda$toString$1(SettingsUtil.java:205)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at baritone.api.utils.SettingsUtil$Parser$1.toString(SettingsUtil.java:206)
	at baritone.api.utils.SettingsUtil.settingToString(SettingsUtil.java:126)
	at baritone.api.Settings$Setting.toString(Settings.java:862)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:169)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:101)
```

it sets it to a list containing null without throwing an exception that the setting is invalid, then reads it later

gotta figure out in the new parser system how to make it actually cause an exception on invalid input instead of setting the setting to null smh

**Comment by niggish** [comment]
same ik im helpful 😘
