### ISSUE TITLE
bot-system cant add bots

### ISSUE THREAD

**Issue by lokzz** [cabaletta/baritone#4069]
## Some information
Operating system: win10
Java version: jdk 1.8
Minecraft version: 1.12.2 forge
Baritone version: bot-system: baritone-api-forge-1.2.17
Other mods (if used): none

## Exception, error or logs
```
[14:50:43] [Client thread/INFO]: [CHAT] [Baritone] > bot add
[14:50:43] [Client thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchFieldError: field_78878_a
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ch.execute(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ai.a(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ai.onSendChatMessage(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ci.a(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ci$$Lambda$283/74285291.accept(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ci.onSendChatMessage(Unknown Source)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:50:43] [Client thread/INFO]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchFieldError: field_78878_a
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.t.a(Unknown Source)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.l.<init>(Unknown Source)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.n.a(Unknown Source)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.n.connect(Unknown Source)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.aq.execute(Unknown Source)
[14:50:43] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 24 more
```

## How to reproduce
1. build & put `baritone-api-forge-1.2.17.jar` in mods folder
2. start minecraft forge 1.12.2
3. join game & turn on lan
4. run `bot a`

## Modified settings
N/A

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by lokzz** [comment]
this works if started in gradlew/IDEA ide
