### ISSUE TITLE
The game crashing

### ISSUE THREAD

**Issue by yakyyakyyou2** [cabaletta/baritone#4080]
## whenever i press play the lawncher dissapears and then reopens saying the game crashed with exit code 1
Operating system: macOS big sur 11.6
Java version: 8 i think
Minecraft version: 1.12.2
Baritone version: 1.2.17
Other mods (if used): anti gost, apple skin, autoreglib, better fps, dupe triger, better therd person, equpment compear, find me, forgewld, fps redjuser, hwla, inventory sorter, itit, jei, jei intergration, jie villigers, JEROreintergration, juorney map, just enough calculation, just enough resorces, luna truscore, mod name tool tip, optifine, quark, rusher hack, schimatica, that one probe, torro health, whaila harvistabilety, would downloader mod, wourld edit, xearos mini map.

## finnested with exit code 1

[17:39:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:39:38] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:39:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:39:38] [main/INFO]: Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading
[17:39:38] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_74, running on Mac OS X:x86_64:10.16, installed at /Users/thomaspowers/Documents/curseforge/minecraft/Install/runtime/jre-legacy/mac-os/jre-legacy/jre.bundle/Contents/Home
[17:39:38] [main/INFO]: Searching /Users/thomaspowers/Documents/curseforge/minecraft/Instances/2b2t/mods for mods
[17:39:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from baritone-api-forge-1.2.17.jar
[17:39:38] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8 16.16.52 14.19.15.jar
[17:39:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from BetterThirdPerson-Forge-1.12.2-1.9.0.jar
[17:39:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from EquipmentCompare-1.12.2-1.3.4.jar
[17:39:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from forgewdl-4.0.1.7-release (2) 16.16.52 14.19.15.jar
[17:39:38] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5 16.16.52 14.19.15.jar
[17:39:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[17:39:38] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[17:39:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from rusherhack-loader.jar
[17:39:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:39:38] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:39:38] [main/ERROR]: Catching
org.spongepowered.asm.service.ServiceInitialisationException: ModLauncher is not available
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap.bootstrap(MixinServiceModLauncherBootstrap.java:52) ~[BetterThirdPerson-Forge-1.12.2-1.9.0.jar:1.9.0]
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:79) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [baritone-api-forge-1.2.17.jar:1.2.17]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_74]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:39:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/Users/thomaspowers/Documents/curseforge/minecraft/Instances/2b2t/mods/baritone-api-forge-1.2.17.jar Service=LaunchWrapper Env=CLIENT
[17:39:38] [main/DEBUG]: Instantiating coremod class ForgeWDL
[17:39:38] [main/WARN]: The coremod net.futureclient.forgewdl.ForgeWDL does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:39:38] [main/WARN]: The coremod ForgeWDL (net.futureclient.forgewdl.ForgeWDL) is not signed!
[17:39:38] [main/ERROR]: Coremod ForgeWDL: The plugin net.futureclient.forgewdl.ForgeWDL is not an implementor of IFMLLoadingPlugin
java.lang.ClassCastException: net.futureclient.forgewdl.ForgeWDL cannot be cast to net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) [forge-1.12.2-14.23.5.2859.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.injectCorePlugin(MixinPlatformAgentFML.java:228) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.initFMLCoreMod(MixinPlatformAgentFML.java:155) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.<init>(MixinPlatformAgentFML.java:134) [baritone-api-forge-1.2.17.jar:1.2.17]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_74]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:68) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:142) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:113) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:106) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:158) [baritone-api-forge-1.2.17.jar:1.2.17]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [baritone-api-forge-1.2.17.jar:1.2.17]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_74]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:39:38] [main/DEBUG]: Instantiating coremod class MixinLauncher
[17:39:39] [main/TRACE]: coremod named RusherHack-Loader is loading
[17:39:39] [main/DEBUG]: The coremod org.rusherhack.launcher.launch.MixinLauncher requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[17:39:39] [main/WARN]: The coremod RusherHack-Loader (org.rusherhack.launcher.launch.MixinLauncher) is not signed!
[17:39:39] [main/INFO]: --------------------------------------------------------------
[17:39:39] [main/INFO]: Initializing RusherHack
[17:39:39] [main/INFO]: --------------------------------------------------------------
[17:39:39] [main/INFO]: --------------------------------------------------------------
[17:39:39] [main/INFO]: RusherHack auth files found. Username: yakyyakyyou
[17:39:39] [main/INFO]: --------------------------------------------------------------
[17:39:40] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[17:39:40] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[17:39:40] [main/INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[17:39:47] [main/INFO]: --------------------------------------------------------------
[17:39:47] [main/INFO]: 1 Loaded org.rusherhack.client.RusherHack.class
[17:39:47] [main/INFO]: --------------------------------------------------------------
[17:39:47] [main/INFO]: Compatibility level set to JAVA_8
[17:39:47] [main/ERROR]: Mixin config mixins.rusherhack.json does not specify "minVersion" property
[17:39:47] [main/DEBUG]: Enqueued coremod RusherHack-Loader
[17:39:47] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[17:39:47] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[17:39:47] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[17:39:47] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[17:39:47] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:39:47] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[17:39:47] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:39:47] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:39:47] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:39:47] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[17:39:47] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[17:39:47] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[17:39:47] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[17:39:47] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: /Users/thomaspowers/Documents/curseforge/minecraft/Instances/2b2t/mods/OptiFine_1.12.2_HD_U_G5 16.16.52 14.19.15.jar
[17:39:47] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:39:47] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[17:39:47] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[17:39:47] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[17:39:47] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[17:39:47] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[17:39:47] [main/DEBUG]: Injection complete
[17:39:47] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[17:39:47] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[17:39:49] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:39:49] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:39:49] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[17:39:49] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:39:49] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[17:39:49] [main/DEBUG]: Injection complete
[17:39:49] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[17:39:49] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[17:39:49] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[17:39:49] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[17:39:49] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property
[17:39:49] [main/WARN]: Mixin config mixins.betterthirdperson.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.betterthirdperson.json requires mixin subsystem version 0.8
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:159)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:183)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:53)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[17:39:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## use the mod on the cursforge app open the lawncher and press the green play button near the botton of the screen.
Add your steps to reproduce the issue/bug experienced here.

To get the modified settings run `#modified` in game (cant cz the game doesnt open)

## Final checklist
- [ ] I know how to properly use check boxes  (no)
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue. 
[latest.log](https://github.com/cabaletta/baritone/files/12209730/latest.log)

**Comment by yakyyakyyou2** [comment]
omg im so f*cking useless that report sucked

**Comment by wagyourtail** [comment]
Add mixinbootstrap mod and hope it works https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap but you may have a mod thats incompatible... baritone uses an older version than one of your other mods requires, and that ahould at least fix that error
