### ISSUE TITLE
NPE on #stop while building .schematic

### ISSUE THREAD

**Issue by VADemon** [cabaletta/baritone#416]
Tried to build a schematic, testing out different options. A couple of times `#stop` worked, but this time it crashed. (that for sure is a way to *stop* too)

Version: baritone-api-forge-1.2.6.jar for 1.12.2

```
java.lang.NullPointerException: Unexpected error
	at baritone.bt.widthX(Unknown Source)
	at baritone.api.utils.ISchematic.inSchematic(Unknown Source)
	at baritone.bv.b(Unknown Source)
	at baritone.bv.a(Unknown Source)
	at baritone.bl.a(Unknown Source)
	at baritone.bl.a(Unknown Source)
	at baritone.bo.a(Unknown Source)
	at baritone.bo.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at baritone.x.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zbk000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1753)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
```

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/da8bf6b1b3c8a3d0e428874de906fc4c2ff29f56
