### ISSUE TITLE
When i do #mine minecraft:diamond_ore it says an unhandled exception occured. The error is in your game's log

### ISSUE THREAD

**Issue by lucacak** [cabaletta/baritone#4208]
## Some information
Operating system:windows 10
Java version:
Minecraft version:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by knatterfurzzz** [comment]
i have the same problem:

[15:06:45] [pool-11-thread-1401/ERROR]: Uncaught exception in thread "pool-11-thread-1401"
java.lang.ArrayIndexOutOfBoundsException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor129.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689) ~[?:?]
	at java.util.stream.SliceOps$1.opEvaluateParallelLazy(SliceOps.java:151) ~[?:?]
	at java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:434) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at baritone.r.a(Unknown Source) ~[baritone-1.20.2.jar:?]
	at baritone.r.scanChunkRadius(Unknown Source) ~[baritone-1.20.2.jar:?]
	at baritone.ej.a(Unknown Source) ~[baritone-1.20.2.jar:?]
	at baritone.ej.a(Unknown Source) ~[baritone-1.20.2.jar:?]
	at baritone.ej.b(Unknown Source) ~[baritone-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor129.newInstance(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.stream.SliceOps$1.opEvaluateParallelLazy(SliceOps.java:151)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:434)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at baritone.r.a(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at baritone.r.scanChunkRadius(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at baritone.ej.a(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at baritone.ej.a(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at baritone.ej.b(Unknown Source)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:45] [pool-11-thread-1402/INFO]: [STDERR]: Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by wagyourtail** [comment]
duplicate #4112
