### ISSUE TITLE
unable to load into Minecraft

### ISSUE THREAD

**Issue by oakleyplays** [cabaletta/baritone#4277]
## unable to load into Minecraft
Operating system: macOS ventura 13.6.4
Java version: latest version
Minecraft version: 1.20.4
Baritone version: 1.20.4
Other mods (if used): none

## How to reproduce
don't know how

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
"Error code 255" is really little information and if that is all you can give us it is unlikely someone will find a solution other than by trial and error.
Have you tried removing mods to see whether it works without?

**Comment by oakleyplays** [comment]
> "Error code 255" is really little information and if that is all you can give us it is unlikely someone will find a solution other than by trial and error.
> Have you tried removing mods to see whether it works without?

oh yeah sorry, I forgot to sent the full error it says this, and it crashes at the "state transitions LOAD_REGISTRIES running" command when it boots into forge
<img width="870" alt="Screenshot 2024-02-17 at 10 17 44 PM" src="https://github.com/cabaletta/baritone/assets/134006047/e7738f5d-a05e-4a62-a010-962a01333431">

**Comment by ZacSharp** [comment]
I'd need the crash report to be sure (you can get it by clicking on "view crash report" in case that's not obvious) though my guess is that you are running into the bug fixed by #4244. The crash report should say something about a `ClassCastException` in that case.

**Comment by oakleyplays** [comment]
the whole crash says: "---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-02-18 17:38:02
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.Minecraft.handler$zzh000$postInit(Minecraft.java) ~[forge-1.20.4-49.0.30-client.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:616) ~[forge-1.20.4-49.0.30-client.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:196) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97) ~[bootstrap-2.0.0.jar!/:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48) ~[bootstrap-2.0.0.jar!/:?] {}
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18) ~[bootstrap-2.0.0.jar!/:?] {}
Caused by: java.lang.ClassCastException: class baritone.ep cannot be cast to class baritone.dy (baritone.ep and baritone.dy are in module baritoe@1.10.2 of loader 'TRANSFORMER' @1ba467c2)
	at baritone.a.<init>(Unknown Source) ~[baritone-api-forge-1.10.2.jar!/:1.10.2] {re:classloading,re:mixin}
	at baritone.BaritoneProvider.createBaritone(Unknown Source) ~[baritone-api-forge-1.10.2.jar!/:1.10.2] {re:classloading}
	at baritone.BaritoneProvider.<init>(Unknown Source) ~[baritone-api-forge-1.10.2.jar!/:1.10.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] {}
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?] {}
	at java.lang.Class.newInstance(Class.java:645) ~[?:?] {re:mixin}
	at baritone.api.BaritoneAPI.<clinit>(Unknown Source) ~[baritone-api-forge-1.10.2.jar!/:1.10.2] {re:mixin,re:classloading}
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Baritone (baritoe), Version: 1.10.2
		Issue tracker URL: https://github.com/cabaletta/baritone/issues
		Mixin class: baritone.launch.mixins.MixinMinecraft
		Target: net.minecraft.client.Minecraft
		at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.Minecraft.handler$zzh000$postInit(Minecraft.java)
Stacktrace:
	at net.minecraft.client.Minecraft.handler$zzh000$postInit(Minecraft.java) ~[forge-1.20.4-49.0.30-client.jar!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:616) ~[forge-1.20.4-49.0.30-client.jar!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:196) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97) ~[bootstrap-2.0.0.jar!/:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48) ~[bootstrap-2.0.0.jar!/:?] {}
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18) ~[bootstrap-2.0.0.jar!/:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (x86_64) version 13.6.4
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 354767496 bytes (338 MiB) / 738197504 bytes (704 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 70 Stepping 1
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Pro
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0d26
	Graphics card #0 versionInfo: Revision ID: 0x0008
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 7498.76
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.4-forge-49.0.30
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2+13
	Backend API: Intel Iris Pro OpenGL Engine GL version 4.1 INTEL-18.8.4, Intel Inc.
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: 8x Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	ModLauncher: 10.1.2
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@49
		minecraft@1.0
		javafml@49.0.30
	Mod List: 
		forge-1.20.4-49.0.30-client.jar                   |Minecraft                     |minecraft                     |1.20.4              |SIDED_SETU|Manifest: NOSIGNATURE
		baritone-api-forge-1.10.2.jar                     |Baritone                      |baritoe                       |1.10.2              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.20.4-49.0.30-universal.jar                |Forge                         |forge                         |49.0.30             |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: d2bfde6a-2df4-445f-9d96-bf9bbe93b1d5
	FML: 0.0
	Forge: net.minecraftforge:49.0.30"

**Comment by ZacSharp** [comment]
Yes, that's #4244. If you want a fix already you'll have to build Baritone yourself with the change from the pr applied. If you can wait there will also eventually (probably this week) be CI builds with the fix for 1.20.4 and at some point also a release.
EDIT: there is #4280 now. CI builds from that pr have the fix.
EDIT2: #4280 is merged so any new enough 1.20.4 build has the fix
