### ISSUE TITLE
crash on custom goal request

### ISSUE THREAD

**Issue by Redhawk18** [cabaletta/baritone#4307]
```java
case ShulkerSearchPathing: {
    if (baritone.getCustomGoalProcess().isActive()) {
        Helper.HELPER.logDirect("custom goal to path to shulker");
        return; // Wait to get there
    }

    curCheckingShulker = getShulkerToCheck();
    Helper.HELPER.logDirect("found current shulker: " + curCheckingShulker.toString());
    if (curCheckingShulker == null) {
        ...
    }

    Optional<Rotation> shulkerReachable = RotationUtils.reachable(ctx.player(), curCheckingShulker,
            ctx.playerController().getBlockReachDistance());

    if (shulkerReachable.isPresent()) {
        ...
    } else {
        Helper.HELPER.logDirect("Going to shulker");
        // crash happens here vvv
        baritone.getCustomGoalProcess().setGoalAndPath(new GoalBlock(getPathingSpotByShulker(curCheckingShulker)));
    }
    break;
}
```

This leads to this error 
```java
[19:38:34] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Multiple entries with same key: class_2338{x=-322, y=63, z=-61}=net.minecraft.class_2627@5c367bff and BetterBlockPos{x=-322,y=63,z=-61}=net.minecraft.class_2627@32300150
``` 
and crashes the rendering thread so crashing the game.

**Comment by ZacSharp** [comment]
Did you find the reason for the crash?

**Comment by Redhawk18** [comment]
> Did you find the reason for the crash?

I haven't I'm going to circle back because I just found out how to turn off obfuscation for baritone

**Comment by Redhawk18** [comment]
> Did you find the reason for the crash?

i just fixed it, the problem was that baritone would insert a `BetterBlockPos` into it the map of blockpos that minecraft uses cause them to collide. This is the code that fixed it, while it does get ride of a lot of the gains `BetterBlockPos` gives it's worth it to not have my game crash. 
```git
--- a/src/api/java/baritone/api/utils/BetterBlockPos.java
+++ b/src/api/java/baritone/api/utils/BetterBlockPos.java
@@ -80,7 +80,7 @@ public final class BetterBlockPos extends BlockPos {
 
     @Override
     public int hashCode() {
-        return (int) longHash(x, y, z);
+        return super.hashCode();
     }
```

While this works, a better solution for upstream should be implemented.

**Comment by ZacSharp** [comment]
What would such a fix look like?
* Not extending `BlockPos`. A very disruptive change for anyone using `BetterBlockPos` and making it far less convenient to use.
* Making `BetterBlockPos` compare not equal to any `BlockPos`. Confusing and annoying to work with.
* Fix the place inserting the `BetterBlockPos` and hope things work for another five years without breaking.

**Comment by Redhawk18** [comment]
> What would such a fix look like?
> 
>     * Not extending `BlockPos`. A very disruptive change for anyone using `BetterBlockPos` and making it far less convenient to use.
> 
>     * Making `BetterBlockPos` compare not equal to any `BlockPos`. Confusing and annoying to work with.
> 
>     * Fix the place inserting the `BetterBlockPos` and hope things work for another five years without breaking.

I have no idea, but correct is better than incorrect with any speed up.

**Comment by ZacSharp** [comment]
Can you maybe provide the place leaking the `BetterBlockPos`? Reproducing on your branch failed and I currently don't have the time to figure it out using just the error message.

**Comment by Redhawk18** [comment]
> Can you maybe provide the place leaking the `BetterBlockPos`? Reproducing on your branch failed and I currently don't have the time to figure it out using just the error message.

This is what I was told by a friend who's one of the lead meteor maintainers.

> this would only happen if you
* 1. call WorldChunk#addBlockEntity or WorldChunk#setBlockEntity with
* 2. a block entity where BlockEntity#getPos is a baritone BetterBlockPos

We likely have a problem with the 2nd one, it seems baritone doesn't often do this so this must have never got caught.

**Comment by mankool0** [comment]
I ran into this and managed to replicate it.
Here are the steps:
1. Place down multiple shulkers (it can happen with just one but is more reliable with multiple)
2. Log out or save the game to get to the main menu
3. Join your world again
4. Run clear area on the shulkers
5. Wait for it to crash as it clears

If it doesn't crash during the clear it can crash as you replace the shulkers that were mined.
To find the place leaking the BetterBlockPos I hooked the `setBlockEntity` method in `LevelChunk` and logged the stack trace if the `BlockEntity::getBlockPos` returned a `BetterBlockPos`

Minecraft logs this warning when the leak happens:
`[Render thread/WARN]: Block entity minecraft:shulker_box @ BetterBlockPos{x=7,y=-60,z=-9} state Block{minecraft:air} invalid for ticking:`

Here's my stack trace of the main location that causes this crash:
```Java
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.chunk.LevelChunk.setBlockEntity(LevelChunk.java)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.chunk.LevelChunk.addAndRegisterBlockEntity(LevelChunk.java:350)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.chunk.LevelChunk.getBlockEntity(LevelChunk.java:338)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.Level.getBlockEntity(Level.java:596)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.ShulkerBoxBlock.getShape(ShulkerBoxBlock.java:231)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getShape(BlockBehaviour.java:1058)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getShape(BlockBehaviour.java:1054)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.state.BlockBehaviour.getCollisionShape(BlockBehaviour.java:355)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getCollisionShape(BlockBehaviour.java:1069)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getCollisionShape(BlockBehaviour.java:1065)
[Render thread/INFO]: [STDERR]: 	at baritone.api.utils.VecUtils.calculateBlockCenter(VecUtils.java:47)
[Render thread/INFO]: [STDERR]: 	at baritone.api.utils.RotationUtils.reachableCenter(RotationUtils.java:261)
[Render thread/INFO]: [STDERR]: 	at baritone.api.utils.RotationUtils.reachable(RotationUtils.java:200)
[Render thread/INFO]: [STDERR]: 	at baritone.api.utils.RotationUtils.reachable(RotationUtils.java:174)
[Render thread/INFO]: [STDERR]: 	at baritone.process.BuilderProcess.toBreakNearPlayer(BuilderProcess.java:300)
[Render thread/INFO]: [STDERR]: 	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:546)
[Render thread/INFO]: [STDERR]: 	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:450)
[Render thread/INFO]: [STDERR]: 	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:199)
[Render thread/INFO]: [STDERR]: 	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:90)
[Render thread/INFO]: [STDERR]: 	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:104)
[Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:64)
[Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:64)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.handler$zzi000$baritone$runTick(Minecraft.java:3235)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.tick(Minecraft.java:1929)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1246)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:882)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

And the snippet inside `BuilderProcess::toBreakNearPlayer`:
```Java
if (!(curr.getBlock() instanceof AirBlock) && !(curr.getBlock() == Blocks.WATER || curr.getBlock() == Blocks.LAVA) && !valid(curr, desired, false)) {
    BetterBlockPos pos = new BetterBlockPos(x, y, z);
    Optional<Rotation> rot = RotationUtils.reachable(ctx, pos, ctx.playerController().getBlockReachDistance());
    if (rot.isPresent()) {
        return Optional.of(new Tuple<>(pos, rot.get()));
    }
}
```

Fixing this inside this area does fix it but looking at the calls to `RotationUtils.reachable` there are more locations that this can happen at.


How would you like me to resolve this? I can go through every spot that calls `RotationUtils.reachable` and make sure it's not a `BetterBlockPos` or add a check inside `RotationUtils.reachable` to make sure it's correct.

**Comment by ZacSharp** [comment]
@mankool0 thank you for hunting this one down! As for where to fix this: definitely inside `RotationUtils.reachable` and not at its call sites.
