### ISSUE TITLE
Impossible to use elytra fly on nether's roof

### ISSUE THREAD

**Issue by AnabolicRoo** [cabaletta/baritone#4356]
## Some information
Operating system: Linux
Java version: /
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): /

## Exception, error or logs
The y of the goal is not between 0 and 128

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Go on the roof of the nether and use elytra feature to go to coordinates

## Modified settings
X

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by YoJames2019** [comment]
And if you manually set the y to 127, it fails with this error

`[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: java.lang.IllegalArgumentException: Invalid y1 or y2
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at dev.babbaj.pathfinder.NetherPathfinder.pathFind(Native Method)
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at baritone.js.a(Unknown Source)
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:57:09] [pool-110-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by 1s0n** [comment]
yea i think the pathfinder cant pathfind above nether roof or smt, because even if i use the goto command it still breaks above nether roof, throwing the exact same exception

**Comment by 1s0n** [comment]
it might just be a hardcoded limit, and i can't change it since the pathfinder itself seems to be proprietary or sum

**Comment by ZacSharp** [comment]
The elytra pathfinder does indeed only work below the nether ceiling so rejecing goals outside that range is intentional.
I hardly know the elytra pathfinder code so I don't know how hard it is to change that. If you want to give it a try you can find the code [here](https://github.com/babbaj/nether-pathfinder).

**Comment by AnabolicRoo** [comment]
Has this been fixed?
