### ISSUE TITLE
Crash mining large areas of sand with cleararea in 1.13.2

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#443]
Reported on discord, but didnt want to make a github issue so I'm pasting his stacktrace

```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at baritone.bl.a(Unknown Source)
	at baritone.ac.update(Unknown Source)
	at baritone.bo.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$2549/659134474.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onTick(Unknown Source)
	at cft.handler$runTick$zei000(SourceFile)
	at cft.m(SourceFile:1244)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by babbaj** [comment]
cringe
