### ISSUE TITLE
Unhandled exception when using #elytra

### ISSUE THREAD

**Issue by Fort-P** [cabaletta/baritone#4431]
## Some information
Operating system: Windows
Java version: 21.0.3
Minecraft version: 1.20.4
Baritone version:
Other mods (if used): 

## Exception, error or logs
```
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: java.lang.IllegalArgumentException: Invalid y1 or y2
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at dev.babbaj.pathfinder.NetherPathfinder.pathFind(Native Method)
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at baritone.process.elytra.NetherPathfinderContext.a(Unknown Source)
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:41:08] [pool-10-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[16:41:08] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:41:08] [Render thread/INFO]: [CHAT] [Baritone] > cancel
[16:41:08] [Render thread/INFO]: [CHAT] [Baritone] ok canceled
```

## How to reproduce
go to the nether roof, set a goal, and then run the elytra command

## Modified settings
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] > modified
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] All modified settings:
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] acceptableThrowawayItems (List<class_1792>)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowDiagonalAscend (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowDiagonalDescend (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowInventory (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowJumpAt256 (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowParkour (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] allowParkourPlace (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] avoidance (Boolean)
[16:44:00] [Render thread/INFO]: [CHAT] [Baritone] << | >> 1/2
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] > set modified  2
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] All modified settings:
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] desktopNotifications (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] elytraAutoJump (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] elytraTermsAccepted (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] freeLook (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] itemSaver (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] smoothLook (Boolean)
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] --
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] --
[16:44:05] [Render thread/INFO]: [CHAT] [Baritone] << | >> 2/2

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment]
`#elytra` is not made to work outside the normal 0 to 128 height range in the nether. There could be a better error message though. (or someone could remove that limitation)

**Comment by Fort-P** [comment]
Yeah, that doesn't make sense to have as a limitation. It would be even
easier to implement the flight on the roof, as there aren't any
obstructions to bump into, and you could just travel straight to your
destination. Also doesn't really make sense to have the overworld/end
blacklisted.

**Comment by ZacSharp** [comment]
Nah, it would still have to handle human-made obstacles. Those limitations do actually make sense in some way:
* Not allowing y coordinates above 128 cuts the cache size in half and might also have a slight speed benefit
* The pathfinder has built in terrain generation to predict terrain way out of render distance, which is obviously dimension specific.

So yes, if the current features are all you need it makes sense to keep those limitations, but I think flying elsewhere is a reasonable enough thing to do to drop them.
