### ISSUE TITLE
Error when using litematica command

### ISSUE THREAD

**Issue by IVIPOWER** [cabaletta/baritone#4543]
## Some information
Operating system: Win10
Java version: Lastest (i believe)
Minecraft version: 1.21.1
Baritone version: idk
Other mods (if used): a ton 

## Exception, error or logs
do i really need it?

## How to reproduce
Loaded an schematic and did #litematica then error happened

## Modified settings
NONE

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

Edit, mb, i missclicked

**Comment by IVIPOWER** [comment]
nvm i fixed it

**Comment by liassssa** [comment]
how did you fix it?

**Comment by IVIPOWER** [comment]
Idk, i resetted my pc and it worked for a whole week, yesterday which was the last time i used this command it didnt work either, idk what happen, hopefully some mod or someone that knows helps us

**Comment by ZacSharp** [comment]
> Baritone version: idk

would be nice to know, there have been some [substantial changes](https://github.com/cabaletta/baritone/pull/4453) to litematic handling

> # Exception, error or logs
> do i really need it?

You don't, but the people you expect help from might themselves get some information from it.

> Other mods (if used): a ton

Having tons of mods installed doesn't help either. Mods can change a lot of things in very different ways and understanding what happens with tons of unknown mods installed is plain impossible.

So far this issue is just another one where someone has a problem and either updating will fix it or there is no chance to find the cause, because there is literally no information to use.

**Comment by IVIPOWER** [comment]
> > Baritone version: idk
> 
> would be nice to know, there have been some [substantial changes](https://github.com/cabaletta/baritone/pull/4453) to litematic handling
> 
> > # Exception, error or logs
> > do i really need it?
> 
> You don't, but the people you expect help from might themselves get some information from it.
> 
> > Other mods (if used): a ton
> 
> Having tons of mods installed doesn't help either. Mods can change a lot of things in very different ways and understanding what happens with tons of unknown mods installed is plain impossible.
> 
> So far this issue is just another one where someone has a problem and either updating will fix it or there is no chance to find the cause, because there is literally no information to use.

on the mod info i had appleskins, jei, litematica, and other vanilla+ mods like trading refresh, i dont think it affects that much to the command, but ill try going mod by mod by moving it outside the folder and find the issue, im not home now so cant send log

**Comment by IVIPOWER** [comment]
[CHAT] [Baritone] > litematica
[Info: 2024-11-19 19:20:56.9193190: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_338 (Render thread) Info [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[Info: 2024-11-19 19:20:56.9194923: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchMethodError: 'net.minecraft.class_2680 fi.dy.masa.litematica.world.WorldSchematic.getBlockState(net.minecraft.class_2338)'
[Info: 2024-11-19 19:20:56.9195562: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.bs.execute(Unknown Source)
[Info: 2024-11-19 19:20:56.9196479: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.w.a(Unknown Source)
[Info: 2024-11-19 19:20:56.9196881: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[Info: 2024-11-19 19:20:56.9197815: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.bt.a(Unknown Source)
[Info: 2024-11-19 19:20:56.9198332: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[Info: 2024-11-19 19:20:56.9198721: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.bt.onSendChatMessage(Unknown Source)
[Info: 2024-11-19 19:20:56.9199078: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_634.handler$zbp000$baritone$sendChatMessage(class_634.java)
[Info: 2024-11-19 19:20:56.9199418: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[Info: 2024-11-19 19:20:56.9199873: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:260)
[Info: 2024-11-19 19:20:56.9200238: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:103)
[Info: 2024-11-19 19:20:56.9202176: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:414)
[Info: 2024-11-19 19:20:56.9203080: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:431)
[Info: 2024-11-19 19:20:56.9203635: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:410)
[Info: 2024-11-19 19:20:56.9203976: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:499)
[Info: 2024-11-19 19:20:56.9204306: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:108)
[Info: 2024-11-19 19:20:56.9204777: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:499)
[Info: 2024-11-19 19:20:56.9205135: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[Info: 2024-11-19 19:20:56.9205706: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[Info: 2024-11-19 19:20:56.9206083: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[Info: 2024-11-19 19:20:56.9206443: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
[Info: 2024-11-19 19:20:56.9206828: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
[Info: 2024-11-19 19:20:56.9207559: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:303)
[Info: 2024-11-19 19:20:56.9208286: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1307)
[Info: 2024-11-19 19:20:56.9208661: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[Info: 2024-11-19 19:20:56.9212238: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[Info: 2024-11-19 19:20:56.9212580: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[Info: 2024-11-19 19:20:56.9214141: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Info: 2024-11-19 19:20:56.9214662: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[Info: 2024-11-19 19:20:56.9215075: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2680 fi.dy.masa.litematica.world.WorldSchematic.getBlockState(net.minecraft.class_2338)'
[Info: 2024-11-19 19:20:56.9215508: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.utils.schematic.litematica.LitematicaHelper.a(Unknown Source)
[Info: 2024-11-19 19:20:56.9215946: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.dq.buildOpenLitematic(Unknown Source)
[Info: 2024-11-19 19:20:56.9216302: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	at baritone.bb.execute(Unknown Source)
[Info: 2024-11-19 19:20:56.9216656: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_2983 (Render thread) Info [STDERR]: 	... 28 more
[Info: 2024-11-19 19:20:57.5172971: NsvuwFtp2fA=: MinecraftJavaLoggingContext.cpp(65)] Game/net.minecraft.class_338 (Render thread) 

This is the log from one "#litematica" to another used consecutively, any help troubleshooting? i couldnt find anything on my own :c

**Comment by rfresh2** [comment]
resolved by https://github.com/cabaletta/baritone/pull/4560

**Comment by IVIPOWER** [comment]
so i just use that command?
im so clueless

**Comment by rfresh2** [comment]
no, the code changes have not been merged into baritone yet

the link i sent is the code changes that need to be made

but baritone maintainers will need to accept the changes, and then eventually merge the changes to 1.21.1

**Comment by IVIPOWER** [comment]
tysm, i got lost for a sec here, guess ill have to wait and hopefully they merge in 1.21.1, i have big proyects from my creative world i wanna add on my survival.. for now ill gather resources and do it by hand, hope they add it soon

**Comment by odd47** [comment]
I have this problem and I cant find any way to fix

**Comment by ZacSharp** [comment]
You need to update Baritone to a version with the fix. Since there is no release with the fix this means either building Baritone yourself or using a recent CI build (pick the latest entry for your Minecraft version from [this](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess%20event%3Apush) list, then download and unzip the "Artifacts" file at the bottom. You need to be logged in and the download is only available for 90 days).
