### ISSUE TITLE
Build command crashing

### ISSUE THREAD

**Issue by SongGame** [cabaletta/baritone#458]
I was experimenting with Baritone and I came across the build command. So I downloaded a schematic off of the internet. But when I did the command the game crashed. I tried downloading a small schematic but no change. If someone has a fix to this, help me.

**Comment by RaceVan** [comment]
i have the exact same problem, i dont really know how to use build, whenever i load a schematic it just crashes, even if i am in creative, survival, or i actually have the blocks needed for the build

**Comment by SkyNetCloud** [comment]
It's an Ids Crash for 1.13 I think

Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$3346/1621185605.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zeg000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at net.optifine.gui.GuiChatOF.e(GuiChatOF.java:41)
	at cjg.keyPressed(SourceFile:131)
	at cfq.lambda$onKeyEvent$4(KeyboardListener.java:378)
	at cfq$$Lambda$3333/228188394.run(Unknown Source)
	at ckd.a(SourceFile:430)
	at cfq.a(KeyboardListener.java:368)
	at cfq$$Lambda$850/1383367438.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(MainWindow.java:458)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by 0-x-2-2** [comment]
Yeah build won't work in 1.13 due to schematics having block ids and they got removed in 1.13

**Comment by ZeroMemes** [comment]
This is me when I utilize the hardcode in datafixeruppers to convert block ids to blocks in 1.13.2.

This conversion will remain in the game forever btw.

**Comment by 0-x-2-2** [comment]
> This is me when I utilize the hardcode in datafixeruppers to convert block ids to blocks in 1.13.2.
> 
> This conversion will remain in the game forever btw.

mojang sometimes removes this stuff after a few updates. proof: cant load beta world on 1.13.2

**Comment by LotDev** [comment]
Yea having the same issue on 1.13.2, but works fine on 1.12.2, would be nice if this could be fixed.

**Comment by leijurv** [comment]
> This is me when I utilize the hardcode in datafixeruppers to convert block ids to blocks in 1.13.2.

@ZeroMemes me when baritone + profunctor optics cocartesian crossover event?!?!??!? :heart_eyes_cat:

**Comment by Figrat** [comment]
> Yea having the same issue on 1.13.2, but works fine on 1.12.2, would be nice if this could be fixed.

how did it work for u and not for me ? can u tell me pls

**Comment by ZeroMemes** [comment]
>how did it work for u and not for me ? can u tell me pls

The problem is rooted in the 1.13.2 version.

**Comment by Figrat** [comment]
> > how did it work for u and not for me ? can u tell me pls
> 
> The problem is rooted in the 1.13.2 version.

im using 1.12.2

**Comment by ZeroMemes** [comment]
> im using 1.12.2

I can say for certain that the same issue isn't in 1.12.2, please provide your crash log in a new issue.

**Comment by Figrat** [comment]
> > im using 1.12.2
> 
> I can say for certain that the same issue isn't in 1.12.2, please provide your crash log in a new issue.

where do i check the crash log ?

**Comment by 0-x-2-2** [comment]
>where do i check the crash log ?

.minecraft

**Comment by Figrat** [comment]
> > where do i check the crash log ?
> 
> .minecraft

i need help about why everytime i want to build it just crash even tho im on 1.12.2

**Comment by 0-x-2-2** [comment]
> i need help about why everytime i want to build it just crash even tho im on 1.12.2

you need to send a crash report

**Comment by scottbeebiwan** [comment]
[crash-2019-07-10_12.23.17-client.txt](https://github.com/cabaletta/baritone/files/3379120/crash-2019-07-10_12.23.17-client.txt)
i have the same issue (1.13), and i assume this log does nothing to help, but thought i'd better post it anyway.
maybe you should be using a different file format?

**Comment by phaalonso** [comment]
`Time: 29/07/19 22:02
Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zeh000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(SourceFile:309)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by ActuallyGod** [comment]
Why keep the "#build (schematic)" thing if its impossible to use? :/
