### ISSUE TITLE
litematica command doesnt work (1.21.4 fabric)

### ISSUE THREAD

**Issue by yasuulein** [cabaletta/baritone#4592]
## Some information
Operating system: Win10
Java version: 8 update 401
Minecraft version: 1.21.4
Baritone version: 1.11.1
Other mods (if used): 

appleskin-fabric-mc1.21.3-3.0.6
camerautils-fabric-1.21.4-1.0.16
DetailArmorBar-2.6.3+1.21.3-fabric
essential_1-3-5-5_fabric_1-21-4
fabric-api-0.111.0+1.21.4
iris-fabric-1.8.3+mc1.21.4
journeymap-fabric-1.21.4-6.0.0-beta.32
Sakura-Ryoko-Litematica-Mod-Fabric-1.21.4
Sakura-Ryoko-MaLiLib-Fabric-1.21.4
shulkerboxtooltip-fabric-5.2.2+1.21.4
skinlayers3d-fabric-1.7.4-mc1.21.4
sodium-fabric-0.6.3+mc1.21.4
voicechat-fabric-1.21.4-2.5.26
worldedit-mod-7.3.9

I have following barritone .jar files installed:

baritone-api-fabric-1.11.1-1-g485bec05
baritone-standalone-fabric-1.11.1-1-g485bec05

## Exception, error or logs

[10:59:41] [Render thread/INFO]: [CHAT] [Baritone] > litematica
[10:59:41] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[10:59:41] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NoSuchMethodError: 'net.minecraft.class_2680 fi.dy.masa.litematica.world.WorldSchematic.getBlockState(net.minecraft.class_2338)'
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.bs.execute(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.w.a(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.w.onSendChatMessage(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.bt.a(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.bt.onSendChatMessage(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_634.handler$zzi000$baritone$sendChatMessage(class_634.java)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_634.method_45729(class_634.java)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_408.method_44056(class_408.java:260)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_408.method_25404(class_408.java:103)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_309.mixinextras$bridge$method_25404$39(class_309.java)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_309.wrapOperation$znl000$fabric-screen-api-v1$invokeKeyPressedEvents(class_309.java:1166)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_309.method_1466(class_309.java:423)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_309.method_22678(class_309.java:527)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_1255.execute(class_1255.java:110)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_309.method_22676(class_309.java:527)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_1041.method_15998(class_1041.java:318)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.method_1523(class_310.java:1361)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//net.minecraft.client.main.Main.main(Main.java:267)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[10:59:41] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2680 fi.dy.masa.litematica.world.WorldSchematic.getBlockState(net.minecraft.class_2338)'
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.utils.schematic.litematica.LitematicaHelper.a(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.dq.buildOpenLitematic(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	at knot//baritone.bb.execute(Unknown Source)
[10:59:41] [Render thread/INFO]: [STDERR]: 	... 28 more

## How to reproduce
just use the '#litematica' command with my mods and minecraft version

## Modified settings
none

**Comment by ZacSharp** [comment]
This is a known problem and a fix is already waiting to be merged into the 1.21.1 branch (1.21.4 will follow).
