### ISSUE TITLE
Baritone keeps crashing when I execute the command .b build

### ISSUE THREAD

**Issue by 2b2ter** [cabaletta/baritone#504]
I'm using 1.12.2
When I execute the command the game crashes instantly.
I tried to uninstall all other mods but has no difference
The schematica will load and the game crashes
Help!

**Comment by ZeroMemes** [comment]
Please provide a crash log so that the issue can be diagnosed.

**Comment by DananaBanana** [comment]
Same problem here!
This is my error when i do #build. (Crashes)
`---- Minecraft Crash Report ----
// There are four lights!

Time: 7/9/19 9:13 AM
Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$2800/244501306.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zef000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$2618/1620068262.run(Unknown Source)
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/450483646.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(SourceFile:309)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$2800/244501306.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zef000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$2618/1620068262.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: cjg
Stacktrace:
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/450483646.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['DananaBanana'/1032, l='MpServer', x=1265.32, y=68.99, z=-2660.56]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-1508,73,464), Chunk: (at 12,4,0 in -95,29; contains blocks -1520,0,464 to -1505,255,479), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 135609 game time, 201981615 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [ctj['DananaBanana'/1032, l='MpServer', x=1265.32, y=68.99, z=-2660.56]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313941856 bytes (299 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz`

**Comment by dragonfly54** [comment]
same but it does not crash it doesn't let me interact whit the gui

**Comment by StijnSimons** [comment]
Are you using a schematic including non-1.13 blocks?

**Comment by 0-x-2-2** [comment]
If you are on 1.13 this issue is unrelated.
