### ISSUE TITLE
Baritone #build crash

### ISSUE THREAD

**Issue by MrDodojo** [cabaletta/baritone#506]
Hey, when I try to load/build my schematic(nn-n.schematic) it gives some weird behaviour,
if I type .b build nn-n it just says loading but doesn't do anything, and if I try #build nn-n it crashes with a log.
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/9/19 5:22 PM
Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$3415/2131693643.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zef000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$3412/1015091036.run(Unknown Source)
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/778350106.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(SourceFile:309)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$3415/2131693643.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zef000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$3412/1015091036.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: cjg
Stacktrace:
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/778350106.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['MrDodojo'/260, l='MpServer', x=-117.63, y=4.00, z=-258.30]]
	Chunk stats: MultiplayerChunkCache: 574, 574
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-112,4,-256), Chunk: (at 0,0,0 in -7,-16; contains blocks -112,0,-256 to -97,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1671 game time, 1671 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 122 total; [ajt['Cow'/59, l='MpServer', x=-185.19, y=4.00, z=-297.13], ajt['Cow'/60, l='MpServer', x=-182.27, y=4.00, z=-291.59], ajt['Cow'/61, l='MpServer', x=-183.29, y=4.00, z=-292.25], ajt['Cow'/62, l='MpServer', x=-175.84, y=4.00, z=-295.54], aka['Pig'/63, l='MpServer', x=-182.78, y=4.00, z=-293.81], aka['Pig'/64, l='MpServer', x=-187.40, y=4.00, z=-297.60], aka['Pig'/65, l='MpServer', x=-180.86, y=4.00, z=-295.04], aka['Pig'/66, l='MpServer', x=-184.70, y=4.00, z=-293.61], ano['Slime'/67, l='MpServer', x=-183.65, y=4.00, z=-289.92], ano['Slime'/68, l='MpServer', x=-184.36, y=4.00, z=-244.83], ano['Slime'/69, l='MpServer', x=-176.46, y=4.28, z=-248.18], akp['Donkey'/70, l='MpServer', x=-176.50, y=4.00, z=-214.50], ajt['Cow'/71, l='MpServer', x=-176.50, y=4.00, z=-210.50], ano['Slime'/72, l='MpServer', x=-183.09, y=4.00, z=-221.99], ajt['Cow'/73, l='MpServer', x=-186.55, y=4.00, z=-204.43], ano['Slime'/74, l='MpServer', x=-177.27, y=4.00, z=-199.81], ano['Slime'/75, l='MpServer', x=-186.60, y=5.18, z=-200.90], ano['Slime'/76, l='MpServer', x=-182.61, y=4.50, z=-212.47], ano['Slime'/83, l='MpServer', x=-169.43, y=4.00, z=-294.09], ajr['Chicken'/84, l='MpServer', x=-160.50, y=4.00, z=-243.50], ajr['Chicken'/85, l='MpServer', x=-166.14, y=4.00, z=-250.17], ano['Slime'/86, l='MpServer', x=-166.77, y=4.00, z=-242.70], ano['Slime'/87, l='MpServer', x=-170.86, y=5.00, z=-241.38], ajr['Chicken'/88, l='MpServer', x=-164.16, y=4.00, z=-237.89], ano['Slime'/89, l='MpServer', x=-169.76, y=5.25, z=-227.91], ajt['Cow'/90, l='MpServer', x=-164.75, y=4.00, z=-206.84], akf['Sheep'/94, l='MpServer', x=-145.50, y=4.00, z=-312.50], akf['Sheep'/95, l='MpServer', x=-148.55, y=4.00, z=-310.40], akf['Sheep'/96, l='MpServer', x=-149.50, y=4.00, z=-309.50], akf['Sheep'/97, l='MpServer', x=-149.50, y=4.00, z=-307.50], aka['Pig'/98, l='MpServer', x=-147.50, y=4.00, z=-288.50], aka['Pig'/99, l='MpServer', x=-150.48, y=4.00, z=-282.55], aka['Pig'/100, l='MpServer', x=-145.50, y=4.00, z=-285.50], ajr['Chicken'/101, l='MpServer', x=-152.14, y=4.00, z=-256.91], ajr['Chicken'/102, l='MpServer', x=-155.15, y=4.00, z=-243.42], ajr['Chicken'/103, l='MpServer', x=-157.23, y=4.00, z=-234.88], ajr['Chicken'/104, l='MpServer', x=-156.50, y=4.00, z=-247.50], ajr['Chicken'/105, l='MpServer', x=-148.82, y=4.00, z=-254.41], ajr['Chicken'/106, l='MpServer', x=-146.12, y=4.00, z=-239.44], ajr['Chicken'/107, l='MpServer', x=-151.86, y=4.00, z=-248.09], ajr['Chicken'/108, l='MpServer', x=-154.50, y=4.00, z=-197.50], ajr['Chicken'/109, l='MpServer', x=-158.63, y=4.00, z=-192.07], akf['Sheep'/110, l='MpServer', x=-150.63, y=4.00, z=-197.24], ano['Slime'/111, l='MpServer', x=-152.45, y=4.00, z=-198.21], ajr['Chicken'/112, l='MpServer', x=-151.50, y=4.00, z=-191.50], aka['Pig'/120, l='MpServer', x=-143.50, y=4.00, z=-288.50], ajr['Chicken'/121, l='MpServer', x=-137.88, y=4.00, z=-263.41], ajr['Chicken'/122, l='MpServer', x=-138.56, y=4.00, z=-267.13], akf['Sheep'/123, l='MpServer', x=-143.50, y=4.00, z=-213.50], akf['Sheep'/124, l='MpServer', x=-143.50, y=4.00, z=-214.50], akf['Sheep'/125, l='MpServer', x=-140.50, y=4.00, z=-217.82], ajt['Cow'/126, l='MpServer', x=-143.23, y=4.00, z=-208.45], ano['Slime'/127, l='MpServer', x=-136.25, y=5.02, z=-210.61], ano['Slime'/128, l='MpServer', x=-128.53, y=4.00, z=-215.85], ano['Slime'/129, l='MpServer', x=-128.53, y=4.00, z=-213.16], ano['Slime'/132, l='MpServer', x=-120.03, y=4.00, z=-285.21], ano['Slime'/133, l='MpServer', x=-107.89, y=5.00, z=-225.68], aka['Pig'/145, l='MpServer', x=-103.60, y=4.00, z=-324.44], aka['Pig'/146, l='MpServer', x=-105.38, y=4.00, z=-331.26], aka['Pig'/147, l='MpServer', x=-103.25, y=4.00, z=-323.39], aka['Pig'/148, l='MpServer', x=-108.27, y=4.00, z=-317.63], ajr['Chicken'/149, l='MpServer', x=-96.50, y=4.00, z=-306.50], ajr['Chicken'/150, l='MpServer', x=-98.50, y=4.00, z=-302.50], ano['Slime'/151, l='MpServer', x=-102.02, y=4.00, z=-296.39], ano['Slime'/152, l='MpServer', x=-101.47, y=5.00, z=-238.98], ano['Slime'/153, l='MpServer', x=-103.43, y=4.50, z=-213.85], ano['Slime'/154, l='MpServer', x=-114.73, y=4.14, z=-221.47], ano['Slime'/155, l='MpServer', x=-116.77, y=5.18, z=-208.34], ano['Slime'/156, l='MpServer', x=-107.54, y=4.00, z=-195.64], ano['Slime'/157, l='MpServer', x=-98.31, y=4.00, z=-194.63], ano['Slime'/158, l='MpServer', x=-104.94, y=4.00, z=-192.78], ano['Slime'/159, l='MpServer', x=-97.03, y=4.42, z=-209.25], ajr['Chicken'/161, l='MpServer', x=-92.50, y=4.00, z=-306.50], ajr['Chicken'/162, l='MpServer', x=-94.49, y=4.00, z=-304.23], ano['Slime'/163, l='MpServer', x=-81.22, y=4.00, z=-291.84], ano['Slime'/164, l='MpServer', x=-85.23, y=4.00, z=-300.11], ano['Slime'/165, l='MpServer', x=-81.46, y=5.00, z=-287.93], akf['Sheep'/166, l='MpServer', x=-79.78, y=4.00, z=-285.74], akf['Sheep'/167, l='MpServer', x=-82.50, y=4.00, z=-285.50], akf['Sheep'/168, l='MpServer', x=-82.83, y=4.00, z=-284.05], ano['Slime'/169, l='MpServer', x=-84.95, y=4.00, z=-188.43], ano['Slime'/170, l='MpServer', x=-97.23, y=4.00, z=-188.07], ano['Slime'/171, l='MpServer', x=-95.12, y=4.00, z=-186.33], aka['Pig'/172, l='MpServer', x=-68.61, y=4.00, z=-306.59], aka['Pig'/173, l='MpServer', x=-67.30, y=4.00, z=-307.57], ano['Slime'/174, l='MpServer', x=-63.32, y=5.17, z=-315.18], akf['Sheep'/175, l='MpServer', x=-74.72, y=4.00, z=-284.58], ano['Slime'/176, l='MpServer', x=-76.80, y=5.25, z=-278.96], ano['Slime'/177, l='MpServer', x=-75.15, y=5.18, z=-231.20], akq['Horse'/178, l='MpServer', x=-74.50, y=4.00, z=-180.50], ajt['Cow'/179, l='MpServer', x=-75.42, y=4.00, z=-192.20], ajt['Cow'/184, l='MpServer', x=-63.11, y=4.00, z=-335.04], ajt['Cow'/186, l='MpServer', x=-52.48, y=4.00, z=-338.21], akq['Horse'/188, l='MpServer', x=-56.03, y=4.00, z=-330.46], akq['Horse'/189, l='MpServer', x=-55.53, y=4.00, z=-332.67], aka['Pig'/190, l='MpServer', x=-57.66, y=4.00, z=-313.86], aka['Pig'/191, l='MpServer', x=-62.92, y=4.00, z=-309.38], akf['Sheep'/192, l='MpServer', x=-53.51, y=4.00, z=-306.40], akf['Sheep'/193, l='MpServer', x=-53.83, y=4.00, z=-309.32], akf['Sheep'/194, l='MpServer', x=-53.35, y=4.00, z=-307.47], akf['Sheep'/195, l='MpServer', x=-55.50, y=4.00, z=-303.50], ano['Slime'/196, l='MpServer', x=-67.62, y=4.50, z=-280.92], ano['Slime'/197, l='MpServer', x=-57.55, y=5.25, z=-272.62], ano['Slime'/198, l='MpServer', x=-56.74, y=4.00, z=-285.34], ano['Slime'/199, l='MpServer', x=-52.57, y=4.00, z=-284.24], ano['Slime'/200, l='MpServer', x=-59.60, y=4.50, z=-276.38], ano['Slime'/201, l='MpServer', x=-56.05, y=5.00, z=-273.96], ano['Slime'/202, l='MpServer', x=-53.55, y=4.00, z=-280.36], ano['Slime'/203, l='MpServer', x=-40.82, y=5.18, z=-260.96], ano['Slime'/204, l='MpServer', x=-58.91, y=4.00, z=-244.65], ano['Slime'/205, l='MpServer', x=-61.10, y=4.00, z=-243.51], ajr['Chicken'/215, l='MpServer', x=-42.50, y=4.00, z=-319.50], ajr['Chicken'/216, l='MpServer', x=-42.49, y=4.00, z=-318.69], ajr['Chicken'/217, l='MpServer', x=-41.50, y=4.00, z=-319.50], ajr['Chicken'/218, l='MpServer', x=-44.30, y=4.00, z=-319.20], akf['Sheep'/219, l='MpServer', x=-43.26, y=4.00, z=-298.43], akf['Sheep'/220, l='MpServer', x=-43.42, y=4.00, z=-296.54], akf['Sheep'/221, l='MpServer', x=-40.46, y=4.00, z=-294.74], akf['Sheep'/222, l='MpServer', x=-47.21, y=4.00, z=-297.26], ano['Slime'/224, l='MpServer', x=-41.01, y=4.00, z=-291.27], ano['Slime'/225, l='MpServer', x=-41.03, y=4.50, z=-283.38], ctj['MrDodojo'/260, l='MpServer', x=-117.63, y=4.00, z=-258.30]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1178673912 bytes (1124 MB) / 1711276032 bytes (1632 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: Radeon RX 580 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12001.7006, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
```

**Comment by leijurv** [comment]
Builder don't work on 1.13

**Comment by ZeroMemes** [comment]
It can be fixed soooo...

**Comment by leijurv** [comment]
I thought there was already an issue for this tho

**Comment by StijnSimons** [comment]
I guess schematics still use a numeric ID?

**Comment by DaMatrix** [comment]
yes, afaik the standard hasn't been updated to use anything else

**Comment by StijnSimons** [comment]
And whats the stairs issue about, block meta?

**Comment by qiujiangkun** [comment]
Not work in 1.14.4, either

**Comment by scorbett123** [comment]
This has now been fixed, I hope.
