### ISSUE TITLE
Baritone doesn't mine redstone ore

### ISSUE THREAD

**Issue by LoganDark** [cabaletta/baritone#569]
## Some information
Operating system: macOS 10.14.5 Mojave
Java version: 1.8.0_212 JDK
Minecraft version: 1.12.2
Baritone version: baritone-standalone-forge-1.2.7
Forge mods (if used): FoamFix@0.10.5-1.12.2, Controlling@3.0.7, ForgeHax@2.9.0, InventoryTweaks@1.63+release.109.220f184, JEI@4.15.0287, JourneyMap@1.12.2-5.5.5b9, Mouse Tweaks@2.10, VanillaFix@1.0.10-SNAPSHOT, ReAuth@3.6.0
Forge version: 14.23.5.2838

SMP on the <details>`play.cursedcraft.com`</details> server, if you can't replicate it in singleplayer.

## Exception, error or logs
**Relevant** logs (get back to me if you want the full `debug.log`):
```
[18:23:25] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §5[§dBaritone§5]§7 Started mining blocks of type [diamond_ore, gold_ore, redstone_ore, lapis_ore]
[18:24:08] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §5[§dBaritone§5]§7 ok canceled
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at baritone.fz.a(Unknown Source)
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at baritone.fz.a(Unknown Source)
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at baritone.fz.b(Unknown Source)
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:24:08] [pool-6-thread-17/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
```

There are no baritone logs or tracebacks after this.

## How to reproduce
Mine redstone_ore.

Baritone taps the block with a pickaxe and then moves on. Going back repeatedly to the same block, but never actually breaking it.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZakME** [comment]
Redstone has 2 id's:
redstone_ore and lit_redstone_ore

When baritone taps it with a pickaxe it changes to the lit_redstone_ore id and baritone no longer sees it as a block to mine. An easy fix is to also add lit_redstone_ore to your ore mining list, but there could also be a QOL fix for this in baritone as well.

**Comment by leijurv** [comment]
Yes, do `.b mine redstone_ore lit_redstone_ore`. Impact does this when you select redstone ore.
