### ISSUE TITLE
Extra Utilities 2 + Baritone = Crash

### ISSUE THREAD

**Issue by Darkar25** [cabaletta/baritone#573]
## Some information
Operating system: Windows 7 64x
Java version: 1.8.0_212
Minecraft version: 1.12.2
Baritone version: idk
Forge mods (if used): 
SecurityCraft
AncientWarfare
BackPacks
Baubles
CarryOn
CodeChickenLib
CustomNPCs
Axtra Utilities 2
mrCrayFish`s furniture
HWYLA
Iron Chest
JEI
JourneyMap
Mantle
Millenaire
OptiFine
Overlord
TConstruct
VariedCommodities

## Exception, error or logs
java.lang.NullPointerException: Unexpected error
	at com.rwtema.extrautils2.backend.XUBlockStatic.getWorldModel(XUBlockStatic.java:93)
	at com.rwtema.extrautils2.backend.XUBlock.func_176205_b(XUBlock.java:464)
	at baritone.ad.b(Unknown Source)
	at baritone.ad.a(Unknown Source)
	at baritone.ad.a(Unknown Source)
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at baritone.x.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zeg000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## How to reproduce
I placed Solar Panel(4112:0) and then after 3-5 seconds minecraft crashed

## Final checklist
- [ + ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ + ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ + i think ] I have not used any OwO's or UwU's in this issue.

**Comment by Master-64** [comment]
Yeah, Extra Utilities 2 and Baritone don't work well together.

**Comment by Deauthorized** [comment]
that's just a conflict, not much you can really do except either remove baritone or extra utilities

**Comment by ZeroMemes** [comment]
@deauthorized that’s what can be done to fix it now, but there’s no conflict. This is something that can be resolved and I have intention to do so.

**Comment by ZeroMemes** [comment]
Fixed by https://github.com/cabaletta/baritone/pull/1087
