### ISSUE TITLE
Auto build does not work on 1.14.4

### ISSUE THREAD

**Issue by Risendale** [cabaletta/baritone#627]
## Some information
Operating system: Windows 10
Java version:  1.8.0_51
Minecraft version: 1.14.4
Baritone version: 1.4.0
Forge mods (if used): nope

## Exception, error or logs
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 7/23/19 11:09 PM
Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bq.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.v.a(Unknown Source)
	at baritone.v$$Lambda$3048/727086923.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.v.onSendChatMessage(Unknown Source)
	at dmp.handler$sendChatMessage$zza000(SourceFile)
	at dmp.f(SourceFile)
	at dcl.sendMessage(SourceFile:318)
	at dcl.sendMessage(SourceFile:311)
	at dbl.keyPressed(SourceFile:129)
	at cya.a(SourceFile:410)
	at cya$$Lambda$3046/1281792763.run(Unknown Source)
	at dcl.wrapScreenError(SourceFile:441)
	at cya.a(SourceFile:408)
	at cya$$Lambda$1516/905812091.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at cuo.c(SourceFile:291)
	at cyc.b(SourceFile:1027)
	at cyc.e(SourceFile:976)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.dx.<init>(Unknown Source)
	at baritone.bq.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.v.a(Unknown Source)
	at baritone.v$$Lambda$3048/727086923.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.v.onSendChatMessage(Unknown Source)
	at dmp.handler$sendChatMessage$zza000(SourceFile)
	at dmp.f(SourceFile)
	at dcl.sendMessage(SourceFile:318)
	at dcl.sendMessage(SourceFile:311)
	at dbl.keyPressed(SourceFile:129)
	at cya.a(SourceFile:410)
	at cya$$Lambda$3046/1281792763.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: dbl
Stacktrace:
	at dcl.wrapScreenError(SourceFile:441)
	at cya.a(SourceFile:408)
	at cya$$Lambda$1516/905812091.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at cuo.c(SourceFile:291)

-- Affected level --
Details:
	All players: 1 total; [dmp['LeadFreeCandy'/65, l='MpServer', x=-100.50, y=4.00, z=136.50]]
	Chunk stats: Client Chunk Cache: 1369, 961
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-96,4,128), Chunk: (at 0,0,0 in -6,8; contains blocks -96,0,128 to -81,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 640 game time, 640 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:425)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 954824536 bytes (910 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
## How to reproduce
try to use #build for any schematic

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by leijurv** [comment]
Correct it does not. Schematic building is 1.12.2 only.

**Comment by Risendale** [comment]
rip, any eta?

**Comment by StijnSimons** [comment]
When the schematics change to actual named ids and not numeric ones.
Or we'd have to make a conversion from numeric id -> named id.

**Comment by 0-x-2-2** [comment]
> When the schematics change to actual named ids and not numeric ones.
> Or we'd have to make a conversion from numeric id -> named id.

baritone needs to switch to the sponge format instead for 1.13+ just like worldedit

**Comment by StijnSimons** [comment]
Yeah that’d be way better.

**Comment by GrimReaperFloof** [comment]
I'd like to have building for 1.13+ yeah. Would be nice if you could move over to a new 1.13 compatible format or something, at least if there would be tools available to convert something into that new format.
