### ISSUE TITLE
[1.14.4] Stepping on a shulker box crashes the game

### ISSUE THREAD

**Issue by Powerlated** [cabaletta/baritone#645]
Baritone only, no Forge mods. 1.14.4, default Minecraft launcher. Dropbox download.
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/24/19 3:18 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at brn.a(SourceFile:242)
	at bvt.a(SourceFile:210)
	at bvt.h(SourceFile:206)
	at bmv.b(SourceFile:476)
	at bvt.b(SourceFile:221)
	at bvt.i(SourceFile:217)
	at bvt.o(SourceFile:356)
	at bmv.d(SourceFile:312)
	at bvt.e(SourceFile:152)
	at baritone.ab.c(Unknown Source)
	at baritone.ab.b(Unknown Source)
	at baritone.ab.b(Unknown Source)
	at baritone.g.a(Unknown Source)
	at baritone.g.onTick(Unknown Source)
	at baritone.v.a(Unknown Source)
	at baritone.v$$Lambda$1679/1272009759.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.v.onTick(Unknown Source)
	at cyc.handler$runTick$zzg000(SourceFile)
	at cyc.m(SourceFile:1401)
	at cyc.e(SourceFile:925)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at brn.a(SourceFile:242)
	at bvt.a(SourceFile:210)
	at bvt.h(SourceFile:206)
	at bmv.b(SourceFile:476)
	at bvt.b(SourceFile:221)
	at bvt.i(SourceFile:217)
	at bvt.o(SourceFile:356)
	at bmv.d(SourceFile:312)
	at bvt.e(SourceFile:152)
	at baritone.ab.c(Unknown Source)
	at baritone.ab.b(Unknown Source)
	at baritone.ab.b(Unknown Source)
	at baritone.g.a(Unknown Source)
	at baritone.g.onTick(Unknown Source)
	at baritone.v.a(Unknown Source)
	at baritone.v$$Lambda$1679/1272009759.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.v.onTick(Unknown Source)
	at cyc.handler$runTick$zzg000(SourceFile)

-- Affected level --
Details:
	All players: 3 total; [dmp['Powerlated'/118004, l='MpServer', x=-459.63, y=17.00, z=-3738.14], dmq['M1_abram'/112588, l='MpServer', x=-460.85, y=16.00, z=-3737.83], dmq['Ryan2719660'/114775, l='MpServer', x=-234.03, y=91.00, z=-3834.26]]
	Chunk stats: Client Chunk Cache: 1521, 1136
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-181,75,251), Chunk: (at 11,4,11 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9533100 game time, 10903610 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4429886024 bytes (4224 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel Xeon Processor (Cascadelake)
```

**Comment by Mhowser** [comment]
You know you can edit your previous issue and put the crash log there. Click the 3 dots on the top right of the comment box and click edit.

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/afebdce1f82969a79d029222fc485668be16c094
