### ISSUE TITLE
forge mod pickaxes

### ISSUE THREAD

**Issue by jackie4289** [cabaletta/baritone#646]
so i have ic2 and baritone installed, .forge 1.12.2 I have a diamond drill from ic2 mod and I dont move because baritone doesnt think its a pickaxe... any way I can change it to make the drill compatible with baritone?

**Comment by SFort** [comment]
This seems to be a issue specific to the IC2 drill
possibly because its also a shovel
(since the bronze pickaxe / chainsaw have no issues)
<details open>
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: java.lang.NullPointerException
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at ic2.core.item.tool.ItemDrill.getPlayerHoldingItem(ItemDrill.java:106)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at ic2.core.item.tool.ItemDrill.func_150893_a(ItemDrill.java:76)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:212)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.gn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.gn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.gn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at java.util.function.Function.lambda$compose$0(Function.java:68)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.gn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.dj.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.en.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.do.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.dn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.dc.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.dd.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at baritone.cn.a(Unknown Source)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd:a:-1]: 	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by jackie4289** [comment]
> This seems to be a issue specific to the IC2 drill
> possibly because its also a shovel
> (since the bronze pickaxe / chainsaw have no issues)
> 
> [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: java.lang.NullPointerException [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at ic2.core.item.tool.ItemDrill.getPlayerHoldingItem(ItemDrill.java:106) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at ic2.core.item.tool.ItemDrill.func_150893_a(ItemDrill.java:76) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:212) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.gn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.gn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.gn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at java.util.function.Function.lambda$compose$0(Function.java:68) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at java.util.HashMap.computeIfAbsent(HashMap.java:1127) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.gn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.dj.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.en.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.do.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.dn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.dc.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.dd.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at baritone.cn.a(Unknown Source) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [04:35:05] [pool-4-thread-5/INFO] [STDERR]: [baritone.dd🅰️-1]: at java.lang.Thread.run(Thread.java:748)

can it be solved? or will I have to use a diamond pic?

**Comment by SFort** [comment]
There's no config for tools/slot used so until a fixed version comes out you can't have a ic2 drill in your inventory
note: for some wierd reason this is not a problem with build

**Comment by jackie4289** [comment]
> There's no config for tools/slot used so until a fixed version comes out you can't have a ic2 drill in your inventory
> note: for some wierd reason this is not a problem with build

build? im just using the impact client

**Comment by SFort** [comment]
@jackie4289 
I was just making note thats its wierd that it works with #build but crashes on #mine, 
impact has nothing todo with it

@leijurv pretty please fix
This is still a issue in v1.2.8

**Comment by usereewrjrjeejr** [comment]
Stop using mods
