### ISSUE TITLE
Wondering if this startup error is fixable

### ISSUE THREAD

**Issue by Johnnyroo2000** [cabaletta/baritone#669]
## What do you need help with?
This occurs on startup when i added the forge baritone to the mod-pack Dungeons Dragons and Space Shuttles and was wondering if there is any way to fix the double overrides and make baritone compatible. (occurs with both stand alone and non stand alone and i have had success wit installing baritone on many other packs ie. first time wit this issues)

[21:28:38] [main/FATAL]: Mixin prepare failed preparing MixinBlockPos in mixins.baritone.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.baritone.json:MixinBlockPos target net.minecraft.util.math.BlockPos was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.baritone.json:MixinBlockPos target net.minecraft.util.math.BlockPos was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [baritone-standalone-forge-1.2.8.jar:1.2.8]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[21:28:38] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinBlockPos] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.baritone.json:MixinBlockPos target net.minecraft.util.math.BlockPos was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[baritone-standalone-forge-1.2.8.jar:1.2.8]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more

**Comment by Johnnyroo2000** [comment]
https://gist.github.com/Johnnyroo2000/b3972430eba487d2746bebe627ca3bd3
Full log here

**Comment by JJJollyjim** [comment]
Same issue against FTB Builders' Paradise. The conflicting mod is MalisisCore, (used by MalisisDoors)

**Comment by usereewrjrjeejr** [comment]
Stop using it with mods

**Comment by JJJollyjim** [comment]
@usereewrjrjeejr that's one option I guess... Is that recommend somewhere?

Alternatively, we were able to get it in by removing MixinBlockPos (since it's only used to improve debug output)

**Comment by Johnnyroo2000** [comment]
Thanks! I will try that and let you know how it goes.
