### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by chooch1911** [cabaletta/baritone#699]
## Some information
Operating system: windows 12
Java version:  java se8 update 221
Minecraft version: 1.14
Baritone version: 
Forge mods (if used): none

## Exception, error or logs
GameStarter running! net.minecraft.launchwrapper.Launch
[18:56:13] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[18:56:13] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[18:56:13] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[18:56:13] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at info.mineshafter.GameStarter.main(GameStarter.java:33) [ms-starter.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 11 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

## How to reproduce
launch the game
EDIT: if i delete the .minecraft folder and reinstall it works the first time but if i leave the game it dosent launch
## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by babbaj** [comment]
>info.mineshafter.GameStarter.main

sounds like a pozzed launcher

**Comment by StijnSimons** [comment]
Yo minewaft too expwenswive wight now

**Comment by StijnSimons** [comment]
Dont be a poorfag and buy minecraft.

**Comment by LukewarmCat** [comment]
Same exact thing happening to me, this isn't because of crācked minecraft. Maybe it's something else?

**Comment by StijnSimons** [comment]
nOt pOzZeD
![image](https://user-images.githubusercontent.com/17461028/85989754-41c66780-b9f1-11ea-8539-f79093d74795.png)
