### ISSUE TITLE
Path calculation thread exception while pathing through cached snowy biome

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#87]
<img width="652" alt="screen shot 2018-08-25 at 7 05 51 am" src="https://user-images.githubusercontent.com/3837873/44619104-265b0600-a836-11e8-99ee-0037a44ab2aa.png">

```
[07:05:46] [Thread-206/INFO]: [CHAT] §5[§dBaritone§5]§7 Exception: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
[07:05:46] [Thread-206/INFO]: [STDERR]: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
[07:05:46] [Thread-206/INFO]: [STDERR]:     at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:185)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at net.minecraft.block.BlockSnow.isPassable(BlockSnow.java:53)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.movement.MovementHelper.canWalkThrough(MovementHelper.java:85)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.movement.movements.MovementTraverse.calculateCost(MovementTraverse.java:92)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.movement.Movement.calculateCost0(Movement.java:89)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.movement.Movement.getCost(Movement.java:77)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.calc.AStarPathFinder.calculate0(AStarPathFinder.java:125)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.pathing.calc.AbstractNodeCostSearch.calculate(AbstractNodeCostSearch.java:77)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.behavior.impl.PathingBehavior.findPath(PathingBehavior.java:301)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at baritone.behavior.impl.PathingBehavior.lambda$findPathInNewThread$2(PathingBehavior.java:239)
[07:05:46] [Thread-206/INFO]: [STDERR]:     at java.lang.Thread.run(Thread.java:748)
```

I *think* that what causes this is if you cache a top layer block as snow, then you later BlockStateInterface.get it, it tells you the IBlockState is the default for BlockSnow. But then when you call canWalkThrough which calls IBlockState.isPassable, it gets the snow depth from the actual world not the cache. But it's no longer snow, it's air, because it's out of bounds and in an EmptyChunk. This causes an IllegalArgumentException.

**Comment by leijurv** [comment]
This should also apply to doors, fence gates, and trapdoors that are exposed to the sky (as well as snow).

**Comment by leijurv** [comment]
Those four block types are the ones that use the world passed to the `isPassable` check to get their IBlockState metadata. Snow checks if its level is less than 5, and doors, fence gates, and trapdoors check if they're open.
